### ISSUE TITLE
Can't calibrate new g6 + new transmitter: "invalid impossible slope"

### ISSUE THREAD

**Issue by lee-b** [NightscoutFoundation/xDrip#1008]
On the beta update channel.

I changed my sensor and transmitter today, stopped & started sensor, changed the transmitter code, paired the bluetooth device, and eventually got readings.  However, calibration won't work.  The error is:

"Got invalid impossible slope calibration!"

However, the calibrations I've tried entering were within 0.1 mmol of the sensor value on the first attempt, and 1 mmol on the second attempt.

This is the first time I've changed transmitter with a g6.  Seems that the beta channel also updated, but I find this very hard to know for sure -- does xdrip+ even have a visible version number on updates?

Seems like the slope calculation is wrong, or the validation of slopes is wrong on new transmitters, or old values are being incorrectly included in stopped / started sensors since the new beta.

**Comment by lee-b** [comment]
Just tried the latest nightly.  Same issue.

**Comment by jamorham** [comment]
What firmware version does your new G6 transmitter report in System Status?

**Comment by lee-b** [comment]
A few additional observations:

* Initial calibration still seems to actually work.  The problem is the result intepretation, and xdrip thinking that it hasn't worked.  So it stays in initial calibration state, and keeps prompting.

* None of the following work, probably just due to the "initial calibration required" state:

* Entering a normal calibration in xdrip
* Choosing calibrate from a pre-existing BG sample point (point remains a square, rather than becoming a circle)
* Entering a calibration from AAPS.

**Comment by HeyImPuni** [comment]
Same issue here. Like @lee-b said, seems like that the calibrations are working fine but xDrip thinks that they got deleted - at least that's what the `Events Log` tells me.

**Comment by lee-b** [comment]
I think xdrip is purposefully deleting them as invalid, because it misinterprets the results from the G6 transmitter, and thinks that the calibration was rejected as invalid by the G6 transmitter.

i.e., the real problem seems to be that XDrip doesn't yet know how to handle the new G6 transmitter protocol's calibration method, or its calibration response code changes.

**Comment by joshhiram** [comment]
Just changed my son's transmitter. It is serial number 81A***. Same issue. Tried alpha release and nightly release with no effect. Firmware version 1.6.5.25. Xdrip version 7d97b62-2019.09.30.

**Comment by stackenblochen** [comment]
I have the same issue with the latest nightly build (2019.10.08) and G6 transmitter (8Gxxxx, firmware: 2.18.2.88). xDrip shows a BG value of 103, but rejects the initial clibration of 71 ad 74. Also, adding a single calibration (through the add... dialog) is rejected.

**Comment by jamorham** [comment]
I believe that if you're seeing a message about impossible slope then this means xDrip is trying to use the xDrip algorithm (not-native). It isn't possible to use the xDrip calibration algorithm on transmitters with 2.18.2.88 firmware as they do not provide the raw sensor data.

Please check your settings that you are using the `Native Algorithm`, `OB1 collector` and that you do not have `Fallback to xDrip` enabled.

**Comment by joelm335** [comment]
Same problem here.  New transmitter 8Gxxxx, firmware 2.18.2.88, Native algorithm OB1 collector.  Attempted initial calibration - calibration rejected impossible slope.  BG running flat - 4.1 two fingersticks at 4.2 and 4.4.  Was using 19 August nightly - now updated to latest 08 October nightly but same problem.  I do not have fallback to xDrip checked. 

Also, although readings are coming through I am getting  lots of errors noted in the logs with every 5 minute reading (OB1 collector).  See attached screenshots


![8G cal rej](https://user-images.githubusercontent.com/32453941/66566119-10a0c100-eb5c-11e9-94a0-99b2da651f82.jpg)
![8G error1](https://user-images.githubusercontent.com/32453941/66566137-1ac2bf80-eb5c-11e9-827d-d9dfd55ea7e0.jpg)
![8G error2](https://user-images.githubusercontent.com/32453941/66566149-21513700-eb5c-11e9-9e09-46d634d43374.jpg)
,

**Comment by stackenblochen** [comment]
@jamorham thanks for the quick reply. I actually use the settings as described in your previous post:

- under settings > G5 debug settings
- Use the OB 1 Collector [checked]
- Native Algorithm [checked]
- Fallback to xDrip [not checked]

Please let me know if I can somehow help debugging this issue.

Update: It seems that my calibration was accepted actually. After some readings that were shown pre-calibration, the values switched to the calibrated ones. I will attach a screenshot, hope its helpful.

![Screenshot_20191010-135830](https://user-images.githubusercontent.com/15332336/66566815-2d41f680-eb66-11e9-97fb-3fe44d9372ef.jpg)
![Screenshot_20191010-135205](https://user-images.githubusercontent.com/15332336/66566816-2d41f680-eb66-11e9-8aa0-f6ceb2bd3069.jpg)

**Comment by jamorham** [comment]
There shouldn't be any initial calibration with G6. I am not sure why that menu option would even be available if native mode is enabled.

**Comment by joelm335** [comment]
@jamorham Thanks for getting back to me.  I have the G6 debug settings as recommended - OB1, G6 native checked and fallback to xdrip not checked (see screenshot).  It is definitely requesting an initial calibration. 

If this is of any help:  This is my 3rd G6 transmitter.  The previous two (80xxxx) ALWAYS required an initial calibration - without this no numbers would appear in xDrip (although readings were internally broadcast to AndroidAPS.  The only setting I have changed  for the 8G is to uncheck pre-emptive restarts. 

![8G initial cal](https://user-images.githubusercontent.com/32453941/66571779-c58cab00-eb67-11e9-82f5-7ab94d4dec46.jpg)
![8G debug settings](https://user-images.githubusercontent.com/32453941/66571793-cc1b2280-eb67-11e9-9982-4defdb102d8d.jpg)

**Comment by CaptainBalou** [comment]
@jamorham I also see "initial calibration" even I use G6 with calibration code. But I have never used it and I was fine with that. As soon as I needed to recalibrate it after 15+ days I used initial calibration and put the value in like value/value+1. Worked very well.

**Comment by joshhiram** [comment]
There's another issue open with more reports like mine.  When we installed
a new sensor and transmitter, xdrip+ rejected the sensor, still continued
to warm up, and presented a persistent "Initial Calibration required"
window that wouldn't go away.  We never got it working and had to the
official dexcom app on iphone.

**Comment by joelm335** [comment]
Update:  
Have now restarted sensor using the remove sensor method.  After warmup,  BG values in xDrip started at 11.5 - fingersticks showed 7.4 and 8.0.  Entered two initial calibrations, got the "rejected impossible slope" message and error logs show calibration rejected, but xDrip sensor values jumped to 7.6 and now accurate.  Menu still shows Initial Calibrations.

**Comment by lee-b** [comment]
My experience matched joelm335's exactly.  Until yesterday.  Last night, it stopped accepting "initial" calibrations -- entering them made an entry or two jump, and the calibration appears, but subsequent readings continue at the uncalibrated levels.

Tried "initial" calibrations a few more times, with no luck.  Eventually it showed the 'confused calibration' message.  Tried resetting calibrations and re-doing the initial calibration.  Got the "confused calibrations" message and error... 3... I think (sorry, it was an awkward time to record things) and "signal missed" for an extended period of time.  Then stopped and restarted the sensor.

Seemed good late last night having restarted, but woke up low this morning, calibration off by 2+mmol, and the "initial" calibrations aren't working again.  No error message this time, though.  Back to signal missed now.

This is with ff2c822-2019.09.24.  Not sure if anything related to this has changed in the nightlies since then.

**Comment by joelm335** [comment]
@lee-b - My initial attempt to do an initial calibration after the restart resulted in a jump in two entries and then it reverted to the earlier uncalibrated levels.  However when I entered the two calibrations again the calibration "held", although I still got the message and Error logs showed  that it had been rejected.  I have since calibrated it at 26 hours.  Again, 2 initial calibrations, again the error message, but again the calibration has held.  I have checked again and it is accurate within 10%.

**Comment by lee-b** [comment]
For those in need of a workaround: I've ended up installing the official dexcom app, and configuring xdrip to follow data from it via AAPS.

**Comment by oschumac** [comment]
Hi looks alike i do have the same prob. Is there some investigation on fixing xdrip ?

**Comment by acron0** [comment]
Just raising a hand to say I also have the same behaviour being described here with firmware 2.18.2.88

**Comment by joelm335** [comment]
Also just got confused calibration 1 on restart with 8G. Previous restarts have allowed calibration. This on was sensor 20.8 and fingerstick 10.9 so maybe too far off. I don’t have a receiver so just stopped and going through restart warmup again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bobsbbq** [comment]
Ok I wanted to share my sensor restart experience with my 8H transmitter. I did the pop out transmitter method before sensor expires. Restart ok, but reading off by 90+ points. Naturally I tried to calibrate. And I  guess it can't handle that much change at one time. It crashed my sensor with a Calibration 1 error and stopped working. I was able to stop and restart it again and this time after the 2 hours, I waited 20 minutes,  then did small calibrations of 9 points at a time, once a hour. It took me a while but it is now ok. 

I'm not sure what the limit is as far calibrations go. I tried 10, and 12 points on the last two and they worked ok. I  read somewhere that you could enter a calibration every 15 minutes,  but I  would use caution. 

Also remember that the 8G and 8H only work in the Native mode. You get a calibration slope error but the transmitter will except it, then xdrip deletes it. But it does work.

**Comment by wardc99** [comment]
I'm late to this party but just changed our transmitter to an 8H transmitter and having the exact same problems described here. I switched the settings and have the latest nightly build. Yesterday it disconnected for 7 hours, saying missed signal. I realize this conversation is from a while back. Are there any workarounds at this point that might help? Thanks.

**Comment by wardc99** [comment]
We're disconnected again. Is it worth trying to make this work? Is there a fix? What other options do we have to upload to a heroku nightscout website? Thanks.

**Comment by wardc99** [comment]
I'm not trying to restart I'm just trying to stay connected!

**Comment by roco5** [comment]
@jamorham I'm also getting the calibration slope error and it appears that my calibrations are not sticking.  Thoughts on a fix?  Does the calibrating twice method identified by @joelm335 ?

**Comment by dg77777** [comment]
Any updates on his?
G6 sensor is inaccurate and seems I cannot influence this through xDrip. Any workarounds?
Using the latest nightly.

**Comment by dar-kod** [comment]
> 
> 
> I believe that if you're seeing a message about impossible slope then this means xDrip is trying to use the xDrip algorithm (not-native). It isn't possible to use the xDrip calibration algorithm on transmitters with 2.18.2.88 firmware as they do not provide the raw sensor data.
> 
> Please check your settings that you are using the `Native Algorithm`, `OB1 collector` and that you do not have `Fallback to xDrip` enabled.

@jamorham is there really no way to use calibration on transmitters with 2.18.2.88 firmware? If I input `Initial Calibration`, it seems to work. And it is with checked `Native Algorithm`, `Use the OB1 Collector` and `Fallback to xDrip` is unchecked.

**Comment by gitanO0** [comment]
I just moved to an 8G... transmitter from an 81... transmitter and am getting this error.  I haven't been able to calibrate since starting it up a couple days ago.  Do we not calibrate these anymore?  What do we do if the meter says one thing and the G6 says another.  That's the case for me right now.  I've tried to "initial calibrate" several times and get the impossible slope error.  I've read the above comments and have my settings set properly but am confused about how this is supposed to work.

**Comment by nshtg** [comment]
You get the impossible slope error but the calibration still goes through to the transmitter.

**Comment by roco5** [comment]
Do you have to do two consecutive calibrations to get it to stick?  (How do
you know the calibration is being sent to transmitter?)

**Comment by nshtg** [comment]
No you don't. Check Events log it will say "Calibration accepted by transmitter".

**Comment by gitanO0** [comment]
So just ignore the slope error and ignore that it says "initial calibration" in the menu, just calibrate as I would normally?

**Comment by nshtg** [comment]
Yes

**Comment by jamorham** [comment]
I think this may also be related to an issue that should be corrected in the May 26th nightly. Are people on this thread using that?

**Comment by nshtg** [comment]
I do. When I need to calibrate the next time I will give you feedback wheter the bug is fixed or not.

**Comment by roco5** [comment]
I have not used it yet.  I'll upgrade and give feedback.

Best,
Rob Conley

**Comment by gitanO0** [comment]
I downloaded the 26th nightly yesterday and this morning I did calibrate.  It did seem to immediately move my last few points on the graph to where my calibrated value was but then went right back to the previous trend.  Like this:  I woke up at a steady trend of around 120 mg/dl.  I did a meter test and it showed 168.  I calibrated to that value using the "initial calibration" option in the menu.  Two points went right to 168 on the graph then every subsequent value went right back to the 120 area and have been there since.  So, the calibration doesn't seem to be having any effect.  I should be higher than the graph is showing by about 40 mg/dl.  I didn't see if that slope error came up though.  
Also, when I go to the side menu, I don't see any calibrate option now.  There's a calibration graph and calibration data table options but no "override calibration" or any option to actually do a calibration.

**Comment by gitanO0** [comment]
Wait, I take back the part about it not adjusting to the new calibration.  It did.  Not sure what I was seeing before.  Maybe the transmitter hadn't sync'd up with the calibrated value yet or something.

**Comment by old-square-eyes** [comment]
How is everyone getting on with this? I'm still in the dark as to whether it's even possible to calibrate. https://github.com/NightscoutFoundation/xDrip/issues/1310 seems to be similar.

**Comment by lee-b** [comment]
Seems like it's not being investigated, for whatever reason.  I gave up on using xdrip for this, and just use the patched officisl app now.  That has the added benefit of sending data to Dexcom that they'll use to approve refunds if a sensor fails.

**Comment by Navid200** [comment]
Ideally, you will give factory calibration a chance after moving from G5 to G6.
I didn't at first.  But, eventually, I did and have never looked back.
I occasionally test my blood glucose to confirm the accuracy of G6.  But, I never find a reason to calibrate (with a new sensor).

After a restart, it's a different story.
I then need to calibrate, and do and have no problem doing that.

I use "Initial calibration" for that.  But, first, I have disabled double calibration, which you can find at the following:
Settings -> Less common settings -> Advanced Calibrations
That way, initial calibration accepts a single entry.

After calibrating, xDrip shows logs suggesting that the calibration has failed.  But, it also reports that the transmitter has accepted the calibration, which is the only thing that matters.

It is important not to enter a calibration that would make a very large correction.  I always limit the calibration to 20% of the reading.  If you enter a larger correction, the transmitter may issue a confused calibration error and stop readings.

Since I limit the calibration to 20% of the reading, I may need more than one calibration.  After a calibration, I wait about 20 to 25 minutes before entering the following calibration.  After a restart, I usually get accurate results with 2 consecutive calibrations.

I never calibrate when the trend is not flat or at least very close to flat.

What your CGM shows is expected to be different than what your blood glucose meter shows, at least, when your glucose is changing:
https://youtu.be/o6bEJ3wko4g

If you have any questions, please ask.  
You can also post in the Gitter room, or in the facebook group.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
