### ISSUE TITLE
Xdrip+ cant connect with Limitter. Android 9.0

### ISSUE THREAD

**Issue by NovaProspekt7** [NightscoutFoundation/xDrip#1033]
Updated to 9.0 version yesterday(android, LG G6), latest xdrip build of 24th of September doesn't work, as well as other random versions (tried a few down to 2018 builds).
Pretty much stuck at receiving data from LimiTTer collector.

Thanks!

**Comment by laois80** [comment]
Me too, its happening every day.

**Comment by NovaProspekt7** [comment]
> Me too, its happening every day.

What you have? What troubleshooting have you tried so far?

**Comment by laois80** [comment]
Hi,Just the usual resetting calibrations, turning bluetooth on and off, uninstalling and reinstalling. I'm not very techy so that's all I can do. During initial setup it seems to not recognise miaomiao while scanning so I've charged and reset the miaomiao too but still not working.What have you tried?Sent from Samsung Mobile on O2
-------- Original message --------From: NovaProspekt7 <notifications@github.com> Date: 26/09/2019  22:16  (GMT+00:00) To: NightscoutFoundation/xDrip <xDrip@noreply.github.com> Cc: laois80 <lmmurphy1980@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [NightscoutFoundation/xDrip] Xdrip+ cant connect with Limitter. Android 9.0 (#1033) 
Me too, its happening every day.

What you have? What troubleshooting have you tried so far?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTUYKZ6QJBB2ZMWD5L3LQLURBJA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7W7QOI#issuecomment-535689273",
"url": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTUYKZ6QJBB2ZMWD5L3LQLURBJA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7W7QOI#issuecomment-535689273",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by NovaProspekt7** [comment]
Pretty much same what you've tried. I resetted the MiaoMiao through the button on the transmitter, need to wait to charge and see if it works this way, otherwise will perform a factory reset for my phone to roll back on old android version (probably will be 7.0 or something)

Hopefully this will help until a fix is out

Good luck :)

**Comment by laois80** [comment]
Didnt even think about android updates. I'll keep that in mind. Thanks  good luck to you!Sent from Samsung Mobile on O2
-------- Original message --------From: NovaProspekt7 <notifications@github.com> Date: 26/09/2019  22:40  (GMT+00:00) To: NightscoutFoundation/xDrip <xDrip@noreply.github.com> Cc: laois80 <lmmurphy1980@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [NightscoutFoundation/xDrip] Xdrip+ cant connect with Limitter. Android 9.0 (#1033) Pretty much same what you've tried. I resetted the MiaoMiao through the button on the transmitter, need to wait to charge and see if it works this way, otherwise will perform a factory reset for my phone to roll back on old android version (probably will be 7.0 or something)
Hopefully this will help until a fix is out
Good luck :)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU3LOQSDABWJ6LPSWNDQLUT6PA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7XBLCA#issuecomment-535696776",
"url": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU3LOQSDABWJ6LPSWNDQLUT6PA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7XBLCA#issuecomment-535696776",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jamorham** [comment]
Have you tried playing around with the `Use Scanning` and `Trust Auto-Connect` advanced bluetooth settings in xDrip settings? Use the search to find them. Make sure you're also running the latest xDrip+ nightly version.

**Comment by NovaProspekt7** [comment]
I've just performed a factory reset and it looks like it did the trick, though it chose Tomato as the, instead of LimiTTer. This is on the latest nightly version.

Hope it helps anyone else who has this issue

**Comment by laois80** [comment]
Tried all that. I dont really want to factory reset my phone, it has too much to lose. Sent from Samsung Mobile on O2
-------- Original message --------From: JamOrHam <notifications@github.com> Date: 26/09/2019  23:47  (GMT+00:00) To: NightscoutFoundation/xDrip <xDrip@noreply.github.com> Cc: laois80 <lmmurphy1980@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [NightscoutFoundation/xDrip] Xdrip+ cant connect with Limitter. Android 9.0 (#1033) Have you tried playing around with the Use Scanning and Trust Auto-Connect advanced bluetooth settings in xDrip settings? Use the search to find them. Make sure you're also running the latest xDrip+ nightly version.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU5A3O42CAKD6NOOPTLQLU3ZFA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7XFR6A#issuecomment-535714040",
"url": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU5A3O42CAKD6NOOPTLQLU3ZFA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7XFR6A#issuecomment-535714040",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by NovaProspekt7** [comment]
You can always backup your files through your phone or on your pc/laptop
Google some guides, there are some easy ones out there how to backup your data for a factory reset

Good luck 😊

**Comment by laois80** [comment]
Thank you!Sent from Samsung Mobile on O2
-------- Original message --------From: NovaProspekt7 <notifications@github.com> Date: 27/09/2019  15:49  (GMT+00:00) To: NightscoutFoundation/xDrip <xDrip@noreply.github.com> Cc: laois80 <lmmurphy1980@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [NightscoutFoundation/xDrip] Xdrip+ cant connect with Limitter. Android 9.0 (#1033) You can always backup your files through your phone or on your pc/laptop

Google some guides, there are some easy ones out there how to backup your data for a factory reset

Good luck 😊



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU6UMYYGLBOQQH5FWNDQLYMPZA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7ZERXY#issuecomment-535972063",

"url": "https://github.com/NightscoutFoundation/xDrip/issues/1033?email_source=notifications\u0026email_token=AL5OTU6UMYYGLBOQQH5FWNDQLYMPZA5CNFSM4I2XFT2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7ZERXY#issuecomment-535972063",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Navid200** [comment]
@NovaProspekt7 Would you please close this issue as it seems it was resolved?
Thanks
