### ISSUE TITLE
Nightscout URL should support tokens

### ISSUE THREAD

**Issue by thecubic** [NightscoutFoundation/xDrip#1035]
xDrip supports nightscout uploading & following in the form:

`https://API_SECRET@my.nightscout.place/api/v1`

This username is not used for HTTP basic auth, it's used as the auth token:

https://github.com/NightscoutFoundation/xDrip/blob/f96119cf4a7911e4fef62bc510a45481ba7467d2/app/src/main/java/com/eveningoutpost/dexdrip/cgm/nsfollow/utils/NightscoutUrl.java#L83

Since `API_SECRET` is too secret (and hard to revoke or principle-of-least-privilege), I initially attempted to use the token as a username instead of the `API_SECRET`, and it was rejected by `cgm-remote-monitor`

It would be neat if URLs would support token access

**Comment by zetric** [comment]
I agree.

In my eyes it's a general topic with http basic auth in nightscout. This is still not supported, so your medical data is visible to the public (API key or token do not protect the dashboard).

But as there is the possibility to place a reverse proxy in front of nightscout with a .htaccess file, it would help if xDrip would also support this kind of authentication. For sure there must be also changes in nightscout as http basic auth conflicts with the bearer token.

Another approach would be to use just the token for securing the whole frontend. But that is something that has to be addressed to the nightscout platform team.

**Comment by dabear** [comment]
Have you guys tested with the Newest cgm-remote-monitor release? There are some changes related to auth token and secrets there. Maybe it now works. Worth a try

**Comment by zetric** [comment]
Absolutely. Especially as I was trying with the docker image of nightscout before where I don't know what exactly is inside.
But unfortunately there is no difference with the nightscout current master branch on bare Ubuntu.
And I am afraid my NodeJS language skills are to poor (near zero) to be able to contribute something here what would be my first approach in general.

So this will be my wish to the nightscout devs for the next year: Add real security 😃.

Happy new year to you guys! 🎆

**Comment by zetric** [comment]
Wow...now I can also sync with nightscout if I replace the api_key with the token in xDrip. I thought I tested this...
And It would be interesting how this works. In the dev console of the webbrowser I see a custom header field "apikey" for the API_KEY scenario that is not used when I access the page via token (that is sent as POST parameter).
And I can also not see what xDrip does with a packet sniffer in Android because xDrip does something that I highly appreciate: It checks the SSL trust anchor. Most other appt still don't do this. Well done!

But well... it worksw and that's the most important thing!

So imho this issue can be closed.

**Comment by guydavies** [comment]
Does this really work?  I've tried with a user-specific token with the Nightscout URL in all the potential positions...

https://<token>@<appname>.herokuapp.com/api/v1/
https://<appname>.herokuapp.com/?token=<token>/api/v1/
https://<appname>.herokuapp.com/api/v1/?token=<token>/

None of those worked for me.  I'm using the latest version of Nightscout master branch and the latest nightly of Xdrip+.  Any pointers would be welcome because I've been pondering the desirability (or not) of having the actual API key in another app.

**Comment by zetric** [comment]
I use it not on heroku but in Docker on a self-maintained rootserver.
So the path to the API might be different. But normally it should work like this:

Webbrowser: https://<your-subdomain>.herokuapp.com/?token=<your-default-API_SECRET-or-manually-created-token>
xDrip: https://<your-token>@<your-subdomain>.herokuapp.com/api/v1/

**Comment by guydavies** [comment]
Thanks for the tip. It never occurred to me that this would be interpreted. 

So I tried what your Xdrip option says and it kept erroring for me. I guess I'll stick with what's working for now. 😁

**Comment by Navid200** [comment]
@thecubic Can we close this issue as it seems there is a working solution?
Thanks

**Comment by thecubic** [comment]
I haven't used xDrip in quite a while, so I can't confirm that the issue is resolved.  Anyone that can verify that is free to close the issue

**Comment by tolot27** [comment]
We should really verify if it is supported know and document it.

**Comment by Navid200** [comment]
So, someone can open an issue and then the xDrip team will take the task to find answers even if the person who opened the issue is no longer able to contribute to the investigation?
I didn't know we had the manpower.  All along, I was under the impression I was closing issues because we had too many open issues and not enough resources and manpower to act on every single one of them.

**Comment by ChaseCarHG** [comment]
This issue is confirmed resolved: 
Inside xDrip+, I successfully used a custom Access Token (created from the Admin Tools menu) before the @ symbol in my REST API URL. I don't seem to have access to update the issue though.

**Comment by 15characterlimi** [comment]
@ChaseCarHG can you confirm what roles you have configured for the access token that you're giving to xDrip+?

I personally have set up an access token with the role:

     devicestatus-upload

for user "xdrip", but it's not working. Concretely, when I put the corresponding access token "[xdrip-some long hexadecimal number]" into the REST API URL in the xDrip settings, I get the error message
   "Unable to do REST API Upload: Unauthorized url: https://xdrip-[hexadecimal number]@[hostname].herokuapp.com/ap/v1/ marking record: failed"

instead of the stuff in [....], obviously I'm using my real access token and hostname.

If I replace the [xdrip-some long hexadecimal number]" thing with my API_SECRET, it works.

Since it works for you, I wonder what I'm doing wrong. Is "devicestatus-upload" perhaps not the right / sufficient role for xDrip+?

Note: I've also tried to set up access token for "readable" access for my Smartwatch, but that doesn't seem to work, either.

**Comment by 15characterlimi** [comment]
Upon further observation, it seems to *sometimes* work, but fail often enough that I keep getting notifications from xDrip+ when it hasn't succeed uploading something in long enough? The issue might not be with Nightscout; I'll report back later if I have more info.

**Comment by tolot27** [comment]
`devicestatus-upload` is not the right role. It allows only the upload of the status of a device, i. e. battery status. You have to create a new role which includes at least the following permissions: `api:treatments:*`, `api:entries:*` and `api:devicestatus:*`. You can also limit these permissions further to not allow deletions, for instance. But this may affect the removal of wrongly created treatments.

**Comment by 15characterlimi** [comment]
@tolot27 thanks a lot! That fixed it.

**Comment by tolot27** [comment]
@15characterlimi Please can you post the most secure but functional permissions here and brief guideline how to setup this?

It would be a great contribution and good addition to our best practice guidelines and hopefully, @Navid200 can add it to the wiki.

**Comment by 15characterlimi** [comment]
> @15characterlimi Please can you post the most secure but functional permissions here and brief guideline how to setup this?

Sure, I can write up what I did, but it wasn't anything magic, I just followed your suggestion on the permissions (thanks!).

Here's what I did, in case it helps:

1. Follow https://nightscout.github.io/nightscout/security/#how-to-turn-off-unauthorized-access on how to lock down access to one's instance (on the Heroku dashboard for one's instance, go to Settings > Reveal Config Vars > add the config var with key "AUTH_DEFAULT_ROLES" and value "denied").
2. Follow https://nightscout.github.io/nightscout/security/#create-authentication-tokens-for-users to create a new authentication on one's Heroku instance, ie. go to https://[APP_NAME].herokuapp.com/admin/ (instead of [APP_NAME], put the app name you picked in https://nightscout.github.io/nightscout/new_user/ under step 4 f) (referred to in the text as "Cloud site name" immediately before). Then click "Add new Role":
   - name: device-readwrite
   - permissions: api:devicestatus:* api:entries:* api:treatments:*
   - click 'Save'
3. Click "Add new Subject" and enter:
   - name (for example): xdrip
   - Roles: device-readwrite
   - click 'Save'
   - note down the Access Token for xdrip (it will start with "xdrip-", followed by a long hexadecimal number i.e. digits 0-9 and a-f).
4. Open the xDrip+ Android app, click on Hamburger menu (three horizontal lines) > Settings > Cloud Upload > Nightscout Sync (REST-API).
    - Set Enabled to ON
    - Optionally, tick "Use mobile data"
    - For 'Base URL', enter: https://[ACCESS_TOKEN]@[APP_NAME].herokuapp.com/api/v1/ 
      - Instead of literally writing "[ACCESS_TOKEN]", write the token string ("xdrip-" followed by the long hexadecimal number) from the end of step 3.
      - Instead of literally writing [APP_NAME], write your app name, which is part of the URL in your browser on the page that you're doing this on.
      - Note that the URL you're entering will not contain the characters [ ], these are just placeholders above to tell you which parts to replace with your access token and app name.
      - Further note that you do not need to enter your API_SECRET anywhere. Your API_SECRET is yours, don't give it to an app. Instead, give apps access tokens, whose permissions you can manage and done above, and can revoke.
      - Further note, the role 'devicestatus-upload' that comes with Nightscout is not sufficient; I believe it's sufficient for uploading glucose readings, but not sufficient for uploading treatments or for editing/deleting stuff, and that causes xDrip to often report errors. It's possible that more restrictive permissions than the ones listed above for device-readwrite might also work, but these ones have been tested and work.

**Comment by tolot27** [comment]
@15characterlimi Many thanks for this detailed description. @Navid200 Would you add this to the wiki, please? We may have to emphasize what the advantage is over the current connection settings: privacy.

**Comment by Navid200** [comment]
This entire page explains how a token can be created:  
https://navid200.github.io/xDrip/docs/Nightscout/Tokens.html  

And the description of how a token can be used by a follower is included in this page:   https://navid200.github.io/xDrip/docs/Follow/FollowNightscout.html
