### ISSUE TITLE
Miaomiao + Libre Checksum Failed, sensor works with LibreLink

### ISSUE THREAD

**Issue by SpeedoPasanen** [NightscoutFoundation/xDrip#1040]
After replacing sensor 2 days ago, I've managed to get only a few readings after restarting everything, then I just get "Error: Checksum Failed". I can scan with LibreLink normally and it shows a normal graph and is in normal range of fingertip tests.

Tomato app shows a history like 6.4 6.4 0.0 -2.0 0.0 6.4 0.0 0.0 (MMOL/L) and also stops working after the first impossible value like 0.0 with "read below normal value, sensor may be broken".

Wondering if my sensor is mostly working but sometimes sends these impossible values, and LibreLink can overcome this by skipping them?

Could use-at-your-own-risk-options be added for ignoring impossible values and skipping checksum tests?

Also, would the "allow testing with dead sensor" option already do that? I cannot enable it even though I have enabled Engineering Mode. The checkbox is still grayed out. How to try it out?

Still 12 days left of sensor and I'm sure I can't get a warranty replacement as it works with the official app so a work-around would be great!

**Comment by tzachi-dar** [comment]
Are you in the us?

בתאריך יום ד׳, 2 באוק׳ 2019, 10:49, מאת Toni ‏<notifications@github.com>:

**Comment by SpeedoPasanen** [comment]
@tzachi-dar no sorry forgot to mention. EU 14 day Libre1

**Comment by SpeedoPasanen** [comment]
Got a Miaomiao 2 today and problems disappeared. Maybe it's more fault-tolerant than mm1 or maybe I broke the mm1 while charging it on monday, which would be weird. Will have to test the mm1 one more time with the next sensor.

**Comment by androckz** [comment]
Hi all.
I'm experiencing the same issue depicted by @SpeedoPasanen.

My setup is:
- Freestyle Libre 1 sensor (Italy, not US)
- MiaoMiao 1 (firmare v. 36, then updated to v. 39)
- xdrip (last nightly, but it happens also with v. 2020.07.13)
- Honor View 10 phone (Android 10)
- Fossil Gen 5 smartwatch (Wear OS 2). Watch is collector only when phone is out of range.

Here a detailed list of what I did, step by step:
- put new sensor on my arm
- started it 24h later, first with Libre reader, then with LibreLink app
- after 1h, LibreLink app said 4-5 times that "Reading not available, retry after 10 minutes" (or something similar, don't remember the exact words). This error message happens again couple of times a day (quite strange, because usually I notice it only the first couple of hours)
- xdrip: stop sensor
- put MiaoMiao in charge, wait until green led light, put MiaoMiao over sensor
- in the meanwhile LibreLink app started scanning via NFC with no problems
- xdrip: start sensor. Waited a lot of time for the initial calibration, so I took a look to bluetooth collector status and logs: a lot of "**Checksum failed - retrying**" errors
- xdrip connection status: "Connected"
- tried to move MiaoMiao over sensor, to find a better placement: no way. 
- **sometimes (10 times a day more or less) there is a correct reading coming to xdrip from MiaoMiao with no checksum errors**
- no errors scanning with xdrip via NFC, so I was able to perform the initial calibration
- tried to clear bluetooth cache several times: same checkum errors
- tried to forget device, associate xdrip to different bluetooth device and then back to MiaoMiao: same checkum errors
- upgraded MiaoMiao firmware to v. 39: same checkum errors
- performed a fresh xdrip install on a Samsung Galaxy Tab A7 (Android 10): **same checkum errors**
- smartwatch: same checksum errors if forced as collector
- **[glimp app](https://play.google.com/store/apps/details?id=it.ct.glicemia&hl=it&gl=US) always get readings from MiaoMiao (no checksum errors)**, both in phone and tablet. I installed this app only to do this test, usually is not installed because I know it is not compatible with xdrip.
- tried to restart sensor life with edropletnfc app: same situation. Checksum errors on bluetooth data, NFC scan with xdrip is OK.

I'd like to try to bypass the checksum, just to see what happens and give more details, but I'm not able to build xdrip project (just posted a message to a different issue thread).

IMHO this specific sensor has something different, but NFC scans with phone are OK and also glimp app can get readings from MiaoMiao. The problem can be repeated on a different device (tablet), so xdrip could be investigated.

I am available to perform all the necessary tests, please let me know.
Thanks a lot!

**Comment by tzachi-dar** [comment]
@MoNsTeR
It seems to me that your problem is in the miaomiao and not a software
issue.

The libre reading changes every minute. So, this should give you
enough time to do the following:

Have the miaomiao read something and in the same time have xDrip read the
same data and compare if you are getting the same data.

You might have to read it a few times to make sure that you have a reading
for the same minute.

I believe that you will see the readings are different.

And last thing. Running without checksum is very dangerous, you might get
invalid readings.
Don't think of doing that in real life.

Thanks
Tzachi

**Comment by tzachi-dar** [comment]
One last thing, I would start by taking down the miaomiao, resetting it and
trying again.

**Comment by androckz** [comment]
> @monster It seems to me that your problem is in the miaomiao and not a software issue. The libre reading changes every minute. So, this should give you enough time to do the following: Have the miaomiao read something and in the same time have xDrip read the same data and compare if you are getting the same data. You might have to read it a few times to make sure that you have a reading for the same minute. I believe that you will see the readings are different. 

Thanks a lot for the answer. Perhaps you're right. It could be that MiaoMiao NFC is "weak" and this sensor is somehow different from others. The strange thing is that Glimp app receives data from MiaoMiao without errors. But Glimp is not open source (I suppose) so we don't know how checksum errors are managed (and IF they are managed). 
As you suggested, I will try to compare the readings and give some feedback.

> And last thing. Running without checksum is very dangerous, you might get invalid readings. Don't think of doing that in real life. Thanks Tzachi

Sure! Only for scientific research :)

**Comment by androckz** [comment]
> One last thing, I would start by taking down the miaomiao, resetting it and trying again.

Already tried, but forgot to mention in my post. I just updated it, thank you.

**Comment by Navid200** [comment]
@SpeedoPasanen Would you please close this issue if it has been resolved?
Thanks

**Comment by SpeedoPasanen** [comment]
Partly still a mystery but may it remain as such. Closing. 😘
