### ISSUE TITLE
how should long acting insuline (Lantus/Levemir/Toujeo) be used in prediction ?

### ISSUE THREAD

**Issue by k2s** [NightscoutFoundation/xDrip#1054]
Already the possibility to distinguish between different types of  insulin that was done in #973 helps with reporting for people using pens.
xDrip does also prediction based on insulin and its pharmacodynamics. 

The prediction is not taking [Lantus](https://github.com/NightscoutFoundation/xDrip/pull/973#issuecomment-536295457) into account after 6 hours, but median for its effectivnes is 10.8 to >24.0 hours and also it has very stable infusion rate for all the time.

What would be the correct way to take long action insulin into account in predictions ?

**Comment by Navid200** [comment]
@k2s You are now a contributor, right?
I hope you don't mind me closing this issue.  We need to organize and prioritize the issues so that you guys (developers) can look and see what needs help without having to comb through hundreds of open issues.
I'm sure you can open a chat room with other developers to get answers if you need to.
If I am misunderstanding the purpose of this issue, please go ahead and reopen.   In that case, I would appreciate an explanation why it is an issue.
Thanks
