### ISSUE TITLE
Dexcom G6 / 8G Sensor:  InvalidRxMessage FF0601

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#1107]
I'm using a Pixel 3a with Android 10 and lateat patch level with xDrip Nov 22nd nightly.

My 8G sensor reported "sensor errors" today. I do not receive values anymore, eventhough the Dexcom receiver does. I can see the InvalidRxMessage entry in the log.

Besides this error I also have the occasionally lost connection problem that others have reported. This is nomally solved by manally unbonding, which does not help in this case.

![Screenshot_20191129-141220~2](https://user-images.githubusercontent.com/39347827/69872397-9536d280-12b5-11ea-81d5-cfe5a12ffc2b.png)

![Screenshot_20191129-141245](https://user-images.githubusercontent.com/39347827/69872254-340eff00-12b5-11ea-96fa-9b3464c93bb2.png)

**Comment by nsghub** [comment]
While I was writing the post, the phone reconnected to the transmitter and received values. The error message stopped showing up.

**Comment by nsghub** [comment]
The message appears approximately after one day. A reboot with additional unbonding fixes the issue.

**Comment by bobsbbq** [comment]
Curious when you say unbonding, are you referring to using the forget device? Does this just break the transmitter connection and you have to enter it back? Does the sensor session stop or does it keep going?

**Comment by nsghub** [comment]
Yes, I mean the "Forget device" button. But this is the same as directly removing the device from the paired devices list in android. The button caption is a bit misleading.
The sensor is not stopped!

**Comment by wouterla** [comment]
I've been having the same issue:
- An initial reading is  fine
- Sometimes this works, even up to a day long, with data received every five minutes as expected
- Often, it will stop working, and I'll only get it working again after a 'forget device' and 'restart collector'

I've had this problem with both a 81xxx and 8Gxxx transmitter, with two different sensors.
Only the 8Gxxx transmitter seems to be giving the InvalidRxMessage FF0601 message, though, so that might not be the main reason this is happening.

I added a 'reset_bond' call in the SCAN section of automate (plus set the msSince to 7 minutes) to try and see if I could, ahem, automate my manual actions for the time being. That seems to ensure me getting readings every 10 minutes. But is obviously not a structural solution.

Maybe the G6 also needs a 'force unbond' setting like the old collector for the G5 had?

Additional data point: I'm using a OnePlus 7 Pro, and there might be a correlation between this starting and the latest update (to 10.0.2.GM21BA) of OxygenOS / Android 10.

**Comment by nsghub** [comment]
After a nightly from december the issue is gone. It only happend right after an update again, but fixed itself after another reading.
