### ISSUE TITLE
Basal Insulin in XDrip

### ISSUE THREAD

**Issue by korkats** [NightscoutFoundation/xDrip#1117]
Hi All
Been using XDrip for a while now with a Miaomiao 2 on Oneplus 6 and have to say its changed my life

Well done developers...

Question, is there a way of adding Basal Night insulin in as at the moment its only Bolus

Fiasp bolus

Tresiba basal

**Comment by zetric** [comment]
Yea, that would be cool. My father also would appreciate that.
Cause a at the moment he sometimes adds two bolus treatments (that is one basal and one bolus) that result in an unrealistic effect time curve.

**Comment by korkats** [comment]
I don't think this exists yet. It can be done on Spike on iPhone.

**Comment by steve8x8** [comment]
I'd like to second this feature request - still have to log my basals (given with pen) separately (using a foreign app, then process their csv and upload to NS API).

**Comment by korkats** [comment]
It just seems a bit ridiculous that an app as good a xdrip cannot cope with bolus and basal. 
Surely someone out there must have a workaround that is relatively simple to grasp. 

Hey out there , What does everyone else do?? (I'm using libre and miaomiao )

**Comment by jamorham** [comment]
Try installing the latest nightly and enable the `Multiple Insulins` preference option which is within the `Predictive Simulation Settings` - Due to a bug in the current version you may need to reboot your phone before this actually takes effect but then you can specify basal insulin as a treatment type if that is what you are looking for. I wouldn't advise trying to include injected basal insulin in to the prediction model via the option as there is no model for this.

**Comment by korkats** [comment]
Fantastic, that's nearly what we are looking.. I'm actually on tresiba 48 hour basal which is not on the list yet, but hey I will try with lantus. 
I added lantus but it squews the profile.

**Comment by Kustomwireless** [comment]
Has anyone checked out how they do it in Glimp it has been in there for a few years and seems to work well.

**Comment by steve8x8** [comment]
I've been using Glimp for a while, and also adopted their scheme. IIRC there's the insulin value, a notes entry (which contains "Bolus" or "Basal"), and a treatment type that's "None" for Basal.
I'm on the train now, but my Contour2Nightscout repo has a script that creates a valid json...

**Comment by vnniyB** [comment]
I've been using the `Multiple Insulins` it works well for input but to throws off the insulin on board graph.
Would be great to have different line graphs per insulin type.
I don't have any experience with apps but I'm a responsible python programmer, any tips on getting started contributing to this project I would love to help

**Comment by tolot27** [comment]
It is related to #1153.

**Comment by flummoxedca** [comment]
I am probably doing something incorrectly but I am wondering if a basal injectiion should be shown in NS ? I'm reallty not sure if I am entering my basal injection (basaglar) correctly. In the morning I dose with Basaglar & novorapid but only the novorapid appears in Nitecout. I cuurently add a note so that I have a record of the injection.

**Comment by Navid200** [comment]
There have been lots of updates since this issue was opened.
Would you please update if this is still missing?

**Comment by Navid200** [comment]
@korkats 
There seems to be a strong overlap with #1153.
I hope you don't mind me closing this.  But, if you disagree, we can reopen it.
Thanks
