### ISSUE TITLE
Feature Request: Deleting Dexcom queue entries

### ISSUE THREAD

**Issue by winni67** [NightscoutFoundation/xDrip#1118]
Hello,

sometimes, there are queued entries like „stop sensor“ or „calibrate ...“ in the queue to the Dexcom transmitter (G6 or G5) and it would be nice and helpful, if these entries could be deleted.

Thanks in advance.

Kind regards.

**Comment by Dainem21** [comment]
Hello,

this would be nice. I had the situation, that one transmitter run out of battery. I had to stop it in xDrip, but since it was no longer responding "Stop Sensor" stuck in the queue.

Best regards

**Comment by skyphyr** [comment]
Agreed, when the transmitter ID changes, these should be automatically cleared as it otherwise will send these instructions to an unrelated transmitter, which could cause issues. Trying to work around this now, same situation as Dianem.

**Comment by Navid200** [comment]
That would be very useful.

**Comment by Navid200** [comment]
Problem Scenario, which will benefit from implementing this issue (1118):

1- Transmitter dies completely on a working system.  This is not just a decrease in the battery voltage.  Rather, the complete shut down such that a Bluetooth scanner will show no sign of the transmitter serial number Bluetooth signal.

2- Since the system was operational, there is no "Start sensor" option in the xDrip menu.  In order to be able to start the sensor on the next transmitter, the user taps on "stop sensor".  Therefore, xDrip attempts to stop sensor on the current (dead) transmitter.  However, since it never receives an acknowledgement from that transmitter, the "stop sensor" command remains in the queue.

3- Since there is a command stuck in the queue, xDrip never establishes communication with the new transmitter.

How would you resolve this problem without the means to clear the queue?

**Comment by Navid200** [comment]
The capability now exists for clearing the Dexcom transmitter que:

Tap on the treatment menu (syringe symbol on the main screen).
Long press on the microphone symbol at the bottom right corner.
In the form that opens, enter the following without the quotes.
"clear transmitter queue"

**Comment by dhermanns** [comment]
Great thx! Pretty hard to get aware of this for other users. Maybe you could make this easier notable for users in the future?

**Comment by Navid200** [comment]
We are working on documentation.  It's not there yet.  But, we plan to improve it.

**Comment by Navid200** [comment]
https://navid200.github.io/xDrip/docs/Clear-queue.html
