### ISSUE TITLE
Follow multiple Dexcom G6s?

### ISSUE THREAD

**Issue by DrSolarMOTA** [NightscoutFoundation/xDrip#1126]
I have a situation where I have three kids and each wears a Dexcom G6.  Each child has their own Android device, is collecting its own data through XDrip+, and uploading to their individual Nightscout websites.  
Is there a way to use XDrip+ to follow all three data feeds simultaneously on my Android phone?
Thanks,
Greg

**Comment by nshtg** [comment]
I don't know about XDrip but could use the Dexcom Share (through XDrip) and the official Dexcom Follow app to achieve this.

**Comment by whoiswes** [comment]
@DrSolarMOTA - I'm in a similar situation.  Both my son and I wear G6s and have phones running xDrip, uploading to separate Nightscouts, etc.

My phone runs xDrip for me, and then I used an app call [AppCloner](https://appcloner.app/) to clone the APK and install it as a follower.  Works fine.

I don't know if you can run multiple app instances as followers because of how xDrip uses google cloud messaging is used for sync - the pro version of AppCloner has an override for that which may be the ticket.

We've been running this way for a few years and it's worked great.

Pixel 2, Android 10 for my phone, Nexus 5X, Lineage 15.1 for his, FYI.

**Comment by DrSolarMOTA** [comment]
@nshtg - Yes, you are correct that Dexcom Follow would be a way to go to see multiple reading at once, but the options for multiple alerts, widgets, and notifications that are available in XDrip are far superior and now that I've been using them, I find them irreplaceable.  But thank you for the backup plan!

@whoiswes - Thank you for responding.  I'll give a look at AppCloner.  I was under the impression that XDrip was just pulling the data directly from the Nightscout API - ie. no Google involvement.  Regardless, this might work well.  I'll give this method a try.

Thanks!!

**Comment by whoiswes** [comment]
@DrSolarMOTA - good point - if you just sync off Nightscout then there should be no issues. I have my phone as a follower so that I can enter treatments, etc directly through xDrip (which syncs to the master, then uploads to Nightscout), so that's the direction I was coming from.

**Comment by jamorham** [comment]
I would suggest using one of the xDrip variants. This is what we do here. Pro-tip change the flair colors to something different so you can tell them apart on your phone!

https://github.com/NightscoutFoundation/xDrip/issues/267#issuecomment-371077145

**Comment by DrSolarMOTA** [comment]
@jamorham - Thank you!!  I knew that I couldn't be the first person in this situation and that there had to be a workaround already in place.
