### ISSUE TITLE
Wear OS watchface ambient mode brightness

### ISSUE THREAD

**Issue by felixsanz** [NightscoutFoundation/xDrip#1137]
Can someone add a selector for brightness on the ambient mode? It's so bright that i can't even sleep with that flashlight lol

I would do myself but i don't know where to start and this seems like an easy task for any experienced out there

EDIT: Or... since ambient mode has a setting for "low color" (everything white), can that color be configurable? Defauling to #FFFFFF, this way i can set it like #888888, resulting in less brightness

**Comment by felixsanz** [comment]
and please, what is "Circle WF" in settings? i can't find any documentation and i'm curious

**Comment by felixsanz** [comment]
I'm trying on my own, but i'm stuck here and need some help please.

Changes: https://github.com/NightscoutFoundation/xDrip/commit/121616b792b1e956f13e8ba3085b39abc96c34ca

This 10 options that i've added should change low bit mode to this colors:

```
1: #1A1A1A
2: #333333
3: #4D4D4D
4: #666666
5: #808080
6: #999999
7: #B3B3B3
8: #CCCCCC
9: #E6E6E6
10: #FFFFFF
```

But i don't know how to implement it or if it's even possible. Where in the code is the white color set?

All i found is this:

```
        if(lowResMode ^ isLowRes(watchMode)){ //if there was a change in lowResMode
            lowResMode = isLowRes(watchMode);
            setColor();
        } else if (! sharedPrefs.getBoolean("dark", true)){
            //in bright mode: different colours if active:
            setColor();
        }
```

So... it's just `setColor()`. I don't know where white is set

**Comment by felixsanz** [comment]
@jamorham You implemented low bit mode right? Can you give me a hand please?

**Comment by felixsanz** [comment]
can someone give a hand please?

**Comment by felixsanz** [comment]
this is pretty sad actually :(

**Comment by Navid200** [comment]
@felixsanz Would you please close this issue if your question has been answered.
If not, you can sue the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by felixsanz** [comment]
Did you even read anything here? Obviously it has not been answered. I tried to contributed and no one gave any help, i just felt ignored. So no, it's not answered and i'm not going to close it. Close it unanswered if you want.

**Comment by Navid200** [comment]
It could have been answered somewhere else.  I have no idea if you have asked the same questions somewhere else or not.  Hence, the question.

No one is paid here to answer your questions or anyone else's.  

What do you mean by "It's so bright that i can't even sleep with that flashlight lol"?
Can't you lower the brightness level of your phone?

**Comment by felixsanz** [comment]
brightness of my phone? did you read the title of the issue?

**Comment by Navid200** [comment]
Please use the support channels to find out if the user community may have any suggestions.
What do others who use the same device do?
Many of the developers frequent those also.

If all the users are facing the same issue, please reopen the issue.

Thanks

**Comment by felixsanz** [comment]
don't worry i left the contribute idea more than a year ago. not worth here.

**Comment by felixsanz** [comment]
closing issues just for the sake of closing is not solving anything. but if you're happy with it.... i guess that's your work now, clean issues and hide them since no one care :)

**Comment by Navid200** [comment]
There is absolutely no way I personally can answer your question.

There are only a few developers.  They are very busy.  They are volunteers.  We are closing many issues that have been opened just for asking questions.
We are asking people to cooperate with us to coordinate the issues so that we can prioritize.

We ask people to consult with other users before opening an issue.   

Many of us have been using xDrip for years.   We don't want it to stop.  But, overwhelming the developers with 1000 open issues, most of which are redundant questions, is not the way forward.  
We are labeling the issues, closing the redundant issues, pointing the users to documentations etc.

I just asked you to consult with users and let me know what you find out.
You don't have to.
You can reopen the issue if you like as I mentioned already.

**Comment by tolot27** [comment]
> closing issues just for the sake of closing is not solving anything. but if you're happy with it.... i guess that's your work now, clean issues and hide them since no one care :)

Navid does not close issues just for the sake of closing, even if it appears at the first look. He screens most of the issues and try to understand what the questions, problems and ideas are. If he find out it is a support question, he redirects the user to the support channels. If he decide it is a feature, he suggest to discuss this at the support channels because there are much more people joined there. For a long time, there were just a few developers here. Recently, I and Navid joined the team at a lower permission level and we started to cleanup, label and categorize the issues. After this has been done, we try to create milestones and hope to get a new base for developers to work on the most important issues first.

I know, you are unsatisfied because you never got an answer. But that is not our responsibility. We are just start learning the code as you do.

Hence, I suggest that you post some more details about your environment as it is [required](https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) for new issues. 

We appreciate your effort in solving this problem by your own. As soon as someone from the dev team finds time to dig into the code/API, you will get a response.
