### ISSUE TITLE
Cannot undo treatments entered via remote device.

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#114]

**Comment by Navid200** [comment]
Has this been addressed, or is it still an issue?

**Comment by tolot27** [comment]
If I remember correctly, it is still an issue. I've started working on this topic as part of PR #1403.

**Comment by tolot27** [comment]
It can be deleted, can't it?

**Comment by Navid200** [comment]
I just set up an xDrip sync follower with xDrip January 16, 2024.

I entered a treatment on the follower, which appeared on the master.
I then deleted the treatment (https://navid200.github.io/xDrip/docs/Delete_Treatment.html) on the follower, and it disappeared on the master.
I am closing this because you can effectively undo by deleting it.
