### ISSUE TITLE
Improvement: define Tresiba in Insulin Profiles

### ISSUE THREAD

**Issue by gruoner** [NightscoutFoundation/xDrip#1153]
@ANDREAPIPPI rised an improvement request in #1080 to define Tresiba in insulin profiles
can someone provide an activity curve for tresiba? maybe we need to implement a new curve in InsulinManager

**Comment by k2s** [comment]
this could help https://www.tresibapro.com/considering-tresiba/product-profile.html

**Comment by gruoner** [comment]
sounds a really interesting insulin..... its curve doesn't really match a linear trapezoid; it seems like a flat one with zero onset-time, peak at the beginning and 42h duration BUT with some kind of efficiency-accumulation after 3 days of (continuous daily) usage....
Such concepts like "efficiency-accumulation" are new to xdrip's prediction logic. Does anyone knows more about this effect (esp. for tresiba but also for other long-term or mid-term profiles)?

**Comment by ANDREAPIPPI** [comment]
Hi gruoner.
Here something confirming the very long lasting of Tresiba:
https://www.ema.europa.eu/en/documents/product-information/tresiba-epar-product-information_it.pdf       ---- look at page 9 curve
This one
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4156782/figure/Fig3/?report=objectonly
comes from here
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4156782/
and gives very interesting information, I think.
Last but not least, this is the official Novo-Nordisk document about Tresica,  the curve is at page 5:
https://www.novo-pi.com/tresiba.pdf
Bye.
Pippo    :-)

**Comment by steve8x8** [comment]
I'm unhappy with that curve that shows insulin activity right at time zero, and is labelled as "steady state", thus not reflecting the effect of a one-time injection.

**Comment by gruoner** [comment]
@steve8x8 that's one of the main effects when taking about "efficiency accumulation" - you would not get a real onset time because when sated with basal insulin any new injection is just for "refreshment".
I'm afraid when we really want predict activity of basal insulin types we have to find a model for that "behaviour"......

**Comment by steve8x8** [comment]
Still we are supposed to handle individual entries and keep them separate. Whether this is a valid approach at all has to be discussed somewhere else (as stacking follows its own rules).
So in the end we need something that reflects a single injection, not a steady state.
Tresiba ist said to take 1-3 days to level and even longer to be removed. So the 1-shot curve should sum up to sth resembling the steady-state one if properly stacked. I guess this would require a total time span of at least two days. Looks like a challenge as xDrip hasn't been created with such long times in mind.

**Comment by br8kpoint** [comment]
+1 I was just put on Tresiba from Lantus and would love to keep tracking this if we can figure this out

**Comment by ulisse31** [comment]
Hello!
I'm in need to add Tresiba as well. Looks like this is blocked/referenced by #1117 and #1200 
I really we can add some traction to this feature.
My personal experience with this insulin is an effective life of ~40h (injected with pen).
thanks!

**Comment by korkats** [comment]
Hi all. 
Did we ever get a work around to add Tresiba to the list. I have been using this for over a year now and I have tried substitution of another Basal (lantus) but it just not right.

**Comment by tolot27** [comment]
You have to wait until #1388 gets merged.

**Comment by ulisse31** [comment]
@tolot27 PR #1388 seems stuck for multiple months so while I understand the technical constrain, I have the feeling that the development of this feature is somehow halted.
I'm not familiar with this developing community and the release cycle of this project: in your opinion, what would be the best way to understand the status of this issue/PR, its traction, and how to gather additional feedback on it?
thank you in advance

**Comment by korkats** [comment]
Many users now use Tresiba and have found it very successful. As a dedicated user of xdrip+ i would like to understand if there is anything I could do to help with the development/feedback to help with its release. I feel that many many users would benefit from the update. On 16 Feb 2021 09:51, ulisse31 <notifications@github.com> wrote:
@tolot27 PR #1388 seems stuck for multiple months so while I understand the technical constrain, I have the feeling that the development of this feature is somehow halted.
I'm not familiar with this developing community and the release cycle of this project: in your opinion, what would be the best way to understand the status of this issue/PR, its traction, and how to gather additional feedback on it?
thank you in advance

**Comment by ANDREAPIPPI** [comment]
Hi
Just to understand:
What are the reasons why Tresiba basal nsulin and other types of insulin additions are currently blocked?
No time for developers?
Insecurity about the usefulness of this option?
Something else?
It's been over a year since these discussions started and I think it's time to wrap them up somehow.
My opinion, of course.
Andrea

**Comment by ulisse31** [comment]
If I understand correctly the chain of PRs and issues, xDrip math logic doesn't properly account the event when insulin effects stack on top of each others, adding their cumulative effect to the "basal on board" (which is strange to me, as this is done with no issue with other insulins like humalog...?).
I guess the technical blocker is PR #1200 (potentially PR #1117 as well) but ultimately the main issue here is that the development discussion is (probably) ongoing somewhere else (or not at all)...?
I wish I could help in any way.

**Comment by Navid200** [comment]
@gruoner It seems k2s addressed your request.

We are closing the issues that have been addressed so that we end up with only open issues that are identifying bugs or feature requests that have no work-arounds.
The main objective is to reduce the number of open issues so that you guys (the developers) can look at the open issues, without having to comb through hundreds of questions, and find out reasonably fast what issue needs your attention.
I hope you agree with that move.

Can we close this issue please?

Thanks

**Comment by gruoner** [comment]
@Navid200 no you can't - its not implemented the way we disussed (i can't find any PR rised by @k2s solving this improvement request).... i'm not sure if we will implement it in future.
u can close it for cleanup reasons but then u will loose all the information tied with that and u will loose the "feature request point" for such a new kind of profile

**Comment by korkats** [comment]
I would like to think that someone could resolve the issue before closing. It has been requested a number of times, without anything moving forward. With Tresiba now becoming very popular with us Diabetics, surely someone can resolve this. On 14 Mar 2021 11:40, gruoner ***@***.***> wrote:
@Navid200 no you can't - its not implemented the way we disussed (i can't find any PR rised by @k2s solving this improvement request).... i'm not sure if we will implement it in future.
u can close it for cleanup reasons but then u will loose all the information tied with that and u will loose the "feature request point" for such a new kind of profile

**Comment by Navid200** [comment]
No, I must have misunderstood. 
I read the first post (I always do) and the only request in it sounded to me for a request for someone to provide an activity curve for tresiba, which the second post did already.

If a developer creates a pull request for a feature that has no open issues, do you think that the pull request cannot be found by someone searching, and we need to open an issue and keep it open until the pull request is merged?

Do you think that every time a new insulin, or a new concentration of an existing insulin or a combination of two existing ones, comes to market, we will need to open an issue so that the new insulin is added?

We should be able to create a simple chart showing all the available insulins in the market versus the ones currently supported by xDrip, no?  

I have never suggested that xDrip was perfect.  The only thing I have said is the following.

xDrip is free and offers so much that many people keep using it.
Please let's help the developers by not opening issues one after another.  Please help me organize the open issues so that they make sense.  Please help me close the duplicate issues.  If there is already an open issue and you just want something else added to it, please add a post to the existing issue.  Please don't open a new one.
With hundreds of open issues, the really critical ones don't get the attention they deserve because they get buried.

I will not close this issue as you have requested.  When I close an issue, I always communicate with the individual that they  can reopen it, which is a fact.

Thanks for your understanding and support.

**Comment by Navid200** [comment]
I am closing this issue because we have consolidated all insulin requests: #1898
You can continue the conversation here in this issue about this particular request.

Please don't post in the consolidated table issue. Please either use this issue or [Discussions](https://github.com/Navid200/xDrip/discussions) for any conversations.

**Comment by Navid200** [comment]
It has been added.

**Comment by korkats** [comment]
Awesome

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
