### ISSUE TITLE
Suggestions request MiaoMiao OOPAlgorithm

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#1170]
Note 10+ with android 9
MiaoMiao 1 with last firmware 39 (just updated it)
OOPAlgorithm version downloaded from miaomiao site

![Screenshot_20200113-095422_OOPalgorithm](https://user-images.githubusercontent.com/36887391/72233934-87db6a80-360d-11ea-8043-9c8dfc299e24.jpg)

Can you comment with your set up??? I have been having problems of connction, reading accuracy, etc.

**Comment by tzachi-dar** [comment]
Seems like oop does not work with your phone. Can you downgrade the android version.

**Comment by DavidAG2000** [comment]
> Note 10+ with android 9
> MiaoMiao 1 with last firmware 39 (just updated it)
> OOPAlgorithm version downloaded from miaomiao site
> 
> ![Screenshot_20200113-095422_OOPalgorithm](https://user-images.githubusercontent.com/36887391/72233934-87db6a80-360d-11ea-8043-9c8dfc299e24.jpg)
> 
> Can you comment with your set up??? I have been having problems of connction, reading accuracy, etc.

The same thing goes for me. I'm using a Google Pixel 2 XL with Android 10, and a MM2 with the latest firmware as well 😥

**Comment by Navid200** [comment]
If you find this thread because you have a similar issue, please ask the user community before opening an issue.
Currently, we have the following two channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

Only open an issue if you have confirmed there is a bug or if you want to ask for a feature that has no work-around.
Thanks
