### ISSUE TITLE
Watch Wake Up negative value preventing syncing of data when using a watch collector and coming back into range of the phone

### ISSUE THREAD

**Issue by SimonPhilpott** [NightscoutFoundation/xDrip#1175]
The 'Watch Wake Up' field found within the status screen continues to count down past zero when the watch is sued as a primary collector and is out of range of the phone. 

This is preventing the copy of xdrip found on the phone from retrieving data from the watch as it never attempts to reset the Watch wake up back to a 5min countdown. The watch continues to collect readings, but the phone shows as missed reading until you reboot your phone. 
![Screenshot_20191217-123234_xDrip+](https://user-images.githubusercontent.com/6833057/72432497-1a574780-378f-11ea-99fc-8f5e95e1d736.jpg)

**Comment by jamorham** [comment]
I believe this is a symptom rather than a cause. The failover time is reported by the watch so if they stop communicating then this time goes in to the past even though at the watch end it is being reset to each new time interval.

Next time this happens can you try force killing the WearOS app on the phone and re-opening it to see if that is where the stall is?

**Comment by SimonPhilpott** [comment]
Will do, if that turns out to be the cause I'll write something in Tasker to accomplish the same procedure. I could detect the string "Watch Wake Up : -".

**Comment by SimonPhilpott** [comment]
That did indeed fix the issue. I was able to kill the WearOS service in Tasker to accomplish the recommended fix. Factory resetting the watch and Wear OS installed fresh also seemed to stop all occurrences of the above issue.
