### ISSUE TITLE
Samsung S10+/Android 10 BG reading every 15-25 minutes

### ISSUE THREAD

**Issue by billymild** [NightscoutFoundation/xDrip#1185]
I have a Samsung S10+ running Android 10. I have tried all fixes posted in the Facebook group with little change in behavior. My app only gets readings every 15-25 minutes or if I manually restart the collector.

**Comment by jbuckhi** [comment]
Same phone and Android version, but no problems at all! Did you switch off all the Samsung energy saving features (Device Care, Battery, App power management ...)

**Comment by billymild** [comment]
@jbuckhi I followed this post, https://forum.fudiabetes.org/t/upgraded-samsung-and-having-xdrip-issues-fixed/7057 My xdrip worked great for a while then after 1 week of no issues, I changed the battery mode from High Performance to optimized and I had nothing but problems. I tried all the same steps again but I couldn't get it back to how it was. 

What settings are you using?

**Comment by jbuckhi** [comment]
@billymild I did everything mentioned in this post plus/except the following:

o Device care, Battery, Power mode:
   I used "Optimised" from the beginning. Because this is a global switch, changing a whole bunch of settings, it might be best, to change this first, if you want to make a change.
o Device care, Battery, App power management:
   Adaptive battery + Put unused apps to sleep > off
   Sleeping Apps:
   no app should be in there
o Device care, Advanced (three dot menu):
   everything switched off, except Notifications

Hope this helps, otherwise no more ideas.

**Comment by billymild** [comment]
This seems to be tied to wear os devices. I disconnected my 2 WearOS watches and readings are consistent and stable.

**Comment by billymild** [comment]
Disconnecting WearOS devices worked for a day then stopped working.

**Comment by billymild** [comment]
I think I have found a resolution: Downloaded 1-24-2020 Nightly build. For Bluetooth settings only check: Turn Bluetooth on, and Use Background Scans. Everything else should be unchecked.
