### ISSUE TITLE
Dexcom Share Following Password visibility

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1187]
The login password for Dex Share Following is always visible. It should be invisible except the last later during input.

**Comment by Navid200** [comment]
Would you please provide more detail?

What would be the benefit of hiding the password from the person who already has the phone unlocked?

If someone has entered the password and has made a mistake, they will have to re-enter the entire password again if they cannot see it all.   But, how are they going to be sure that it is the password that is wrong if they cannot see it?

**Comment by Navid200** [comment]
@tolot27 What would be the reason for this?
Aren't all passwords visible in xDrip?

**Comment by tolot27** [comment]
It is never a good idea to show passwords. That's the reason why all passwords in all password input fields on all websites (think of your bank app) and most of the desktop and mobile applications are invisible. That has nothing to do with locked or unlocked phones/computers and also not with privacy films.

The Dexcom Share Upload password is also invisible.
We simply have to change https://github.com/NightscoutFoundation/xDrip/blob/38fee03be56da6ce9cbe90e08dbe8e4b651c6edc/app/src/main/res/xml/pref_data_source.xml#L136

Will do this later.

**Comment by Navid200** [comment]
I disagree,

When you talk about something that can be seen on a web site, like you bank account login page, the possibility exists to access it in an internet cafe.  In that case, it would be best to hide the password.

But, we are talking about xDrip, an app that runs on a mobile phone in your pocket or purse.
Furthermore, I don't want my passwords to be hidden in xDrip.  The only time I access a page that shows a password is if something isn't working.  In that case, I go to that page to see the password. 

I would like to close this because I don't believe it will be approved considering the associated PR was rejected for similar reasons I have described.

**Comment by Navid200** [comment]
I am closing this because the associated PR was not merged.
There is no reason to hide a password in xDrip unless it is on a page that the user is likely to post in a forum when asking for help.
