### ISSUE TITLE
Libre2 sensor changes

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1210]
Two minor problems I encountered when I changed my Libre2 sensor:

- xDrip (20191122 if that matters) FCs when the new sensor is detected by LibreLink (patched)
- xDrip never sends a "Sensor Change" treatment record to Nightscout (although the new sensor is listed in System Status)

Both can be mitigated, the first by restarting the app, the second by extracting the start date from LL data and uploading a corresponding JSON record, but it's a minor nuisance every two weeks...

**Comment by steve8x8** [comment]
The first bullet point may have an explanation - the settings allow xDrip to fail if it detects a sensor ID change. Is the second item related (i.e., the change isn't reported due to xDrip restarting)?

**Comment by yosepito** [comment]
For the sensor ID change, I think you could simply disable the setting "check libre serial" in settings-->less common settings. This should fix the issue of ID changes included in your first bulletpoint

**Comment by fookatchu** [comment]
There are currently faulty libre 2 sensors in the wild. I received an email which explains that the alarms (bluetooth) are not working, but scanning (nfc) is not affected. Since the patched app gets it's data via bluetooth, no data is send to xdrip. This at least is my assumption. I have one of these sensors running right now. I suppose this is somehow related. I only received a german mail from Abbott, but anyone affected should have received that too. If not, here are the affected Lot-numbers:

[https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png](https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png)

**Comment by steve8x8** [comment]
@yosepito done that - still I'm lacking sensor changes reported to NS. (I have a way to extract the last sensor serials from LL's database and upload them, but it's kind of a nuisance.)
Also, recently xDrip does no longer remember previous sensors (the "Sensors:" list in System Status > Libre2 is empty; only the current one s shown as "Libre2 Sensor:"). Running latest nightly.

**Comment by Navid200** [comment]
@steve8x8 Are you still having problems with xDrip?
Have you asked in the Gitter room to see what other may be doing in a similar situation?

**Comment by Navid200** [comment]
Thanks for the questions, and suggestions.
Please ask other users to find out what every other user does.
After that, if you believe a feature would help, you can reopen and change this to a feature request.
