### ISSUE TITLE
WearOS graph Plugin Glucose?

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#1224]
On the phone:
xDrip  - Menu - Less Common Settings - Advanced Calibration

Calibration Plugin: Datricsae
Use Plugin Glucose : ON

The readings on WearOS watch doesn't match with the phone, I assume that is not using Plugin Glucose. Is that right?

![1](https://user-images.githubusercontent.com/608650/73729898-c4424800-472d-11ea-8060-b0957b180f2d.PNG)

**Comment by parapenT1sta** [comment]
I received feedback that Plugin Glucose is not sent to Nightscout. But I didn't check it yet.

**Comment by sweetafro** [comment]
@parapenT1sta I experienced similar problems with Jan 29 build. Had upgraded to the G6 (8H series) transmitter and sensor. Upgrade appeared to go fine. After phone got readings, I switched it to my watch as collector (Force Wear Collection). Eventually my phone's xDrip Home screen display showed that it was not receiving data (old reading/number with line through it). However, my Zenwatch2 was still receiving data AND the xDrip status page showed watch regularly receiving data. It just wasn't displaying on the xdrip home screen. This had been working fine with a G5 transmitter/sensor. If I switched to phone as collector, the readings were fine and it sent them to my watch but the arrows didn't match. Unfortunately, I did not capture screen shots or logs. (Not for this issue: I have since uninstalled xdrip, cleared all the cache, factory reset my phone, re-installed latest nightly xdrip and am now having problems with xdrip "seeing" my G6 transmitter)

**Comment by idalioreis** [comment]
> I received feedback that Plugin Glucose is not sent to Nightscout. But I didn't check it yet.

![Screenshot_20200204_215152_com android chrome_resize_91](https://user-images.githubusercontent.com/48919798/73799212-35751000-47ad-11ea-97d0-ae013b41a49e.jpg)  ![Screenshot_20200204_215139_com eveningoutpost dexdrip_resize_71](https://user-images.githubusercontent.com/48919798/73799218-37d76a00-47ad-11ea-81c3-4a98186d1d4d.jpg)

**Comment by nsghub** [comment]
I used a similar setup and had the same issue. See #692

**Comment by parapenT1sta** [comment]
@tzachi-dar Old issue.

**Comment by parapenT1sta** [comment]
Another issue related to Plugin: https://github.com/NightscoutFoundation/xDrip/issues/1229

**Comment by Navid200** [comment]
@parapenT1sta 
Is this not related to the following?
https://github.com/NightscoutFoundation/xDrip/pull/595

If yes, would you please post in that issue and request it to be reopened if you still have the problem?

**Comment by parapenT1sta** [comment]
It seems but the ticket is closed and the issue still persists.

**Comment by Navid200** [comment]
@parapenT1sta It doesn't matter that it is closed.
Please post in it and please explain to the person who closed it that you still have the problem.
It can be reopened.

**Comment by parapenT1sta** [comment]
Ok :)
