### ISSUE TITLE
Confused calibration follow up

### ISSUE THREAD

**Issue by oakeley** [NightscoutFoundation/xDrip#1235]
This is a follow-up to #770 
Please provide an option to send an ad hoc calibration to a G6 no matter what the current sensor state.
The G6 when started with a code has a very big signal error (usually 2-4 mmol too high). This can be calibrated back in range but if you get a confused calibration during this process then the sensor will stop giving data. There is (currently) a brief window when you can send a new calibration to fix the confused state but if you miss this the sensor stays crashed. 
By default xDrip turns off the calibration menu item after a few minutes of "confusion".
If there was an emergency way to give a calibration then the sensor could be recovered without having to do a stop/start (wait 2 hours) and then try the calibration sequence again.

Having an emergency calibration option would also resolve issue #1234

**Comment by jamorham** [comment]
If you use the syringe icon and enter a blood test value this should send it to the transmitter as a calibration.

**Comment by ramboozer** [comment]
Having problems with this as well.. Did as you said Jamorham and prompted me to turn on automatic calibrations...and it says it will use that data in 20 minutes to correct calibrations. I was reading...that you can't calibrate when using a G6 in native mode? I am not sure how accurate that information is simply for the fact there is SOOO MUCH information everywhere about it. currently facing the same issue where I calibrated it because my Glucose was WAYYY off then what xDrip was displaying

**Comment by Navid200** [comment]
@oakeley Would you please close this issue if it has been addressed?
If not, would you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
@jamorham I use "Initial calibration" for calibrating.  I have been doing that on 8J and 8Q.  
I have disabled double calibration.  So, it doesn't ask for two calibrations.

Is there anything wrong with calibrating like that using "Initial Calibration"?

**Comment by ramboozer** [comment]
I never found any solution to this myself. after dumping about 300$ in sensors. In my experience or from what I tried. there was 0 work around. I attempted todo the standard Dexcom solutions when fail calibrations occur: waiting 2 hours & retry. No luck at all. No longer can use xDrip because of its flaws with the G6 I encountered

**Comment by Navid200** [comment]
I have been using G6 for more than a year now.  My first two transmitter were 81XXXX.  The next two were 8JXXXX and 8QXXXX.
I have never needed to calibrate on a new sensor.
I do calibrate every time I restart.  I have never used a single G6 sensor for just 10 days.
I have provided detail instructions for doing all that in the facebook group:
https://www.facebook.com/groups/xDripG5

I always use initial calibration for calibrating, after having disabled double calibration.  Again, all the details are provided in the instructions.

**Comment by Navid200** [comment]
Never calibrate when the trend is not flat or at least very close to flat.
https://youtu.be/o6bEJ3wko4g

Disable double calibration.
Use initial calibration to calibrate.  After a restart, you need to wait about 15 minutes for the initial calibration option to appear.  You will get error log messages about the incorrect slope.  But, you will also see a log stating the calibration has been accepted by the transmitter.

Never apply a calibration that results in a correction greater than 20% of the reading.  If you need to make a correction larger than 20% of the reading, you need to calibrate multiple times in smaller steps.  otherwise, you will get the confused calibration error.
