### ISSUE TITLE
Sensor restarts never work - Pixel 4 XL Transmitter 8H

### ISSUE THREAD

**Issue by ThoR294** [NightscoutFoundation/xDrip#1272]
I have been struggling with sensor restarts on my pixel 4 xl.  I usually am able to use my ticwatch pro to restart the sensor, but now I'm not able to.  This has been going on for a while.  Not sure if anyone else has these issues or what to do to fix it.

![Screenshot_20200315-104901](https://user-images.githubusercontent.com/28109677/76703794-b4ae0b80-66aa-11ea-87fd-20d75e29cfe4.png)
![Screenshot_20200315-104856~2](https://user-images.githubusercontent.com/28109677/76703802-b8da2900-66aa-11ea-9627-d8acb002ceb0.png)

**Comment by adanvdo** [comment]
This has been an issue for 81 - 8H transmitters. It was reported first in January in #1199 but there has been no movement on it. It looks like jamorham did discover a new hardware/firmware version and had coded it as not being capable of preemptive restarts on Feb 7th. 

still waiting

**Comment by ThoR294** [comment]
> This has been an issue for 81 - 8H transmitters. It was reported first in January in #1199 but there has been no movement on it. It looks like jamorham did discover a new hardware/firmware version and had coded it as not being capable of preemptive restarts on Feb 7th.
> 
> still waiting

awesome thank you.  That is my exact issue.  Ugh this sucks

**Comment by akarabakhtsyan** [comment]
The only thing that works for me for now is removing transmitter from the sensor by unlatching it from the sides, waiting for 15 minutes, putting back in, and starting the sensor again.

**Comment by ThoR294** [comment]
> The only thing that works for me for now is removing transmitter from the sensor by unlatching it from the sides, waiting for 15 minutes, putting back in, and starting the sensor again.

I can never do that I always break the sensor

**Comment by DeXel55** [comment]
I use iFixit [splunger](https://www.ifixit.com/Store/Tools/Metal-Spudger/IF145-012?o=5). Works everytime.

**Comment by ThoR294** [comment]
> I use iFixit [spudger](https://www.ifixit.com/Store/Tools/Metal-Spudger/IF145-012?o=5). Works everytime.

I just tried it.  I think I got it.  Lol thanks!  This sucks

**Comment by wntrmute2** [comment]
I routinely use 2 old glucose test strips.  Insert one alongside the transmitter near the fatter part and you can feel a click as it releases.  Then slide another one in at the same place on the other side and out it pops.  Simple.

**Comment by Navid200** [comment]
@ThoR294 Would you please close this issue if you are satisfied with the validity of the answers?
You can also use the support channels for similar questions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by ThoR294** [comment]
> @ThoR294 Would you please close this issue if you are satisfied with the validity of the answers?
> You can also use the support channels for similar questions.
> https://www.facebook.com/groups/xDripG5
> https://gitter.im/jamorham/xDrip-plus
> Thanks

Sure!  Is there any development regarding auto restarting on the newer transmitters?

**Comment by adanvdo** [comment]
I don't think this should be closed if the native restart method is broken

**Comment by Navid200** [comment]
I have seen claims that individuals are  working on it for quite some time now.  But, I have no knowledge of the details.
Thanks

**Comment by adanvdo** [comment]
do you think those claims are worth closing this case without confirmation of it being fixed? restarts for me have not worked since 8G. I'm now on 8K and still can't restart and removing the transmitter often results in the sensor breaking and doesn't mean this feature is fixed.

**Comment by Navid200** [comment]
@adanvdo Please define "native restart".

**Comment by adanvdo** [comment]
the feature to restart a g6 sensor natively in the app without depending on any external interactions

**Comment by Navid200** [comment]
We were able to hard reset a G6 transmitter.  But, Dexcom changed the firmware.  We cannot do that with transmitters that have the new firmware (Firefly).  It would be pointless to open an issue here for that because it is not xDrip that does not allow hard reset.

The same thing is true about pre-emptive restart.  We cannot perform pre-emptive restart on a Firefly because Dexcom changed the firmware, not because xDrip has a bug.

The same is true about non-native mode.  We were able to run G6 in non-native mode.  We cannot do that any more with Firefly.  It would be pointless to open an issue for that.  

All of these have been caused by changes to the transmitter.
If we figure out a way to do them again, I am sure the developers will add the capability.  But, keeping open issues for them is not going to expedite the process.  If we ever going to have a solution it has to come from people who are experimenting with devices trying to figure what they can do with them.

These are G6 restart instructions:
https://www.facebook.com/groups/xDripG5/permalink/4504790526261074
It goes into detail showing you how you can easily create a tool from a sensor package.  It shows how easy it is to gently remove the transmitter.

**Comment by adanvdo** [comment]
I appreciate that you guys are going through the cases. Thank you all for the work you are doing. Your link is to a private Facebook group though, and it would be a lot better if you could provide the instructions here in the readme or something. I do not want to create a Facebook account just to read the doc. anything that you can do about that would be appreciated. 
again, thanks for all your work

**Comment by Navid200** [comment]
Discussions, above my pay level (that's not literal as we are all volunteers), are ongoing about documentation.  At this point, I have no permission to add any documentation here.  I would love to.  I will as soon as I am allowed.
