### ISSUE TITLE
xDrip + miaomiao 2 + libre 2 does not connect

### ISSUE THREAD

**Issue by mizunno** [NightscoutFoundation/xDrip#1275]

**Comment by mizunno** [comment]
Hello all!

Sorry for posting and close the issue, miss click.

I have been using xDrip + miaomiao2 + libre 1 some time and works fine. But now, I have libre 2 and xDrip can't connect with this new sensor.

Some thoughts?

Thanks in advance.

**Comment by akadismas** [comment]
> I have been using xDrip + miaomiao2 + libre 1 some time and works fine. But now, I have libre 2 and xDrip can't connect with this new sensor.

Hi, any progress?
I've succeeded to connect xDrip + miaomiao2 + libre2 only with OOP algorithm following [this article](https://medium.com/@miaomiaoreader/how-to-make-libre-us-14-days-sensors-work-with-miaomiao2-on-xdrip-35b431a40940).

**Comment by tzachi-dar** [comment]
xdrip and libre2 only work using the oop.

**Comment by plmarcelo** [comment]
@tzachi-dar Do you know if it only works for miaomiao2. Because I have MM1 and In logs it says that data was read. But doesn't show any data :-(

**Comment by Navid200** [comment]
Please use the support channels before opening an issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment]
There are so many open issues because people have been using the issue platform as if it was a forum.  The result is that, with hundreds of open issues, the developers have a hard time figuring out which issue needs their attention.
I am closing this issue.  I ask you to please use the support channels for consulting with the user community.
Thanks
