### ISSUE TITLE
Can not pair Bluejay to phone

### ISSUE THREAD

**Issue by siblues** [NightscoutFoundation/xDrip#1285]
I am using a Pixel 3XL with Xdrip+ and everything works great and I just received my Bluejay in the mail yesterday after waiting for weeks.I can not get the watch or phone to read anything from the Dexcom.They both are working together fine phone and watch but they never get any readings and the documentation for the watch is really non existent.I really need some help and I don't want to have to send this back and end up purchasing something else.Thanks

**Comment by siblues** [comment]
I still haven't been able to get this to work at all.Everything loaded correctly and the phone and watch are communicating with each other but I have yet to get one reading to show up on the watch?Any help would be greatly appreciated.Thanks

**Comment by nicoleloop** [comment]
Holy...absolutely NO ONE has bothered responding to this person's question, in how many months?! I just received my own blue jay x2 watch 3 days ago, and I cannot find Any documentation on how to use it as a standalone collector either. I think that I'll be about to figure it out (hopefully), but wouldn't it be even more exciting if there was a definitive way to be able to Learn how to do so, rather than just having to wing it and hoping that you won't have just flushed the cost of the watch, should anything go wrong? Just saying... 😉 And this doesn't seem like something that jamorham would usually do, in either case! Is everyone sure that he is doing okay these days? Should we make the effort to find out, rather than just complain about things not working right? I, for one, do care, and I just hope that he is only taking a well-deserved vacation from the rest of us needy folks...always wanting him to magically fix things for us lol... Rather than any Other reason why he seems to have gone MIA these last few months.

**Comment by tolot27** [comment]
The first step is to include the devices (phone, dexcom receiver in use or not, sensor [G4|G5|G6]), you are using as well as the xDrip and Android version into your question/ticket.

Next: Do you get BG values into xDrip without using the BlueJay watch? Do you get the values transfered to the BlueJay watch?

Configuring the watch as a collector is not very compilcated. Got to Settings > Smart Watch Features > BlueJay Watch and enable 'Run Collector'.  If you also use the Dexcom receiver, you have to scroll down at the BlueJay Watch settings, click on BlueJay Advanced Settings and disable 'Run Phone Collector' and enable 'BlueJay uses Phone Slot'. That's it!

**Comment by nicoleloop** [comment]
I have done that, in regards to using the blue jay x2 as a standalone collector. I still have 110 minutes left before I can find out whether or not the blue jay watch will start actually collecting/displaying my bg readings sans my phone! (as I am under the impression that the blue jay x2 will only work with the settings set to the native algorithm, even when using a G5 sensor/transmitter system, such as I am)

**Comment by nicoleloop** [comment]
And...it didn't work. 2 hours passed and it just kept saying that it was still warming up (but it stopped counting down). 
I am too tired to deal with it tonight. So I switched back to the phone as the collector and turned native off.

**Comment by jamorham** [comment]
@nicoleloop you need to be using native mode for it to work. Get a native mode session working with your phone and when you are confident that is okay then enable the BlueJay as collector.

**Comment by nicoleloop** [comment]
I have done that, but I must have done something incorrectly, as it is still using my phone as the collector? But it has accepted the calibrations now, finally, so perhaps it just needs more time to get itself sorted out. 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nicoleloop** [comment]
Actually, it appears to now be pulling sensor readings from both the blue jay watch and the phone simultaneously! Is this even possible? Or am I just not interpreting it correctly?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tolot27** [comment]
> Actually, it appears to now be pulling sensor readings from both the blue jay watch and the phone simultaneously! Is this even possible?

No, that's not possible. If you enable the BlueJay collector, the phone collection is disabled automatically. This can be seen in &#8801; > System Status > G5/G6 Status.

Does it work now, as expected? If yes, please close this issue.

**Comment by Navid200** [comment]
@siblues Would you please post here?
https://gitter.im/jamorham/BlueJay
We are asking the user community to use the support channels to consult with other users before opening an issue.
Thanks
