### ISSUE TITLE
BG reading missed and silent mode

### ISSUE THREAD

**Issue by olegsegal** [NightscoutFoundation/xDrip#1287]
Please do an option to override mode for "BG reading missed" alarm!! 🙏 The very common situation at night is phone on the silent mode, the BG is missed, the glucose is decreasing and you never know about that :'( other alarms have this option, but not this one. 

Please add this option to override silent mode ASAP. And thanks for all your work. God bless you

**Comment by razerrazer** [comment]
Can you give some more information, what phone is it ?

You have to disable all power saving options for your phone, otherwise it will stop working when it's night.

**Comment by olegsegal** [comment]
> Can you give some more information, what phone is it ?
> 
> You have to disable all power saving options for your phone, otherwise it will stop working when it's night.

Any phone: Samsung S7, Samsung S10e, Samsung S7 Edge etc.

The thing isn't about phone losing signal, but about the inability to set an option "override silent mode" for "signal lost" alarm, while other types of alarms have this option.

**Comment by razerrazer** [comment]
Is it working if you keep your phone on charge when your sleep ?

**Comment by razerrazer** [comment]
This is my settings on my oneplus 7 pro. I think it's quite similar to yours.

I have added my settings for the battery optimization below.
1. Fist go to settings --> then click on "Battery"

![image](https://user-images.githubusercontent.com/17000974/81080266-d5e3e900-8ef0-11ea-986e-4e1262185d16.png)

2. Then click on Battery Optimization

![image](https://user-images.githubusercontent.com/17000974/81080637-425ee800-8ef1-11ea-947f-9b1e7c39d5fa.png)

3. Make sure your xdrip App is not Optimized" otherwise click on xdrip and take the option "Don't Optimize"

![image](https://user-images.githubusercontent.com/17000974/81080668-4db21380-8ef1-11ea-91d0-f1186494f2f0.png)

![image](https://user-images.githubusercontent.com/17000974/81081800-ad5cee80-8ef2-11ea-9eff-0c68e6d8153e.png)

4. Click on "Advanced Optimization"

![image](https://user-images.githubusercontent.com/17000974/81080695-53a7f480-8ef1-11ea-89bd-3c8693c80322.png)

Make sure to disable "Sleep standby Optimization setting" otherwise it will kill your xdrip every single night to save you battery instead of life :-D

Hope it helps!

**Comment by olegsegal** [comment]
Thanks for the screenshots, but we're talking about different things here :)

The problem is with the XDrip functionality, which doesn't allow to override silent mode for the "BG reading missing" alerts.

It has nothing to do with power savings.

Other alerts working well in silent mode.

**Comment by Hexonium** [comment]
I have the same issue on my samsung A8 (Android 9), including when the phone is not in silent mode! (in that case the "missed reading" notification pops up, but the phone doesn't vibrate or ring). I've enabled "Override Silent on these alerts" in the "Other alerts" menu but that doesn't change anything... It's kind of annoying because low BS could be missed with this bug.

**Comment by olegsegal** [comment]
> I have the same issue on my samsung A8 (Android 9), including when the phone is not in silent mode! (in that case the "missed reading" notification pops up, but the phone doesn't vibrate or ring). I've enabled "Override Silent on these alerts" in the "Other alerts" menu but that doesn't change anything... It's kind of annoying because low BS could be missed because of this bug.

Just noticed that on my Samsung s7 edge it's the same thing. It doesn't ring even if the phone isn't in the silent mode 😶

**Comment by psonnera** [comment]
Same issue Samsung S10, all alarms work in silent mode and normal mode but not missed readings. Vibration on missed readings luckily works though...

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/1147

**Comment by Navid200** [comment]
This is an issue I would like resolved because it affects many.  It doesn't help opening multiple issues because it may imply that a smaller group are impacted.   Instead, I suggest adding your voices to the existing issue.  
Also having redundant issues open takes attention away from other open issues that also need to be addressed.
So, I am closing this issue.  If you like to add your voice, please post in the linked issue.

Please let me know if you believe I'm making a mistake.
Thanks

**Comment by Navid200** [comment]
Would anyone experiencing this please have a look at this?
https://github.com/NightscoutFoundation/xDrip/issues/193#issuecomment-903731657
Would you please post in that thread if you believe that the problem still exists?
