### ISSUE TITLE
xDrip deleted my database

### ISSUE THREAD

**Issue by JimZam** [NightscoutFoundation/xDrip#1341]
Hello. Tonight xdrip deleted my database. I installed yesterday the last nightly, 3f17d8e, from May the 5th. In Events there is a xdrip-daily Job ran finished at the hour the database was erased, but I have checked all the settings and Backup and Delete older than are unmarked. I have all the data saved in Nightscout, is it possible to recover them? I've enabled Try to download data from Nightscout but no exit so far :-(
Thanks in advance.
Regards

**Comment by JimZam** [comment]
Good morning. Today it did it again. Is there any option I have missed that delete de whole database? Any help, please?
Thank you and regards

**Comment by JimZam** [comment]
Hello. The same problem again. I reinstalled everything and tonight the database has been erased. This is something never happened before, I've been using xdrip+ for years. This is the first time I use it with Libre 2 (before always Dexcom), don't know if this has any relation. Any help will be appreciated.
Kind regards

**Comment by UberQueiroz** [comment]
Same problem here...

**Comment by adanvdo** [comment]
I reported this problem in #1280 but ever since then I have not had the problem. Ive been running the Feb 20th, 2020 nightly this whole time and haven't changed a thing besides enabling the Save Database Daily option.  
The only response I got was from one of the libre devs. @tolot27 . if you check out the post you might be able to get him to take a look. this is obviously a problem

**Comment by tolot27** [comment]
Closing it in favour of #1280.
