### ISSUE TITLE
Miband 4 - Bug Report: Color Artifacts in the BG Graph

### ISSUE THREAD

**Issue by Otter3eso57** [NightscoutFoundation/xDrip#1346]
Hi @bigdigital,
Your Miband 4 integration in xDrip+ works awesome. But I noticed today that there are color artifacts in the BG graph. Please see the attached pictures.
The artifact is between one point of color change were the curve intersects the limit line and the second color change. It looks like only one spline per color is used. But the spline needs to be cut between these points.

Can you have a look at the graph generation?

Thank you very much.

Otto
![red_blue](https://user-images.githubusercontent.com/65522328/82384923-3581de80-9a31-11ea-9bfd-7850461c08d5.jpg)

![blue_red](https://user-images.githubusercontent.com/65522328/82384946-416da080-9a31-11ea-8a9e-79439b015b4f.jpg)

**Comment by bigdigital** [comment]
Hi.
To render graphs on miband, it was used the same library as for the entire xdrip application. This library draws lines as a collection of dots by specific coordinates. In some cases,  due to approximation in the coordinates calculations, the point coordinates can be shifted in one or another direction by one pixel which can lead to such artefacts.  Since this is a separate library bundled in the xdrip core i don't i can change this behaviour.  
Regards,
Artem

**Comment by Otto75so3e** [comment]
Hello @tolot27,
Could you please help me find the developer that could address this issue in the xDrip "graphics library".

**Comment by tolot27** [comment]
@Otto75so3e I've just started triaging the issues. Later on, we will prioritize them and start working on the most important issues.

**Comment by tolot27** [comment]
@Otter3eso57 @bigdigital Is this still an issue or is it fixed over time by some library upgrades?

**Comment by bigdigital** [comment]
No, i think this issue still happening if use a connected lines for bg graph.  For now, I've switched the miband graph to the dots representation instead of the connected lines (like this done for xdrip graph in the application). This makes this bug not so noticeable. Actually, i not sure if this is a chart library issue, or there is something wrong with the chart coordinates filler in the xdrip.

**Comment by Navid200** [comment]
Closing this as currently the plan is to address Mi Band by a different app to be developed by bigdigital as explained here:  https://github.com/NightscoutFoundation/xDrip/pull/1659#issuecomment-979924823.
