### ISSUE TITLE
Tech support?

### ISSUE THREAD

**Issue by Schizm1** [NightscoutFoundation/xDrip#1359]
Thank you Xdrip developers for everything you've created. I've run into a problem which I cannot seem to get an answer for. I've been T1D for 40 years and have kept healthy. The creation of CGM have finally made a portion of my dreams come true. Over the last week, my Dexcom G6 and Xdrip have developed issues completely out of the blue. I have a great job as a firefighter (yes T1D can do it) but rely on my CGM to make my life easier to control. As much as I appreciate this community, I'd be willing to pay decent money to get support ASAP to fix the "issues" between xdrip+ and my Samsung G20+. They have worked together in the past but as of a week ago, just went haywire. I really wish there was "tech support".

**Comment by tolot27** [comment]
@Schizm1 Does it work for you, now? Did you ask in the support channels at facebook or gitter?

**Comment by Navid200** [comment]
The support channels:

https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment]
There have been changes to Android and xDrip since you opened this issue.
The first thing to do is to update to an xDrip release of November 27, 2020 or after.

Then, you need to get the correct xDrip settings.  For that, you can go to the support channels. 
For example, here:  https://www.facebook.com/groups/xDripG5/permalink/4838757582864365

You can always re-open this issue.  But, please try the support channels first.
