### ISSUE TITLE
Timestamp wrong order for syringe value

### ISSUE THREAD

**Issue by sashasochka** [NightscoutFoundation/xDrip#1382]
Look at the screenshots and timestamps. The red dot should be before the first calibrated CGM value, based on timestamp and common sense
<img src="https://user-images.githubusercontent.com/822771/87660118-343a0d00-c767-11ea-94cd-1bdd319f8203.jpg" width="300"/><img src="https://user-images.githubusercontent.com/822771/87660123-369c6700-c767-11ea-9505-698592cf41ab.jpg" width="300"/>

**Comment by Navid200** [comment]
Seems to be related to : #1612

**Comment by tolot27** [comment]
It is explained in https://github.com/NightscoutFoundation/xDrip/issues/1453#issuecomment-734503679 and a duplicate of this issue. I don't think it is related to #1612.

**Comment by tolot27** [comment]
@sashasochka For the future: Please do not put the description into the title.

**Comment by Navid200** [comment]
There is a FUZZER figure (2.5 minutes) that is how much all readings are moved forward in time only for plotting on the graph intentionally.  It is possible that calibrations are not going through the FUZZER.  This could be a bug.

@AdrianLxM, Could that be the case?  Shouldn't the calibrations also experience the FUZZER?

**Comment by Navid200** [comment]
@sashasochka 
Your blood test point, with the timestamp of 1:05 has been shifted on the graph to a later time.
This is intentional.
If this is not done and your glucose is changing, the point on the graph will look to have a significant error due to the delay between blood glucose and interstitial fluid glucose.

This is done only for visual effects.  When you enter a calibration, the value is sent to the transmitter right away with the correct time.

If this makes sense, I would like to close this.

If it does not, please respond.
