### ISSUE TITLE
Contour Next One uploaded readings display offset

### ISSUE THREAD

**Issue by palaslet** [NightscoutFoundation/xDrip#142]
On the image bellow you can see a calibration entry from Contour Next One. It looks like the reading is done about 13:45-13:50, but when pressing it and getting the actual timestamp it says 13:35...
Is this intentional or a bug? If it's intentional; why?

![image](https://user-images.githubusercontent.com/5837762/27793226-7544a1a4-5ffd-11e7-8a59-c2fd5b916ddb.png)

**Comment by jamorham** [comment]
The graph shows sensor glucose which lags behind venous glucose which the meter reads. 

Positioning the point relative to sensor glucose aligns it with the sensor glucose trend line as shown in your screenshot. 

If the blood-test point were moved to the left over the 13:35 X co-ordinate it wouldn't match up as effectively.

It is intentional and not a bug.

**Comment by palaslet** [comment]
Thanks :)
