### ISSUE TITLE
Miband 4 - Bug Report: Screen Brightness

### ISSUE THREAD

**Issue by Otter3eso57** [NightscoutFoundation/xDrip#1427]
My Miband shows this bug with the screen brightness. Night mode in xDrip is off , no other apps that accesses the Miband.

The screen goes dark for the watch face upload (as intended) but after that it stays dark for about 20s to 60s. It seems to switch back to day mode when the next full minute is reached.

I use Samsung A40, xDrip 01.09.2020, Mi Smart Band 4 V1.0.9.48

Are there people with the same problem, any idea what this could be @bigdigital?

**Comment by ANDREAPIPPI** [comment]
Hi. 
I have the same problem on my Xiaomi Note 7, MIUI 11.0.1 (Androis 10), Xdrip 20200725 and Mi Smart Band 4 1.0.9.48.
I see the same nehaviour, with brightness almost OFF for times differently long, but never longer than 1 minute.
Not a big problem, but a bit annoying, anyway.
Bye
Andrea    :-)

**Comment by bigdigital** [comment]
> My Miband shows this bug with the screen brightness. Night mode in xDrip is off , no other apps that accesses the Miband.
> 
> The screen goes dark for the watch face upload (as intended) but after that it stays dark for about 20s to 60s. It seems to switch back to day mode when the next full minute is reached.
> 
> I use Samsung A40, xDrip 01.09.2020, Mi Smart Band 4 V1.0.9.48
> 
> Are there people with the same problem, any idea what this could be @bigdigital?

Is that possible that you had a weak Bluetooth connection when such problem happens? For example, the phone was far from the band or band was under the water? After the watchface uploading, the xdrip has a 7 seconds delay before restoring screen brightness. If your band lose  Bluetooth connection during this time, the brightness wouldn't be restored. In this case the screen brightness would be restored on the next wathface uploading sequence. Regarding the delay, this delay designed to mask watchface uploading process (The band firmware automatically switch on display after the watchface uploading)

**Comment by Otto75so3e** [comment]
Unfortunately I think the connection quality is not the problem. The issue also appears when the devices are directly side by side. Is Xdrip writing some log files that could help you troubleshoot?

**Comment by Otto75so3e** [comment]
Hi bigdigital,
I found something. My observation is that it happens when the phone screen is off. I followed your instruction and uploaded the log.

It is OK when:
- The phone is on the charger
- The screen is on and xDrip is in the foreground
- The screen is on and another app is in the foreground
- The high or low glucose alarm triggers (screen off, but the alarm sounding)

It looks like during the 7-second wait xDrip is send to sleep and needs about 1 minute to wake back up. I have all battery optimization off  as far as possible. Global "Energy Mode=optimized" (best performance), xDrip "Background Activity=allowed", xDrip "Energy Usage=not optimized". When I wake up the phone it seems that the watch screen changes to normal in about a second.

Can you use an alternative method to implement the 7 second delay? In case it uses more battery then only as a workaround option for those that have this problem.

**Comment by bigdigital** [comment]
Indeed, seems that your phone can't "wakeup" in time after the thread was sent to sleep.  I'll try to implement this delay in another way and share a test application again.

**Comment by tolot27** [comment]
@bigdigital Please can you setup a repository and your account for handling issues related to your Mi Band app? Many of them are not related to xDrip itself and cannot adressed by the developers of xDrip.

**Comment by bigdigital** [comment]
Hi, yes, it already exists https://github.com/bigdigital/xDrip/

**Comment by tolot27** [comment]
>Hi, yes, it already exists https://github.com/bigdigital/xDrip/

Great! But this is just a fork repository. It may confuse issue creators if they try to create an issue related to your Mi Band app. Do you have a repository four your app?

**Comment by Otto75so3e** [comment]
You are right, I am confused. The Miband integration is not an additional app. It is part of xDrip like all the other watch integrations that are discussed here. Bigdigital is very active in developing it and addresses the issues here posted. In fact, he already provided me with a fix to test out. I plan to close this issue as soon as this fix is accepted as part of the xDrip nightly build.
If you don't accept certain types of issues here than you need directions in your contributing guidelines that guide users to a dedicated place for the sub modules of xDrip.

**Comment by tolot27** [comment]
@Otto75so3e and @bigdigital Sorry, I mixed something up. You are right regarding to the MiBand integration. It is part of xDrip. I was confused because of the separate download apk. Apologies!

Maybe we should think about integrating CI for certain branches.

BTW: The Samsung Tizen Integration G-Watch App is not part of xDrip.

**Comment by Navid200** [comment]
@Otter3eso57 
Is this still an issue?

**Comment by Otter3eso57** [comment]
@Navid200
Yes still open, since the solution is part of #1659 that is not merged yet.

**Comment by tolot27** [comment]
I'll close this issue because it is solved in the build available at https://bigdigital.home.blog. We are still waiting for @bigdigital to address the requested changes until we can merge #1659.
