### ISSUE TITLE
Bug Report: Inconsistent Arrows in Widget and Notification

### ISSUE THREAD

**Issue by Otter3eso57** [NightscoutFoundation/xDrip#1439]
The trend arrows in the Widget and the Notification are inconsistent. It is dependent on the arrow direction. 45 degree up and down is different than all the other arrows. The screenshot shows two examples.

Tested on Samsung A40 & Samsung S9, Android 10, xDrip 2020.05.05 & 2020.09.04.

![arrows](https://user-images.githubusercontent.com/65522328/93655803-10749b00-fa26-11ea-9327-17cd54049622.png)

Edit: The "Number Wall on Lock Screen" is also affected.

**Comment by AdrianLxM** [comment]
Back in early 2015 I also had a phone that replaced the arrow with the south-east-arrow emoji (:arrow_lower_right: ) and I actually liked that look on xDrip.

**Comment by Otto75so3e** [comment]
I agree the arrows look nice. My key point is that they should have a consistent design.

Thanks to your input I found four place where I think it is defined in xDrip (Constants.java, Dex_Constants.java, 2x BgReading,java:  search for \u2198 in the files ). After more research and copying utf8 emoji in emails to view on android. I found that it is possible to use a variant selector after the arrow to tell android to not use the emoji style arrow but the text style arrow. Could someone try to fix this by adding \uFE0E to the constants.

example: DOWN_45(5,"\u2198", "FortyFiveDown"), => DOWN_45(5,"\u2198\uFE0E", "FortyFiveDown")

![arrows2](https://user-images.githubusercontent.com/65522328/93671141-c7adf800-faa0-11ea-9319-9445efbe676b.png)

**Comment by tolot27** [comment]
@Otto75so3e Thanks for suggesting a solution. Using the variation selector-16 (U+FE0F) is the correct approach. Maybe, we should refactor `BgReading.java` to use `TREND_ARROW_VALUES` from `Dex_Constants.java` and change/overload `TREND_ARROW_VALUES.Symbol()` to add the variation selector-16 per default.

**Comment by Amidamaru** [comment]
hi guys, any update on this? :) would love to have a consistent design of arrows on all my three parts (app, widget, lockscreen)

PS: loving the app 👍

**Comment by technimatic** [comment]
Hi. I've noticed the same bug on Samsung phone. It seems that some of the default XDrip text arrows are not present in default Samsung font set. That's why Xdrip replaces them with graphic ones. The quick SOLUTION is to change the phone's system font. For instance, on Samsung phone, change font from Default to SamsungOne fix the issue (in all places including widget). Hi. I've noticed the same bug on my Samsung phone. It seems that the default text arrows are not present in default Samsung font set. THE SOLUTION is to change the phone's system font. For instance, on Samsung phone, changing font from Default to SamsungOne fix the issue (in all places including widget). To change font on Samsung phone go to tap settings -> tap display -> tap font and screen zoom -> select your choice of font style.

**Comment by technimatic** [comment]
Hi. I've noticed the same bug on my Samsung phone. It seems that some of the default text arrows are not present in default Samsung font set. That's why Xdrip replace missing symbols with their graphical equivalent. THE SOLUTION is to change the phone's system font. For instance, on Samsung phone, changing font from Default to SamsungOne fix the issue (in all places including widget). To change font on Samsung phone go to tap settings -> tap display -> tap font and screen zoom -> select your choice of font style.

**Comment by Amidamaru** [comment]
@technimatic  wow good finding! I tested it and I can confirm that the arrow is "normal" once I change from the default to SamsungOne font. But since I don't like the SamsungOne font :D, I hope there will be another solution for this in near future :)
