### ISSUE TITLE
notification for Dexcom transmitter expiry

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1486]
Similar to #1467 a notification of the Dexcom transmitter expiry would be very helpful like it is provided by the Dexcom receiver four and two weeks before expiry.

**Comment by Navid200** [comment]
> I'm not sure if this is the right place for this, but I just wasted a Dexcom G6 sensor. I replaced the sensor only to find out that I needed to replace the transmitter as well (after 3 months). I would have liked for xDrip to notify me of the transmitter end, just like it notified me the sensor had ended.

You could have followed these instructions to remove the old transmitter from the sensor and place the new transmitter inside the same sensor to avoid wasting a sensor:
https://navid200.github.io/xDrip/docs/Remove-transmitter.html

This issue will be addressed.  But, it is not getting priority because we have bugs that we need to resolve.
I am not saying this is not important.  I am hoping that we can address this soon.

**Comment by zspitz** [comment]
> You could have followed these instructions to remove the old transmitter from the sensor and place the new transmitter inside the same sensor to avoid wasting a sensor:

I tried for a bit. But it was 3 AM, and the sensor was situated rather inconveniently for trying to pry the old transmitter out.

I also could have checked how many days were on the old transmitter before putting in the new one. I'll know for next time.

**Comment by Lupum1001** [comment]
What if we made this part of the "Start Sensor" wizard? We only really care about the remaining transmitter time when we're starting a new sensor, right?

I've been itching to add some transmitter status information to that UI for a few months now.

**Comment by zspitz** [comment]
Perhaps some or all of [this](https://androidaps.readthedocs.io/en/latest/Configuration/xdrip.html#replace-transmitter) could be streamlined into the Start Sensor Wizard.

**Comment by Navid200** [comment]
@Lupum1001 I have done exactly that:  https://github.com/NightscoutFoundation/xDrip/pull/2191

But, that PR needs some clean-up and I have not had time to do it.

**Comment by Lupum1001** [comment]
> @Lupum1001 I have done exactly that: #2191
> 
> But, that PR needs some clean-up and I have not had time to do it.

I'll take a look at it, thanks. 👍

**Comment by Lupum1001** [comment]
![image](https://user-images.githubusercontent.com/52087143/190181778-75bb91f4-85d2-408f-a6a4-6e033a4790d4.png)
So if you start a sensor on the 99th day, will it last the entire length of the sensor, or will it work for 24 hours and then stop?

**Comment by Navid200** [comment]
@Lupum1001 

I'm not 100% sure if it would be a good idea.  But, since the conversation is moving towards a PR rather than this issue, I suggest we continue the conversation here:  https://github.com/NightscoutFoundation/xDrip/discussions/2338

I have answered your question there already.

After questions end and you may like to make advice and suggestions for the PR, we can have those in the PR itself.  

And I appreciate your contributions either way.

**Comment by Lupum1001** [comment]
I believe this issue can be closed; PR #2343 addressed the issue, and it's been working fine as far as I can tell.
https://github.com/NightscoutFoundation/xDrip/pull/2343

**Comment by Navid200** [comment]
I am closing this issue because we now have it covered.

Starting a sensor, as you get close to transmitter end of life, you will get a warning that your transmitter will not work soon providing detail about when.
As long as you use xDrip for starting sensors, you will get the warning.
If you use something else to start sensors, that same device/app is responsible for notifying you.

**Comment by zspitz** [comment]
@Navid200 Thank you. I've already seen the new UI and it's helped me avoid unnecessary sensor switches.

**Comment by Navid200** [comment]
@zspitz When you post on GitHub, you automatically are subscribed to the thread.  So, when anyone posts in that thread, you will get a notification.  You can easily unsubscribe.
My last post was to explain why I was closing this thread.  I was not addressing you in particular.
Every time you post here, everyone else who has posted gets a notification.  Please be mindful of that.  
Thanks
