### ISSUE TITLE
"Samsung Workaround" is set by default for all phones

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1495]
Helping someone, using Dexcom G6, on the facebook group, asked them to go through the Source Wizard.
Her phone was Huawei.  We were both surprised that Samsung Workarounds was set.

I took an Asus phone out of the drawer for a test.  Installed xDrip (October 1, 2020 version) on it.  Ran the Source Wizard.  Chose G6 as the transmitter.
Sure enough, Samsung Workaround was set.

**Comment by tolot27** [comment]
@Navid200 Thanks for your support. It is a general problem that many settings are specific to certain hardware but visible in the settings tab almost all the time. I'd like to address this problem sometime because it is quite confusing to the users. But it requires a lot of recoding of the configuration management.

**Comment by Navid200** [comment]
I have been telling people to uncheck that if their phone is not Samsung.
Is that an incorrect advice?

On a second note, is there any way we can expedite 1118?  Or, is there a work-around for items stuck in the queue?

**Comment by Navid200** [comment]
@tolot27 
I have been telling people to uncheck that if their phone is not Samsung.
Is that an incorrect advice?

On a second note, is there any way we can expedite 1118? Or, is there a work-around for items stuck in the queue?

**Comment by Navid200** [comment]
@tolot27 
I just noticed that you changed the title!
Why?  I opened this issue.  Shouldn't you talk to me before editing it?

**Comment by tolot27** [comment]
> @tolot27
> I have been telling people to uncheck that if their phone is not Samsung.
> Is that an incorrect advice?

It is a correct advice, but doesn't matter much.

Regarding #1118: I'd prefer not mixing issue comments.

**Comment by tolot27** [comment]
@Navid200
> I just noticed that you changed the title!
> Why? I opened this issue. Shouldn't you talk to me before editing it?

Indeed, I could have asked; that would be more polite. I don't want to be impolite but as an issue maintainer I'm free to give issues a more suitable title. That's why I've changed it and turned it into a feature request.

If you are not happy with the new title, please suggest an alternative. You can also contact me at Gitter, privately. That would be a better please to discuss in detail.

**Comment by tolot27** [comment]
> Helping someone, using Dexcom G6, on the facebook group, asked them to go through the Source Wizard.

@Navid200 Please link to the Facebook post. Thx.

**Comment by Navid200** [comment]
> > Helping someone, using Dexcom G6, on the facebook group, asked them to go through the Source Wizard.
> 
> @Navid200 Please link to the Facebook post. Thx.

This is the thread:
https://www.facebook.com/groups/xDripG5/permalink/4527172744022852/

I just read through and realized that I had told her to go through source wizard while she has an active session.  I wonder if that was an incorrect advice.  I wonder if Source Wizard only works properly when run with no sensor running.

**Comment by Navid200** [comment]
> @Navid200
> 
> > I just noticed that you changed the title!
> > Why? I opened this issue. Shouldn't you talk to me before ed You can also contact me at Gitter, privately. That would be a better please to discuss in detail.

**Comment by Navid200** [comment]
> @Navid200
> 
> > I just noticed that you changed the title!
> > Why? I opened this issue. Shouldn't you talk to me before editing it?
> 
> Indeed, I could have asked; that would be more polite. I don't want to be impolite but as an issue maintainer I'm free to give issues a more suitable title. That's why I've changed it and turned it into a feature request.
> 
> If you are not happy with the new title, please suggest an alternative. You can also contact me at Gitter, privately. That would be a better please to discuss in detail.

How can I contact you on Gitter.  I cannot find a way to send a MP!

**Comment by tolot27** [comment]
@Navid200
>How can I contact you on Gitter. I cannot find a way to send a Private Message!

It may not work using the app. I'm duing it in the webbrowser by hovering over a user icon and click on "CHAT PRIVATLY".

**Comment by Navid200** [comment]
> @Navid200
> 
> > How can I contact you on Gitter. I cannot find a way to send a Private Message!
> 
> It may not work using the app. I'm duing it in the webbrowser by hovering over a user icon and click on "CHAT PRIVATLY".

I don't see that option on my Chrome web browser.
![Untitled](https://user-images.githubusercontent.com/51497406/98248653-39ec7600-1f43-11eb-8407-b236fbc2ad63.png)

**Comment by Navid200** [comment]
I see cases on facebook where this setting is set for a device that is not Samsung.  And they experience connectivity issues.
I ask them to uncheck it and the problem is resolved.

I would like the title to reflect that.  Currently, this is set by default.  Considering that statistically speaking, there are less Samsung devices than every other brand phone, the default should be unset rather than set.

**Comment by jamorham** [comment]
The `Buggy Samsung Workaround` feature doesn't engage unless the phone is a samsung (or specifically listed device) and the wakeup jitter is detected to be a problem. The setting `Samsung Workarounds` allows this to happen. The only effect of changing  this setting to off would be to disable the workarounds on a samsung which is likely not a good thing to do.

You can tell if your phone wants to use the workaround in the G5 status page because it will say `Buggy Samsung` -> `Using Workaround` - If you don't see this then it wouldn't try to use it.

As such I don't see any reason to have this option anything other than enabled and the only reason to change would be if Samsung change something else in their framework modifications which cause the workaround to fail which is why the option to disable it is provided.

Please tell me if you think that the workaround is activating on non-samsung phones, but as far as I know that doesn't happen and so any change to the setting on non-samsung seeming to resolve a problem would be a coincidence.

**Comment by Navid200** [comment]
@jamorham Do I understand correctly that the "Samsung Workaround" setting should be always set for all devices?
And, there is an intelligence in the code that only kicks in, to enable Buggy Samsung Workaround, if the device needs the workaround?

But, what happens if the wake up jitter is detected and the Buggy Samsung Workaround is enabled for a non-Samsung device?  Could that never happen?

**Comment by jamorham** [comment]
The code to enable it checks against `Build.MANUFACTURER.toLowerCase().contains("samsung");` so it only does anything on a samsung device. 
The only exception to this is we check against a list of other devices where it is known to work. `alwaysBuggyWakeupModels = Sets.newHashSet("Jelly-Pro", "SmartWatch 3");` 

As far as I know xDrip wont do any samsung workaround unless those conditions are met and so the settings page setting only has the effect of being able to disable the feature on samsung phones which is a bad idea because as far as I know all versions of the samsung framework still have the same issue which the workaround fixes. This is why I say it should be left as enabled.

**Comment by Navid200** [comment]
I now understand the "Samsung Workaround" setting should always be set for all devices.  Then, can we move it to the engineering mode?
I ask the same question for any other setting that you believe should be set or unset for all devices.

I now close this issue.  Thanks for answering.
I will also change my recommended settings, on facebook, to have this set for all devices.
