### ISSUE TITLE
Buttons Silence alarms not working

### ISSUE THREAD

**Issue by Stormyfour20** [NightscoutFoundation/xDrip#1497]
Greetings. I have a Samsung S10 Plus with Android 10. I also have buttons silence alarms selected. This feature doesn't seem to be working and when I get an alarm in the middle of the night it's quite challenging to silence an alarm. It used to work fine on my S7 but not now . Any chance I could get some help with this please? Thanks!

**Comment by tolot27** [comment]
Did you read #73? Does the known limitations answer your question partially?

**Comment by Stormyfour20** [comment]
Thanks for replying. I did read it and I guess I just figured that's since it was from 2017 that it had been resolved. Especially since it worked fine on my S7 but it doesn't seem to work on the S10. What I gathered from that post is that it really is random whether it works or not?

**Comment by tolot27** [comment]
> What I gathered from that post is that it really is random whether it works or not?

No, not random. As @jamorham statet: "I haven't found a reliable way to do this when the phone is locked or outside of the app." Hence, if your phone is unlocked and xDrip in the foreground, it should work.
But as times go on and newer Android releases change a lot of things, it can work but doesn't have to be.

**Comment by Stormyfour20** [comment]
Well I was looking for some help, not a lecture.

**Comment by AdrianLxM** [comment]
@Stormyfour20 the way you could reliably get button presses is by writing an accessibility service.

**Comment by Stormyfour20** [comment]
@AdrianLxM Thanks! I guess I'm looking for a quick fix and I'm frustrated that there is an option to "Buttons silence alarms" and it doesn't work especially since it worked on my S7. I feel like I'm doing something wrong and causing it.

**Comment by AdrianLxM** [comment]
> @AdrianLxM Thanks! I guess I'm looking for a quick fix and I'm frustrated that there is an option to "Buttons silence alarms" and it doesn't work especially since it worked on my S7. I feel like I'm doing something wrong and causing it.

I doubt you are doing something wrong. An app capturing user input is a sensitive thing. Capturing it globally while not being open could open the world to sniffing passwords intended to be input to another app. So Android is restricting it more and more.
As a developer I don't like this restrictions... As a user I fully understand them.

The one good reason of capturing user entry is an assistant service. So that's the way to go. And the user then will get warned (and in newer devices actively have to enable it).

**Comment by Stormyfour20** [comment]
@AdrianLxM Obviously I'm a rookie at this, so I really appreciate you taking the time to explain it to me in a way I can understand. My wife also appreciates it! I'll see if I can sort this out and hopefully it will get resolved. Thank you.

**Comment by Navid200** [comment]
@Stormyfour20 You say you need this when you get an alarm in the middle of the night.
Don't you want to see what the alarm is before snoozing it?
If you unlock the phone to see what the alarm is, you can easily silence it as well.  Would you please explain the scenario?

**Comment by Stormyfour20** [comment]
Thanks for the reply. The goal here is to not wake up my wife. By the time I can get to the "snooze alert" menu 30+ seconds has gone by and now she's awake. On the S7 I had I could silence the alert almost immediately with the power button and everyone but me stays asleep. Yes I want to know the blood sugar value, but I can see that in the kitchen when I get up to treat the low. Thanks for trying to help!

**Comment by Navid200** [comment]
Oh, I see, you silence the alarm right away.  But then, quietly unlock the phone to see what the alert was.  I understand now.

Just in case you don't know, there may be another option, which may be an improvement but not the perfect solution that has been disabled due to the Android 11 ...

There is an ascending volume profile.
You can enable it by going to Settings -> Alarms and Alert -> Glucose Alerts Settings -> Alert Volume Profile

If you choose the ascending volume profile, the alarm starts at very low volume.  Your selected sound file plays at the very low volume.  Then, in 1 minute, the same sound file is played at slightly higher volume.  There will be a 1-minute gap between consecutive execution of the sound file.  The volume goes up once every time the file is played.
If the phone is close to you, I hope that only you will hear it and not your wife the first time it plays.  If you snooze the alarm, it will stop and will not continue the repeat the alarm.

Would that help?

**Comment by Stormyfour20** [comment]
That's a fantastic idea! I'll give it a go and set it up today. 

On a side note, when I posted this a while back I was using Toujeo. I've since switched to Tresiba for long acting. Wow, what a difference. Nighttime lows are almost a thing of the past. That's another way to silence those alarms.

Thank you for trying to help out, I really appreciate it.

**Comment by Navid200** [comment]
You're welcome.
Please update either way (if it works or not).
If you are satisfied, please close the issue or let me know to do it.

**Comment by Stormyfour20** [comment]
I tried it out today and seems like this is an excellent alternative. I'm calling this a fix and closing the issue. Another happy customer! Thanks.
