### ISSUE TITLE
Xdrip+ Problem nach Software Update 01.11.20

### ISSUE THREAD

**Issue by MooGro** [NightscoutFoundation/xDrip#1507]
Hallo ich habe das Samsung S20 und nach dem Software Update ständig die Pairing Anfragen.
Bin schon so ziemlich verzweifelt,  da xdrip+ die einzige app war, mit der ich meinen G6 auslesen konnte. Die Dexcom App lässt sich nämlich auf dem S20 auch nicht mehr installieren. 

Hoffe auf eine schnelle Lösung. Habe wirklich schon alles ausgetestet und gelöscht und wieder neu installiert. Doch keine Behebung des Problems. 

Wer eine Lösung hat, bitte her damit. Kann keine Nacht mehr richtig schlafen. Es kommt alle paar Minuten "Mit DexcomSM koppeln?"
Dies ist eine ganz dringende Bitte an die Entwickler. Bitte findet schnell eine Lösung oder gibt es bereits eine???

**Comment by yumtime** [comment]
I am having the same issue on Pixel 3. Started after I updated to build RP1A.201105.002

I get this error in the log: 
Could not set pairing confirmation due to exception: java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission neither user nor current process has android.permission.BLUETOOTH_PRIVILEGED

I've given Xdrip all the permissions I can but it still does this.

**Comment by tolot27** [comment]
Duplicate of #1494
