### ISSUE TITLE
Feature request: automate 'eating soon', before getting up, using an alarm clock

### ISSUE THREAD

**Issue by petervanrijt** [NightscoutFoundation/xDrip#1513]
Hi all,

Currently our morning routine from getting up to eating currently takes about 30 minutes. It should be great if there would be an alarm clock build in xDrip (for example xDrip > Hamburger menu > 'Rise and shine'). When this functionality is available it's possible to automate 'eating soon' target to switch on 30 minutes before morning alarm clock sounds. Because f that there will be always active insuline to process breakfast.

Best regards,
Peter

**Comment by AdrianLxM** [comment]
This seems to be a looping feature.
What system are you using? 
It seems to be better located there.

AAPS already has this feature built in, e. g.

**Comment by tim2000s** [comment]
There are a number of ways of doing this using IFTTT and Automate in combination with Nightscout for those using looping systems. Instructions can be found in the various system documents. 

You may want to review using  those rather than adding a set of features into xDrip that don't already exist (eg creating temp targets).

**Comment by tolot27** [comment]
That would require catching system alarms which needs extra permissions. I recommend to follow one of the other suggestions.

**Comment by AdrianLxM** [comment]
I'm closing this here. TT are in the responsibility scope of the APS app you are using.
