### ISSUE TITLE
Double prediction graph

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#1565]
Running latest nightly. Problem is I get two prediction graphs, and I don't know which one is right.
![Screenshot_20201220-215504_xDrip+](https://user-images.githubusercontent.com/15315426/102738344-7582aa00-430f-11eb-91e6-f5472076a9d9.jpg)
I think this is a bug.

**Comment by tolot27** [comment]
What do you mean by "two prediction graphs"? The only anomaly I can see is the "jump" in the prediction line.

BTW: You did not answer the most important questions provided by the issue template during issue Hence, we cannot narrow down the problem. Please add the missing information here. Do not create a new issue, but have a look at https://github.com/NightscoutFoundation/xDrip/issues/new?template=bug-report.md to know what information is necessary.

**Comment by doc77** [comment]
Sorry for the missing info.

Version: 2020.11.27
Environment: G6 on Android 9 Samsung Note 8
Expected behavior: a smooth single line depicting prediction. This is just one example, sometimes the two lines overlap time. It is definitely confusing and not normal behavior. I  a long time user and have never seen this behavior.
Actual Behavior: Most often, after adding carbs and bolus insulin at the same time, the double graph appears. It is not a simple skip. The graph in total becomes quite irrational.
Steps to reproduce behavior:  the behavior is reproduced randomly when entering carbs and bolus insulin at the same time.

**Comment by emp-00** [comment]
I have never seen such a behavior (on xDrip+ since 2 years and using predictive simulation from the start). 

Currently still running 2020-11-27 build on Samsung A8. Below a snapshot from my live system - this is how it's supposed to look/work I guess. @doc77 's screenshot shows a break/step in the prediction curve and I agree that's probably a bug or an odd misconfiguration. My settings are: Carb Ratio 10g, Insulin Sensitivity 30 mgdl/U and Carb Absorption 35g/h. @doc77, do you use multiple insulin types? I don't. Also check your "Low level prediction values", I have 100, 3.5, 2 and 0.8 (probably defaults). If this is all good you could revert to the 2020-11-27 and check if this solves your issue. However, I have not noticed any changes of the prediction code recently. Maybe somebody knows?

![image](https://user-images.githubusercontent.com/60714349/102827474-eba41100-43e2-11eb-9930-f1b115ad9bdf.png)

**Comment by tolot27** [comment]
@doc77 Please export your configuration and database for further analyses and post the most relevant settings here. Do the prediction lines "join" after some time?

**Comment by Navid200** [comment]
@doc77 Please respond to the questions tolo27 has asked.
I am closing this for now as you may not be experiencing this issue any longer.
If you are, please answer the questions and we can reopen the issue and work on resolving it.
