### ISSUE TITLE
Kalibrieren Libre 2, patched App, xdrip >= 20

### ISSUE THREAD

**Issue by nicolewerer** [NightscoutFoundation/xDrip#1600]
Welcher Build ist der Letzte, mit dem eine Kalibrierung des Libre 2 in xdrip bei Abweichungen >= 20 möglich war?
Ich brauche diese Möglichkeit dringend und verstehe auch nicht, weshalb es nicht mehr möglich ist.

Mein aktueller Sensor wird in xdrip (Latest APK) zum Beispiel mit 89 angezeigt, blutiger Wert ist 142. Falscher Alarm wird ausgelöst.

**Comment by AdrianLxM** [comment]
This never had been possible. The reason behind it is that the Libre bottoms out at 40mg/dl. If the value goes deeper, it would still show 40mg/dl.
So if you would calibrate it at +45mg/dl e.g. the lowest value it would be able to show is 85mg/dl
Then the user could go hypo - and xDrip would not alarm as it would still have 85mg/dl

**Comment by nicolewerer** [comment]
Ok. Aber früher wurde der Wert doch zumindest in die richtige Trendrichtung angepasst. Heute zeigt mir xdrip einen Wert von 78 mg/dl, blutig ist der Wert 139 mg/dl. 
Bei 78 würde ich essen/trinken, bei 139 nicht.

So ist das auch nicht ungefährlich, weil ich dann irgendwann bei 210 mg/dl bin und glaube bei 155 zu sein...

Warum passt xdrip den Wert nicht mehr tendenziell an den BZ-Wert an? Seit wann ist das so? Ich hatte vorher wirklich nie solche Probleme.

**Comment by MasterPlexus** [comment]
This behavior is set up in that way since the libre2 integration. So I would say, if you don't have the problems before, then the difference was not such big. Maybe this specific sensor has problems for you. Maybe the fibre is not completely set under the skin? Anyway: this behavior will not changed in my eyes by the devs due to the more dangerousity of not recognized low values.

**Comment by tolot27** [comment]
Please ask in the support forums an in Englisch.

**Comment by tolot27** [comment]
> Ok. Aber früher wurde der Wert doch zumindest in die richtige Trendrichtung angepasst. Heute zeigt mir xdrip einen Wert von 78 mg/dl, blutig ist der Wert 139 mg/dl.

As @MasterPlexus already mentioned, there could be a problem with your sensor or the body place you have set it. Some users have even more discrepancies (+100 or even +150 BG higher than Libre value), especially at higher BG values. Other GM systems like Dexcom reject calibrations if the difference is too large - which makes absolutely sense because of potentially malfunction sensor.
