### ISSUE TITLE
add support for insulin Humulin

### ISSUE THREAD

**Issue by youngti548** [NightscoutFoundation/xDrip#1607]
I am a type 2 diabetic currently on glipizide, [Humulin](https://www.humulin.com/insulin-options) 70/30 and when i need it Humulin R.  It would be great if i could add these and see the estimated affects on the xdrip graph.

**Comment by Navid200** [comment]
I am closing this issue because we have consolidated all insulin requests: #1898
You can continue the conversation here in this issue about this particular request.

Please don't post in the consolidated table issue. Please either use this issue or [Discussions](https://github.com/Navid200/xDrip/discussions) for any conversations.
