### ISSUE TITLE
Xdrip disconnects  from ticwatch while I am sleeping

### ISSUE THREAD

**Issue by frankenmk8** [NightscoutFoundation/xDrip#1620]
Hello
I use only ticwatch pro 2020 + miaomiao 2 + xdrip  and every time while I am sleeping after 20 -30 min smartwatch  disconnect! 
all day the smartwatch never disconnects!only when I am in a deep sleep..
Please can you help me ....

**Comment by razerrazer** [comment]
I have the same watch as you.
Please check your settings.

I have added my settings below:

![image](https://user-images.githubusercontent.com/17000974/106107120-cffcfa80-6146-11eb-97cf-a1693554ea3b.png)

And under my watch, i have nothing added under settings.
Ensure that you have unlocked "Enable Collector" since this one is not working as it should.

**Comment by tankrizzo** [comment]
I don't believe there is anything you can do about this at the moment - wearOS disconnects Bluetooth when it thinks the watch goes into "deep sleep" mode. I charge my watch overnight and have it act as main collector - charging does not put the watch into deep sleep mode.

**Comment by Navid200** [comment]
@frankenmk8 Would you please close this issue if you have the answer you were looking for?
You can also use the support channels to get suggestions from other users who may have advice.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
Please use the support channels to find out what other users are doing.
Only open an issue if you can confirm you have identified a bug or if you have a feature request that has no work-around.
