### ISSUE TITLE
New feature: save settings to sd card "Save as"

### ISSUE THREAD

**Issue by SimonPhilpott** [NightscoutFoundation/xDrip#1622]
While it's extremely useful to export and save Xdrip+_settings to the SD card, this really only allows you to save one backup at a time. 

### Describe the solution you'd like
It would be more useful for this feature to either allow you to save as, or save with a date suffix so that you have the option to load settings backups from different time periods or states.

### Additional context
I'm using two different methods of collecting data, Wear OS and from a full android watch bother of which have a number of unique settings applied to get each scenario set up. Equally I've been through periods of time where I'm testing setting up different ways of doing things or show different types of information or test different Carb ratio's / Insulin sensitivity etc. The only way to juggle between 'test' settings and a reliable initial snapshot of my settings is to save to SD card, locate the file from a file explorer copy it elsewhere then move the file back if I want to restore. It's not very elegant.

**Comment by Navid200** [comment]
I agree what you have to do is not very elegant.  But, it works.

There is a request to add more options for the falling threshold of the "BG falling fast" alert.  There are currently only 2 options for the user to choose from.  The suggestion is to add 2 or 3 more options.  Believe it or not, that request has not been implemented yet.  There is not even a non-elegant way to accomplish that objective.  

In the grand scheme of things, this request can wait in my opinion.

**Comment by Navid200** [comment]
@SimonPhilpott This will affect several functions.
When you install xDrip, it detects a previous settings file and ask you if you want to restore it.
If the user uses save as and adds a date suffix, to every saved file, the detector needs to be modified to identify all such files.

The load settings also needs to be modified so that it would allow the user to load files other than the default.

Any user  will be affected even those are are happy with everything as is now.  Now, they will have to deal with approving to load a save file, which they don't currently.

Considering that you can already accomplish what you need:
just rename a saved file as soon as you create it;
when the time comes that you need to load a particular save file, just overwrite the default save file with that specific save file version, I would like to postpone this to when we have addressed more urgent issues.
