### ISSUE TITLE
New feature: Keep the predicted blood glucose curve onscreen and unchanged once an input has been added

### ISSUE THREAD

**Issue by SimonPhilpott** [NightscoutFoundation/xDrip#1623]
When you input an insulin dose or the carbs for food Xdrip shows the predicted blood glucose change based on you inputted Carb ratio, insulin sensitivity and carb absorption rate. 

This initial predictive 'simulation' curve is updated for each data point received from that point onwards. This doesn't give you an easy picture to see where your predictive variables are incorrect. For example, if the eventual spike is higher than predicted this would suggest carb ratio is wrong. A drip in blood glucose before onset would suggest an incorrect carb absorption rate. A spike might be indicative of an incorrectly inputted Insulin sensitivity. 

### Describe the solution you'd like
Keep the initial predictive slope onscreen, perhaps at 50% transparency so you can track the actual slope against the initial prediction for the purposes of review and tweaking. Display a secondary dynamic slope that responds and changes the same as it does currently. The aim would be to tweak all of the predictive simulation values to get a much more accurate initial prediction slope.

**Comment by xannasavin** [comment]
sounds interesting, but maybe this would rather be a nice feature for the Nighscout reports, where you could review several days at once in retrospective rather then just the last day or even last meal. 
However, if you review several days in Nighscout, you will get a better overview on whats happening and where the carb/insulin ration might be wrong.
That "one time" thing you see in xDrip with the prediction line should not be used for assumptions on your treatment plans, since there are many factors that could be interferencing. So only act if the same behaviour pops up over several days (at least 2).

**Comment by vguttmann** [comment]
I would support this Feature Request. I like xDrip, because it gives me a very powerful suite of tools, and I have often thought that this would be useful. 

I do understand your concerns, however, there are also people who do not want their glucose values to be stored on some server.

And lastly, if we'd be making one-datapoint-decisions, we'd have passed out a few times already. Diabetes management always is about noticing a trend and countering it. If I see that I consistently drop before rising, regardless of the meal, I know that my insulin start time might be a bit off, and if #1259 gets implemented, that'd be possible.

Lastly, I do think that there should be a setting to enable this trace in addition to the normal prediction, and not enabled by default.

**Comment by ANDREAPIPPI** [comment]
I support SimonPhilpott's request for new features.
Sometimes I see big changes between the initial predicted blood glucose curve and subsequent curves after the new readings.
To check this, after having entered carbohydrates and insulin units, I enter the expected glycemic values in an Excel sheet, at intervals of about 15 minutes for the next 3 hours.
So after a few readings and corrections of the xDrip + curve, I can see the differences from the predictions, but it's a complicated and inaccurate way.
So I agree with this request, it would be much easier to check the changes to understand if and how to change the carbohydrate / insulin ratio.
Andrea   :-)

**Comment by Navid200** [comment]
@SimonPhilpott Is there an app that does what you are asking?
Perhaps a simulator?

**Comment by Navid200** [comment]
@SimonPhilpott There is already an old issue asking for something similar.
Please add your request, if you feel it's different, to that issue.
https://github.com/NightscoutFoundation/xDrip/issues/464

Thanks
