### ISSUE TITLE
Libre 2 uk

### ISSUE THREAD

**Issue by Mr-Enigma** [NightscoutFoundation/xDrip#1637]
Hiya so I'm one of probably many people getting the libre 2 upgrade soon. I heard it is possible to not have to use miaomiao 2 with the new libre but it seems to be the usa version only? Also I would still need to be able to send the readings for the clinic to review.

Any advice? Thanks

**Comment by tolot27** [comment]
@Mr-Enigma Did you read https://github.com/NightscoutFoundation/xDrip/issues/new/choose? It is important to ask the community support before opening an ISSUE here.

**Comment by Mr-Enigma** [comment]
yes i seen that but since i dont use facebook i thought a good place to ask a question would be the place where the software is.....was there a harm asking a question? seems rude to just assume i have facebook and close it like this

**Comment by tolot27** [comment]
I don't want to be rude; but we have to handle this type of issue so often because either the issue guidelines are not read or the issue templates are ignored. And I did not direct you to Facebook. If you read the link carefully, you would read that you have the choice to either ask the Facebook community OR the Gitter community. Currently, there is no other support possible - unfortunately. How do you understand the sentence "We don't have the resources to answer support questions posted here as tickets."?
The supporters try to narrow down the huge number of issues (currently 830) and filter out support issues and questions. That helps the developers to focus on bugs. You are invited to help us as well.

**Comment by Mr-Enigma** [comment]
> I don't want to be rude; but we have to handle this type of issue so often because either the issue guidelines are not read or the issue templates are ignored. And I did not direct you to Facebook. If you read the link carefully, you would read that you have the choice to either ask the Facebook community OR the Gitter community. Currently, there is no other support possible - unfortunately. How do you understand the sentence "We don't have the resources to answer support questions posted here as tickets."?
> The supporters try to narrow down the huge number of issues (currently 830) and filter out support issues and questions. That helps the developers to focus on bugs. You are invited to help us as well.

i have helped out, i created a very detailed watch tutorial on this hub to help you guys out, at no point did i tell people that replied or asked follow up questions no i wont answer a question posted here go to facebook or "gitter". you guys might be too busy to answer a question but us normal people often do reply here. just need to search libre 2 in this hub to see general questions being answered. i understand you might want to close some open non-issues but what really is the harm asking a question, worst case it doesn't get answered.
