### ISSUE TITLE
Linebreak Broken for TIR values on Statistics Page

### ISSUE THREAD

**Issue by aendes** [NightscoutFoundation/xDrip#1641]
Hello,

maybe this is only in the german translation, but there is a line-break issue with the statistics page:
<img src="https://user-images.githubusercontent.com/35429041/107614497-b67da780-6c4a-11eb-9478-9cfa16795fac.png" width="300"/>

**Comment by Navid200** [comment]
Who could have verified this before approval?  Could the person who did the translation verify this before submitting the translation?

**Comment by tolot27** [comment]
This is a problem in other languages as well:

<img src="https://user-images.githubusercontent.com/1370732/110709996-6835d700-81fd-11eb-9d34-fa324bec3023.png" width="300"/>

**Comment by Navid200** [comment]
Do the translators only deal with words?
They have no way of verifying this themselves, right?

**Comment by Navid200** [comment]
No, I don't even have a Crowdin account.  
I'm just trying to understand who we should ping for this.  
If this happens only for some languages, could it be that when the length of the line becomes too long, the issue occurs, and that's why it doesn't happen in English?
Can I recreate this problem on my phone?

**Comment by tolot27** [comment]
Just switch to Finnish or Russian to recreate it.
