### ISSUE TITLE
Nightscout uploader causes HTTP error 413 - Payload Too Large when sending a large number of entries

### ISSUE THREAD

**Issue by waltersf** [NightscoutFoundation/xDrip#1699]
Nightscout uploader sends bg readings using a JSON array in the request body, but it causes HTTP error 413 (Payload Too Large) when there are a lot of entries. 

A person I was helping faced this problem during a new installation of Nightscout (version 14.2.2). She tried to send all data for more than 2 years, resulting in more than 6000 entries (BgReadings) in Nightscout REST queue.

- Version of xDrip: 202103081944
- Using Libre 1 with MiaoMiao 2, master sending data to Nightscout. 
- Tested in different phones (I exported original data to another phone with same result).

Workaround: I exported xDrip database, extracted SQLite3 database, opened it and deleted all content from table UploaderQueue.  Then, we decided to send only 1 month of data to Nightscout and it worked. I think the problem would happen again if we we try to send all data again.

My suggestion is to send data to Nightscout in smaller batches. 

Best

**Comment by Navid200** [comment]
Would you be willing to do a test and tell us exactly what minimum size would cause the error?
Then, we can add it as a warning to the existing warning (use with care).
![Screenshot_20210417-114020](https://user-images.githubusercontent.com/51497406/115118768-e0b55380-9f72-11eb-804c-bae2be5eea4e.png)

**Comment by Navid200** [comment]
You should respond.  

This is not something that we can fix if we don't know what the problem is.
The existing comment on that page already suggests that you have to be careful meaning if you attempt a very long period, it will fail.

I will be happy to update that warning to clarify how large the data can be before there will be trouble.
In that case, for example, we can say only load data for one year at a time.
Then, you can upload data for 1-year chunks.
But, we need to know when it fails.

I don't see why any developer would spend time on this when it has never caused a problem.

**Comment by Navid200** [comment]
There is already a warning that the user has to use this carefully.  We can add more detail to that warning if we get more info.
But, this doesn't seem to be a show-stopper.
We will address this when more developers join and we have addressed more critical issues.
