### ISSUE TITLE
Local Broadcast of calibation from AAPS aren't  registered in calibation data table or graph.

### ISSUE THREAD

**Issue by capflamme** [NightscoutFoundation/xDrip#1700]
### Your environment
- xDrip 18885dd-2020.12.23
- AAPS 2.8.2 build 194549adc-2021.01.31-15:50
- Hardware data source: Libre 2 and Librelink patched app.
- Issue happens on my OnePlus 6T running OxygenOS 10.3.9 (Android 10), but I doubt it's device specific
- Inter-app settings and auto calibration activated.

### Expected behavior
Broadcasted calibration should always be taken into account, or an error message should be displayed in the log explaining why the calibration was not used.

### Actual behavior
When using the calibation feature of AAPS, I get the toast notification "Calibration sent to Xdrip+" in AAPS and I can see a 'jamorham nsreceiver' event log saying "Processing broadcasted calibation: X.XX offset ms: YY" in Xdrip+ log, but the calibation isn't taken into account as it is not visible in Calibation Data table or Calibation graph. No other event related to the calibation are visible in the log after that.
I tried maybe 20 times and 2 times it worked normaly, but I can't identify why it worked on these 2 specific attempts.

When adding the same calibration directly in Xdrip+, it's always working fine.
I'm always doing calibration when BG is stable for 15min and around 4-7 mmol/l.

### Steps to reproduce the behavior:
For example:
1. Enable Local Broadcast in AAPS: Preferences >NSClient>Advanced Settings> Activate 'Enable Local Broadcasts"
2. Enable Inter-app communication in Xdrip+: Settings>Inter-app settings> Enable below options:
'Broadcast locally'
'Compatible Broadcast'
'Accept Treatments'
'Accept Calibrations'

### Screenshots
<img width="400" src="https://user-images.githubusercontent.com/73880107/115236727-00d44680-a11c-11eb-992d-8e7355d9e0e1.jpg" /><img width="400" src="https://user-images.githubusercontent.com/73880107/115236734-016cdd00-a11c-11eb-8374-0d084090db13.jpg" />

**Comment by Navid200** [comment]
@capflamme 
The data in the calibration graph (and likewise, calibration table) is only meaningful if calibration is done by xDrip.
Is calibration not native (not done by xDrip) in the situation you are describing?

**Comment by capflamme** [comment]
Hello,
The calibration is done by using the calibration button in AAPS. I think it just send the calibration value to Xdrip and then Xdrip is supposed to process it as it was inputed directly in Xdrip.
________________________________

**Comment by Navid200** [comment]
@capflamme 

Calibration is creating an association between the interstitial fluid glucose and blood glucose.
This association is done by a formula.  The entity that is responsible for creating, editing, and maintaining the formula is not always xDrip.

I personally use Dexcom.  The G5 Dexcom transmitter transmits raw values as well as calculated blood glucose values.
xDrip allows the user to choose to use native or non-native mode.  

If the user uses non-native mode, xDrip maintains the formula.  Now, the calibration graph and calibration data table show important information that represent the formula in effect.

But, if the user uses the native mode, it's the Dexcom transmitter that does the calibration.  But, since the transmitter transmits raw values, the xDrip code continues to create a calibration graph.  In this case, the calibration graph is pointless.  It absolutely has nothing to do with the real calibration formula maintained by the transmitter in this case.

I currently use a G6 transmitter.  This G6 transmitter does not transmit raw values.  I have no choice but to use the native mode.  When I look at the calibration table, it is empty.  This is because there are no raw values to use to create a calibration graph.  And it would be useless anyway as the calibration is not done by xDrip.

So, just because a calibration value goes through xDrip does not mean that xDrip is maintaining the formula.

What device is responsible for calibration is your system?

**Comment by capflamme** [comment]
I use Librelink patched app as hardware source. Sensor is therefore freestyle libre 2.
If I input the calibration within Xdrip it's working fine everytime. Calibration is put in table and graph and BG is modified accordingly. When I do it through AAPS, the calibration is only taken into account sometimes, most of the time it isn't. I am not able to understand why it's working sometimes only.
There is definitely something odd/buggy happening here. Maybe something related to the time when the calibration is added relative to the BG update time/frequency. Just a supposition, though.
________________________________

**Comment by Navid200** [comment]
>When I do it through AAPS, the calibration is only taken into account sometimes

Please state how you know that a calibration is, or is not, taken into account.  Please don't base it on whether it appears in the xDrip calibration graph or calibration data table.

**Comment by capflamme** [comment]
As said previously, when I do it in Xdrip, it's always added to the table/graph.
Moreover, I dont really understand how it could be taken into account if not added to the calibration table and graph.
There is no way to calibrate natively FSL2 sensor with librelink, it's not at all like dexcom sensor.
________________________________

**Comment by Navid200** [comment]
@tzachi-dar @keencave 
What is the FSL2 calibration mechanism like?  Is it done by xDrip?

**Comment by capflamme** [comment]
Yes, it's done by Xdrip with fixed slope. Only intercept can be modified within a secure range of around 2mmol/L, I think.
________________________________

**Comment by tzachi-dar** [comment]
I'm afraid I'm not familiar with libre2 calibrations.

**Comment by tolot27** [comment]
We have to investigate why `NSClientReceiver` does not perform the calibration even if it is logged. It would help to see a log from the rare cases; 2 out of 20 as you reported above.

**Comment by tolot27** [comment]
> When you speak about the rare cases, you mean the cases when calibration inputted in AAPS is taken into account in Xdrip?

Yes, I mean exactly what you reported with:

> I tried maybe 20 times and 2 times it worked normaly, but I can't identify why it worked on these 2 specific attempts.

> I would be glad to provide you with logs, but I'm not sure how to get/generate these logs. Can you explain me?

Similar to the logs you provided above. Much better would be an exported xDrip database. It is an SQlite database and you can remove everything except the calibration and usererror table and you can limit the data to a specific time range.

**Comment by Navid200** [comment]
@capflamme Can you provide the data requested by tolot27 please?

**Comment by Navid200** [comment]
We can reopen this as soon as the required data is provided.
Otherwise, for all we know, there is no problem any longer.
