### ISSUE TITLE
Option to force-disable "Samsung Workarounds" (for devices running custom ROM)

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1753]
I've been running xDrip on a Samsung S4mini (LineageOS 16.0) for a while with the patched LL app. No problem so far, even with Samsung Workarounds disabled.

Attempting to use L2/BT, I'm running into issues - which appear to point at these Workarounds being enforced (no matter what the setting is). I suspect that BT handling in LOS differs from that done by Samsung in stock firmware, and that the Workarounds aren't required when running LOS.

Since it's one of the smallest phones with NFC around, I'd like to keep this one for running my Libre sensor, but that would apparently require a change in the code that explicitly disables Samsung Workarounds, ignoring the manufacturer string.
At the moment, when attempting to connect to a sensor already running, I can see the Workaround being enabled after a few seconds, no matter what the setting was (the source code suggests that there's a persistent store that got fed from the past??)

Is there hope for this old but trusty (and virtually indestructible :)) device?

**Comment by Navid200** [comment]
@steve8x8 This is the not the right place for posting a question.
Would you please post in the following and I will work with you to figure out if an issue is needed?  
https://github.com/Navid200/xDrip/discussions

If I attempt to answer your question here, it would give a wrong message to the user community that they can open and issue, here, in order to ask a question.
We can always reopen this issue if needed.
