### ISSUE TITLE
intrusive notification

### ISSUE THREAD

**Issue by tkalfaoglu** [NightscoutFoundation/xDrip#1776]
Hi. On my phone, a Huawei p30 lite, when i am using the phone, every few minutes the graph notification comes down and had to be lifted up to disappear. İs there a way to stop this notification? Many thanks

**Comment by Navid200** [comment]
@tkalfaoglu Have you already asked this question from the user community, which includes all the developers as well?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If yes, would you please provide a link here to the question?
We can reopen this if it is indeed an issue.

**Comment by Navid200** [comment]
This is a link to an existing issue that addressed the same concern:
https://github.com/NightscoutFoundation/xDrip/issues/750

We are hoping to dedicate the issues platform to issues so that the developers can look at them and see what needs attention.

User questions are very important and need to be addressed as well.  However, the expertise needed to address bugs and user questions are not necessarily the same.
We are working on improving documentation.
In the meantime, please help us by posting your questions in the support channels (see above).
If after you post a question, we determine that it is indeed an issue, we will ask you to open an issue or we will ourselves open one to address it.

Thanks
