### ISSUE TITLE
"Multiple types of insulin" not working

### ISSUE THREAD

**Issue by Marcio261** [NightscoutFoundation/xDrip#1801]
Hello there!
What's the xdrip version working on the miband 5, that  the "multiple types of insulin" is working well? 
Im inputing Lantus units, but its working like a bolus input.

**Comment by Navid200** [comment]
@Marcio261 If/when you have a question, please use a support channel:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

Please don't open an issue in order to ask a question.
There are many questions that can be answered by the user community in those support channels.  

The developers monitor those support channels also.  If a question cannot be answered or resolved one way or another, the developers may ask you then to open an issue.  But, until that happens, please don't open an issue by default.
