### ISSUE TITLE
xDrip crash while scanning Libre 1 sensor

### ISSUE THREAD

**Issue by hapvlz** [NightscoutFoundation/xDrip#1809]
Hi Guys,

Phone is: Xiaomi Mi 8 Pro Android 10 QKQ1
xDrip version: e4f7fa3-2021.08.04

Suddenly started that when scanning a sensor it crash the application.
It happens every time when scanning it.

In event logs errors are like -

Error invalid id (time) for bg 23765
Error invalid id (time) for bg 23762
Error invalid id (time) for bg 23762
Error invalid id (time) for bg 23761
Error invalid id (time) for bg 23761

![WhatsApp Image 2021-08-11 at 14 14 59(1)](https://user-images.githubusercontent.com/34927858/129026970-a8bde393-77f2-4796-bc1d-c5f74e7e14c7.jpeg)

**Comment by hapvlz** [comment]
What is the purpose of Github issues page then? 
Gitter require account creation, facebook is not something that I use on daily.

If you wish you can close this issue, but it's something that should be reviewed since it definitely looks like a bug.

**Comment by Navid200** [comment]
@hapvlz I would like the issues platform to be used by the developers to know what item needs their attention.
Interacting with the user community and figuring out how a user can better use the existing capabilities of xDrip is a completely different task, which requires a completely different set of skills.

We only have a limited number of developers.
I don't want them to have to execute both of those tasks because it's not practical.
The user community has a lot of knowledge.  Not every developer knows everything about every single capability of xDrip.  There may be only one or two.  And I don't want those two individuals to have to do anything other than everything else they already have to do.

You, as a user of xDrip, can help us by asking your questions first from the user community.  It may require that you create an account.  If you are not willing to do even that, I don't see how I can ask the developers to spend time to address your request.

**Comment by tolot27** [comment]
@tzachi-dar Isn't this a left over of #1743, is it? The "too much data" looks like it is related.
