### ISSUE TITLE
G6 sensor expiry alert

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1815]
It would be good to have a "your sensory is expiring in 24 hours" alert, or something similar to what the official G6 app does. Thank you

**Comment by tolot27** [comment]
Closing in favor of #1467

**Comment by jamespaulley** [comment]
Wait why have you closed this and then linked to a closed request?

**Comment by tolot27** [comment]
> Wait why have you closed this and then linked to a closed request?

First, this feature request was raised, already and you have not searched for it. Maybe, you have just forgotten that you raised exactly the same issue (#1651) on Feb. 19, 2021? This issue was also closed as a duplicate. It makes no sense at all, having the feature request twice or more times. Hence, I marked this issue also as a duplicate and closed it.
Secondly, you completely ignored the issue template.

The reason why the linked issue is closed is described in the comments. You can always add new comment, if you are not happy with the closing comment. But most importantly, please discuss new ideas first via the communication channels as described in the issue template.
