### ISSUE TITLE
Constantly get Google Play Services error

### ISSUE THREAD

**Issue by maloo1** [NightscoutFoundation/xDrip#1825]
On a phone without google play services the message "com.eveningoutpost.dexdrip.xdrip won't run without Google Play services, which are not supported by your device."

I know I do not have Google play services installed and do not need (or want) the "embedded master - follower" functionality mentioned in the prerequisites.

I would expect the error to only be shown once, and only if I try to enable the above feature.

Alteratively, it would be great if we could just fall back to using a non google play services implantation - like Signal does with GCM...

**Comment by Navid200** [comment]
@maloo1 Thanks for your question.
Please ask questions in the support channels, and we will answer them there.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If it is necessary to open an issue, we will ask you to open an issue.
Thanks for your support.

**Comment by maloo1** [comment]
For anyone finding this in the future this is a duplicate of #1379. Sorry about my poor searching!

**Comment by Navid200** [comment]
@maloo1 Please don't use the issues platform as a forum.  I perfectly understand that you intend to communicate the answer to your question to others who may have the same question.

The problem is that the issues platform has a different purpose.  That is to highlight what issues exist for the developers to focus on.

As long as the user community continues to use the issues platform as a forum in order to communicate with each other and with the developers, people will continue to open issues in order to communicate.

We are asking the users not to do that.  
There are platforms that are meant to be used for the communication purpose, the support channels listed above.

If this is not clear, I am happy to go more into detail.

**Comment by Navid200** [comment]
The more issues are opened, the harder it becomes for anyone to search them.
The best course of action is not to open an issue unless absolutely necessary.
Opening an issue and then posting a link in it to another issue, does not resolve the problem of having yet one more issue added to the list.
