### ISSUE TITLE
Alarm priority on Wear OS 3.0 / Galaxy watch 4

### ISSUE THREAD

**Issue by AlexD97** [NightscoutFoundation/xDrip#1826]
### Subject of the issue
On Wear OS 2.0 xDrip alarms made my watch vibrate intensively 3 times. On Wear OS 3.0 on the Galaxy watch 4 the watch vibrates like for ordinary notifications. The problem is that I may not notice the alarm. 
I don’t know if this is a bug or if it is simply not possible to make high-priority notifications on Wears OS 3.0.

### Your environment
- xDrip version: Nightly build 2nd Sep 2021
- The option to use the Android notification channels is used.

### Expected behavior
An intense vibration when having an alarm.

### Actual behavior
A slight vibration like for every other notification.

**Comment by mk89pwnz** [comment]
Same problem, simple notification is a joke, any way to make it work like alarm?

**Comment by Navid200** [comment]
> 
> I don’t know if this is a bug or if it is simply not possible to make high-priority notifications on Wears OS 3.0.
> 

Please let's not open an issue if we are not sure if it is a bug or not.

Please post in the discussions.  
https://github.com/Navid200/xDrip/discussions

If anyone has anything relevant to post here, they can post it in the discussions as well.
If it turns out that it is an xDrip bug, we can then reopen this issue.
Thanks for bringing this up.
