### ISSUE TITLE
Dex Share follow BG delay

### ISSUE THREAD

**Issue by Bwangster12** [NightscoutFoundation/xDrip#1851]
I just installed xDrip+ on a tablet and my phone in order to follow my daughter's Dexcom G6 app.  I chose the Dex Share Follow option and am finding that very often they readings are delayed to the xDrip apps... On both devices.  I see the status screen shows polling times, and often the BG delay shows 5 or more minutes... Whereas another device Dexcom Follow app or her G6 app already has been updated.

**Comment by Navid200** [comment]
I agree.
It may be a good idea to change the title of 1849.  The title currently is very long and focuses on the solution rather than the problem.
It's easy for someone who is experiencing the same problem to miss 1849 and not find it.

May be we can change the 1849 title to:
Dexcom share follower delay
