### ISSUE TITLE
Missed Readings override silent

### ISSUE THREAD

**Issue by ruenightscout** [NightscoutFoundation/xDrip#193]
Hello, I have missed the missed readings alert a few times recently. I have discovered that if notification volume is on then missed reading alarm sounds but if my phone is on silent it automatically switchs off notification volume so missed reading alert just vibrates.   Is there a setting to make missed reading alert override silent mode? It seems to get its sound from whatever alert sound I have 'Other Alerts' set as but doesn't seem to recognised the override silent mode being ticked in the 'Other Alerts' settings page.  I can't see anything in the missed readings settings for choosing the sound or overriding silent.  It's a good sign that the system has worked well for so long that I haven't needed the missed readings alert! Many thanks, Esther

**Comment by Navid200** [comment]
The missed readings alarm uses the same sound file as the fast rising and fast falling alerts.

There is a claim that on Android 9 and below, the override silent mode also followed the setting of fast  rising and fast falling alerts.
Can anyone confirm that?

**Comment by Navid200** [comment]
@raduiliescu Do you still experience this issue?
What is the version of Android on your phone?

**Comment by kasapis** [comment]
A friend is having the same issue, she has android 10.

**Comment by Navid200** [comment]
If your Android is level 8 or higher, you can use notification channels to accomplish this.

Enable:
Settings -> Alarms and Alerts -> Glucose Alerts Settings -> Notification Channels

Now, you need to trigger the missed readings alert.  To artificially cause that, just change the hardware data source to something non-existent.

After the alert is triggered, use Android settings to go to Settings -> Apps & Notifications -> xDrip+ -> Notifications 
You should see a channel titled: bgMissedAlertChannel.
Tap on the following line (Missed reading Alert).
Now, you can customize your preferences.  You can choose the sound clip, if it should vibrate or not, and if it should override do not disturb or not.

The following may vary by phone.
If you are overriding do not disturb, carefully read the description:
![Screenshot_20210406-151801](https://user-images.githubusercontent.com/51497406/113767033-2ad54400-96ec-11eb-90db-3ff34a8ce64a.png)

So, in the case of the phone shown, "... when Do not disturb is set to Priority only, you need to ensure Android do not disturb is set to Priority only.

**Comment by Navid200** [comment]
I don't believe this is an issue.

In the phone Android settings, please go to:
Settings Apps & notifications -> Notifications -> xDrip+

Make sure "Override Do Not Disturb" is enabled.
![Screenshot_20210823-083843](https://user-images.githubusercontent.com/51497406/130448898-487342cf-2af4-40ee-8593-4aab48ea51d4.png)

If you enable that for an app, in this case, for xDrip, Android will allow the app to handle override silent mode.
Then, enabling override silent mode for the missing signa alert will override silent mode even on Android 11 as I just tested it.

**Comment by Navid200** [comment]
If you experience this issue, please see the post above and follow the instructions.  If it still doesn't work, please post here and we can go over the details.  Please don't open another issue.

**Comment by adamecker** [comment]
@Navid200 I'm pretty confident this issue still exists. I've configured xDrip to override do not disturb mode as you showed above but if the phone's "ring & notification" volume is set to silent or vibrate only then there is still no audible alert (the notification still pops up and is visible without any volume). I believe the intent of this issue was to add a "override phone silent mode" option to the "missed reading alert" configuration page as there's no setting for that alert like there is for some others. I'm using Android 12 on pixel 4 with the notification channels option turned on and a custom sound picked for the missed reading channel.

**Comment by Navid200** [comment]
@adamecker 
xDrip uses two different methods for making sound from alerts.  I have summarized xDrip alerts here: https://github.com/NightscoutFoundation/xDrip/issues/1762

It is a fact that only some alerts use a volume profile.  Hence, they don't care what the volume setting is.  The others don't use a volume profile and they depend on the volume setting.
I am not happy about that.  I wish to change this.

However, that is not the same as missed readings alert not having a override silent mode.  You are making an observation that there is more than one reason for an alert not to make a sound.  I have summarized that here:  https://navid200.github.io/xDrip/docs/Silent-alert.html

There are several alerts that make no sound if the volume is low.  Forecast Low, and persistent high are some examples.

I agree with you that xDrip has more to be fixed/improved.  I disagree to say that this specific issue should still be kept open.

Thanks for your post.  Please let me know what you think about my response.

**Comment by Navid200** [comment]
@adamecker Please read the title of this issue.  It states override silent mode, not the volume.
The missed reading alert has a functioning override silent mode.  Therefore, I disagree with opening this issue because if we do, it suggests something is wrong with override silent mode.
Please do a test:  raise your ring volume to something like 75%.  Then, follow the instructions I have provided to allow override silent mode to work for missed readings alert.  Then, temporarily disable collection and set the missed reading alert to alert when the readings are missed for only 7 minutes.  Now, put your phone in "Do Not Disturb" mode.  
If the alert works, it means that override silent mode is working. 

I agree that the missed reading alert will make no sound if the volume is set to 0.  It's not just that alert suffering from this problem, as I explained already.
We already have an open issue, as I stated already.

If we reopen this issue, should we then open another issue about the Forecast Low alert not making a sound when the ring volume is set to 0?  And should we open another issue for the Persistent High alert not making a sound when the ring volume is set to 0?  And should we open another issue for fast rising alert not making a sound when the ring volume is set to 0?

Why don't you raise the volume on your phone until we fix the volume issue?

**Comment by adamecker** [comment]
@Navid200 ah I see where the confusion is coming from. As a long time Android user I think of silent mode and do not disturb as completely different things. To me silent mode is when you turn volume to vibrate or complete off (silent) and DnD is the toggle that you can turn on via the pull down system settings menu or a schedule.

I'd prefer for the language in xDrip to be consistent. For example the regular glucose alerts can the setting "Override Silent Mode" which does make noise then the volume is set to zero but the override silent mode setting in "other alerts" behaves differently. Maybe that one should be called override do not disturb instead to be clear?

I agree though that we can just use the other issue to track this problem and in the meantime I'll try to keep my volume up at night (it's a long time habit of mine to be in vibrate only mode basically all the time so that's hard to break).

I don't want to be annoying but do you have any guess on how long it will take for this issue to be addressed?  Mostly asking because I have professional Android experience and am really interested in helping out but I don't have a ton of free time right now 😁
