### ISSUE TITLE
Habanero sync problem

### ISSUE THREAD

**Issue by DunePlodder** [NightscoutFoundation/xDrip#197]
Treatments are successfully uploaded to Nightscout from xDrip+ or CGM Care Portal(5.4) on my Pebble.
Treatments entered into Nightscout are not automatically synchronised with xDrip+.
The sync can be "forced" by entering a treatment into xDrip+, then earlier Nightscout entered treatments are downloaded.

**Comment by jamorham** [comment]
Would you mind sending me a private message or email with the URL of your installation so that I can compare whether there is anything unusual about how the treatments look.

**Comment by DunePlodder** [comment]
I sent it through, hopefully you received it?

**Comment by DunePlodder** [comment]
I've also noticed that if I upload a treatment from xDrip+ to Habanero which has a time earlier than the Nightscout entered treatment it doesn't sync that newer treatment.

**Comment by jamorham** [comment]
I am pretty sure this is a bug with Nightscout not correctly handling the Last-Modified-Since header and reporting there is no new data to download. 

As an interim measure I have disabled the use of this field until we work out which NS versions are affected and then can handle it better. Please try the Oct 26th nightly which should resolve the issue.

**Comment by DunePlodder** [comment]
I've done some more testing & the sychronizations work perfectly in all directions, great. Case closed!
