### ISSUE TITLE
OxygenOS 12 C16

### ISSUE THREAD

**Issue by thorinEichenschild007** [NightscoutFoundation/xDrip#2105]
I Updated my OnePlus 8T to OxygenOS 12 C16, and since the Update, the OB1 Collector goes always in Deep Sleep mode, and it's not possible to change something in the Settings.
The App is allowed to be executed in Background, and all Permissions are granted.

The WakeUp Time is very long, Around 5minutes...
Is there a solution which I don't know?

![Screenshot_2022-05-08-16-18-57-84_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/91971937/167300565-1a91d91c-5d1e-4dd3-bb85-b47ee69a52cb.jpg)

**Comment by Navid200** [comment]
Please be so kind to follow the instructions and open a discussion instead of this issue, which I am closing now.

You can open a discussions here:
https://github.com/NightscoutFoundation/xDrip/discussions

This is what we ask everyone to do and we hope that people will eventually stop opening issues by default.

**Comment by thorinEichenschild007** [comment]
I'm sorry, I asked the Nightscout community...
I didn't know about that!
