### ISSUE TITLE
Upload xdrip to nightscout:failed

### ISSUE THREAD

**Issue by angelalex197** [NightscoutFoundation/xDrip#2116]
Unable to do Rest Api Upload: Attempt to invoke virtual method boolean java.long.String.Starts.
with(java.langString) on a null object refference marking record: failed.

**Comment by Navid200** [comment]
Do you mind reporting this in a discussion rather than in an issue?
If it turns out that it is indeed an issue that we have never been aware of, we can turn it into an issue?
This is what everyone currently sees when they attempt to open an issue:
![Screenshot 2022-05-11 081107](https://user-images.githubusercontent.com/51497406/167846825-0dac5fb7-b211-474a-b9a1-1a27cb4d2ec5.png)  
  
  
Here is where you can open a discussion:
https://github.com/NightscoutFoundation/xDrip/discussions
