### ISSUE TITLE
OOP1new and Libre 2 with Sync followers

### ISSUE THREAD

**Issue by psonnera** [NightscoutFoundation/xDrip#2119]
### Subject of the issue
On a non NFC master phone (KingKong Mini 2), when using a Libre 2 EU with OOP1new (fa218ef 2019-11-22) , versions above https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.03.26 do not allow followers to receive data.
Versions above https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.10.13 start showing NFC block errors in master and follower.

### Environment
- Master above 2022.03.26
- Master KingKong Mini 2, NSClient
- Bubble bridge
- All followers (various Android versions from 6 to 12) in Sync follower
- Master using OOP1 enabled

### Expected behavior
Followers should display BG.

### Actual behavior
Libre blocks are received but ignored.

### Screenshots
Screenshots won't add value, what's the best way to share some logs?

**Comment by tzachi-dar** [comment]
As far as I can say, when using OOP1 there was no way to interrupt the block data. So, I'm not surprised that there are errors regarding them.
That said, the BG values that are being sent from the master should be displayed on the follower as well.

If you can connect the follower phone to a pc and run 
adb logcat > file
for about 15 minutes and send this file, that would be great.

**Comment by psonnera** [comment]
Here you go, using May 12th 2022 on both. Logcats at different moments. Follower on a Samsung Galaxy 5 but had same results on other followers with Android 9 and 12.
[master+follower.zip](https://github.com/NightscoutFoundation/xDrip/files/8690735/master%2Bfollower.zip)
.

**Comment by tzachi-dar** [comment]
Strange, the issue seems to happen on the master code.

Please try this version:
https://drive.google.com/file/d/1gf2RAlpbl-YuyfgrQ8-n_zpj8sz-Ogii/view?usp=sharing

Here is the log:

05-13 20:54:27.013  3147  5534 I jamorham graph: Noise: Not enough data to get sensible noise value
05-13 20:54:27.014  3147  3147 D BestGlucose: No noise option slope by minute: -.04732
05-13 20:54:27.014  3147  5534 D BestGlucose: No noise option slope by minute: -.04732
05-13 20:54:27.014  3147  5533 E BgReading: Could not save BGR: 
05-13 20:54:27.014  3147  5533 E BgReading: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
05-13 20:54:27.014  3147  5533 E BgReading: 	at java.util.Collections.sort(Collections.java:204)
05-13 20:54:27.014  3147  5533 E BgReading: 	at java.util.Collections.sort(Collections.java:156)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.NFCReaderX.parseData(NFCReaderX.java:947)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.NFCReaderX.getLibreTrend(NFCReaderX.java:1075)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.utils.LibreTrendUtil.AddLibreblock(LibreTrendUtil.java:188)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.utils.LibreTrendUtil.getData(LibreTrendUtil.java:160)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.utils.LibreTrendUtil.updateLastReading(LibreTrendUtil.java:111)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.models.LibreBlock.UpdateBgVal(LibreBlock.java:213)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.NewDataObserver.newBgReading(NewDataObserver.java:57)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.utilitymodels.BgSendQueue.handleNewBgReading(BgSendQueue.java:147)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.models.BgReading.bgReadingInsertFromInt(BgReading.java:1339)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.LibreAlarmReceiver.CalculateFromDataTransferObject(LibreAlarmReceiver.java:276)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.models.LibreOOPAlgorithm.handleData(LibreOOPAlgorithm.java:288)
05-13 20:54:27.014  3147  5533 E BgReading: 	at com.eveningoutpost.dexdrip.NSEmulatorReceiver$1.run(NSEmulatorReceiver.java:115)
05-13 20:54:27.014  3147  5534 D BestGlucose: dg result: 76 previous: 143
05-13 20:54:27.014  3147  3147 D BestGlucose: dg result: 76 previous: 143
05-13 20:54:27.014  3147  5534 D AlertPlayer: FileBasedNotifications called bgReading.calculated_value = 76.0 calculated value: 76.0

**Comment by psonnera** [comment]
@tzachi-dar working fine! No backfill occured on the follower after first reading so I guess the whole first history blocks wasn't transferred but this is working nicely (follower is https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.05.12).

**Comment by tzachi-dar** [comment]
This should be fixed by: https://github.com/NightscoutFoundation/xDrip/pull/2127
