### ISSUE TITLE
Sometimes when I dismiss an alert notification, the alert is not snoozed.

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#212]
2017.11.01 Nightly

**Comment by jamorham** [comment]
What does the event viewer show at the time the alert was snoozed but didn't snooze?

**Comment by TebbeUbben** [comment]
"Attempt to cancel alert within minimum limit of 3 seconds"

Why is there a limit?

**Comment by jamorham** [comment]
Because some apps with `Notification Access` are, as far as we can determine, programatically cancelling notifications.

See: https://github.com/NightscoutFoundation/xDrip/issues/205

I assume you did cancel the alarm within 3 seconds.  In my tests I found it very difficult to cancel the alarm by hand within 3 seconds which is why the limit is set there as a balance between the maximum of how long an app might take to cancel it and the minimum a human might do.  Bear in mind it can be to do with Android Wear alerts as well so there can be a delay in propagation.

**Comment by TebbeUbben** [comment]
Ah okay, so I now have to be a bit slower ;).

Thanks for your answer, I'll close this issue now.
