### ISSUE TITLE
Wear OS: Ignore DND mode for glucose alerts

### ISSUE THREAD

**Issue by xannasavin** [NightscoutFoundation/xDrip#2223]
### Your environment
- What version of xDrip: 2022.05.26
- What type of hardware data source: Dexcom G6
- Ticwatch Pro 3 GPS, Huawei P30 Pro 

### Expected behavior
I do activate the DND mode at night for my watch. 
The alarms for high or low glucose should vibrate.

### Actual behavior
In the past I solved this issue with the "Feel the wear" app, but since it is outdated it's no more possible to install it on the watch.
The watch is, as said, at night in DND mode, so I don't get disturbed while sleeping.
However, the alarms for high or low glucose are obviously essential.
There should be a way to allow those notifications to bypass the DND mode on the watch.
"Feel the wear" made it also "somehow" possible to ignore DND mode, so there should be a solution.
I can not let my phone do the alarms, since that would wake up others, which I also do not want.

### Steps to reproduce the behavior:
For example:
1. Set watch to DND mode
2. Get low glucose alert
3. don't get notified ><

**Comment by Navid200** [comment]
Hi,

Thanks for your contribution.
We are asking everyone to open discussions instead of issues.  
We will then have to go through the discussions and decide which ones should be converted to issues.  This guarantees that the issues will not become cluttered at any point in time.

When you attempted to open this issue, you must have got these instructions already.
For that reason, I am going to close this issue.
If a developer asked you to open this issue, please clarify.  Otherwise, please open a discussion.

Thanks for your cooperation.
