### ISSUE TITLE
Web Follower not working 

### ISSUE THREAD

**Issue by DieSchatten** [NightscoutFoundation/xDrip#2246]
Hi,

the LLU Web Follower is not working here in Germany for Libre. Seems like Abbott did change the URL at least for German Accounts from api-eu.libreview.io to api-de.libreview.io . Is there a way to change that my self?

**Comment by jamorham** [comment]
Please update to the latest nightly and let me know if that resolves the issue.

**Comment by Navid200** [comment]
Is there any objection in closing this issue?
There is a clear request to not open issues as a first step.  If we don't take it seriously, others will start opening issues instead of discussions.

**Comment by DieSchatten** [comment]
> Please update to the latest nightly and let me know if that resolves the issue.

I did update to the latest nightly from 26th. Did not resolve the issue.

**Comment by jamorham** [comment]
@DieSchatten can you also try toggling the proxy support on/off and see if this does anything as this resets some of the internals. If this doesn't help please can you use the event viewer and submit the logs. Thanks.

**Comment by benceszasz** [comment]
It seems that German server is still not working with Web Follower. I have tried to help someone to use Web Follower with Libre 3, but it wasn't able to pull the data, while LibreLinkUp was working perfectly. Because it seems, that some countries have different servers (https://github.com/timoschlueter/nightscout-librelink-up/blob/main/utils/llu-api-endpoints.js), we have tried it again with a different Libre account pair (uploader and follower) this time we have set the country of the Libre users to Switzerland and it was working perfectly. Maybe there is something wrong or missing in the country / api endpoint mapping?

**Comment by gui-dos** [comment]
You can get the regional server to use for a country code with:
```
https://api.libreview.io/llu/config/country?country=HU
=>
"lslApi":"https://api-eu.libreview.io/
```
```
https://api.libreview.io/llu/config/country?country=DE
=>
"lslApi":"https://api-de.libreview.io/
```
