### ISSUE TITLE
Font size problem xdrip+

### ISSUE THREAD

**Issue by 17gubbar** [NightscoutFoundation/xDrip#246]
Hello and merry xmas. I just got my new phone, and a g5.. Dexcom app dosent work so i go whit xdrip, works great!
Now to the problem, font size on the text on the graph all of a sudden got really big.. It dosent matter if i change the screen size in options to smaller, it's still bigger then before. Saw an old thread about that here earlier.. Any fix to this? Make the text on the graph smaller? I have android 7.1, razer phone. 
![screenshot_20171223-233655](https://user-images.githubusercontent.com/34807314/34325258-2edd878a-e88d-11e7-981d-4865a90b6e80.png)

**Comment by glaucoqs** [comment]
I'm having the same issue with the font size currently.  I don't remember when it was, because I believe it's been like this for over a year.
![Screenshot_2022-08-20-01-12-04-156_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/36828397/185728630-d37cc53e-d57c-464a-ad44-f94d678a7f49.jpg)
