### ISSUE TITLE
xDrip produces incorrect battery data in Nightscout devicestatus uploader JSON object

### ISSUE THREAD

**Issue by dv1** [NightscoutFoundation/xDrip#2501]
The existing code produces a `battery` value like:

    "battery": "50 days (voltage: 285/275)"

This can be found [here](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/NightscoutBatteryDevice.java#L126) and was introduced by commit 92956f73f49dc199e2539ba055ec0d647876b91e .

However, this is wrong. The Nightscout API docs state that `battery` must be an integer.

Because of this type mismatch, AndroidAPS crashes when its NSClient BG source plugin is read. When it reads the `devicestatus` objects, the parser throws an exception when it tries to parse `battery` as an integer. (AndroidAPS source is [here](https://github.com/nightscout/AndroidAPS/blob/dev/plugins/main/src/main/java/info/nightscout/plugins/sync/nsclient/services/NSClientService.kt#L511), and its schema is [here](https://github.com/nightscout/AndroidAPS/blob/dev/core/ns-sdk/src/main/java/info/nightscout/sdk/remotemodel/RemoteDeviceStatus.kt#L54).)

This needs to be fixed to match the expected type.

**Comment by Navid200** [comment]
@dv1 Would you please check the xDrip that uploads to Nightscout.
Please check the following:  

Settings &#8722;> Cloud Upload &#8722;> Nightscout Sync (REST-API) &#8722;> Extra Options  

On that page, do you have Upload OB1G5/G6 transmitter battery enabled?

If yes, would you please disable it?

**Comment by Navid200** [comment]
I'm closing this because you ignored the request not to open an issue.
Please open a discussions and we will take it from there.

**Comment by dv1** [comment]
"request not to open an issue" - what request? And this is clearly an issue, not a discussion. I'll open one regardless, but this makes little sense.

**Comment by Navid200** [comment]
When I have an issue with xDrip, I personally consider it to be an xDrip issue.  But, that is not enough for me to declare that it is.

I will open a discussion.  The developers monitor the discussions the same way they monitor the issues.
Majority of requests are misunderstandings.  If they all first become issues until a developer has time to explain to the user how they should use xDrip, we will always have plenty of open issues, which are really not issues.

You are right that some of these are real issues.
We had to make a compromise.  Our decision was to ask everyone to open discussions first.
We ask many of them to be changes to an issue by asking the user to open one.  

Before we implemented this approach, the number of open issues was approaching 1000.

What I am doing here is wrong too.  The issues platform should not be used for explaining our policies.
But, since you are talking about the issue policy and since it occasionally comes up, I am explaining it here.

I am not starting a conversation.
If you like to respond to this, please be so kind to open a discussion and I will be more than happy to have an open discussions about it there.

**Comment by Navid200** [comment]
When you attempt to open an issue, you will see this:
![Screenshot 2022-11-27 084756](https://user-images.githubusercontent.com/51497406/204138990-f08525ca-faea-4ea4-9c8d-6b23591e7ab6.png)

That's the request from the user community to please not open an issue as a first step.

We want to help the user community.  We didn't have discussions opened in this repository.  But, we do now.

**Comment by paravoid** [comment]
This is very clearly a bug, and a well-reported one at that. I understand that the volume of issues can be problematic, but for clear-cut cases such as this one, creating a "discussion" first defeats the point of having an issue tracking and will result in even more work for everyone involved -- so I'd like to ask you to reconsider your policy here.

But, with that aside, I have not seen a fix trickle in, nor the discussion opened up. @dv1 are you proceeding with a discussion and/or PR? Should someone else pick it up? (I'm just an interested party/drive-by contributor)

**Comment by dv1** [comment]
@paravoid I added a workaround to AAPS. [See here.](https://github.com/NightscoutFoundation/xDrip/discussions/2503#discussioncomment-4248632)

**Comment by Navid200** [comment]
@paravoid Open a discussion and we can talk about the policies.
