### ISSUE TITLE
Error message in log Dailyintentionservice

### ISSUE THREAD

**Issue by MasterPlexus** [NightscoutFoundation/xDrip#254]
As I see it just sometimes and wondering what this means. The message tells that a column does not exist. As I see no other problems, this is for sure only a minor thing.

![screenshot_20180102-104949__01](https://user-images.githubusercontent.com/942153/34480207-50a0ee3c-efab-11e7-8e6d-6c14ff2d4c61.jpg)

**Comment by jamorham** [comment]
`CalibrationSendQueue` is a depreciated class and I will mark it as so in a future release. The cleanup method is still called to purge old data from installations which previously used this database table. You see this error because it is complaining that the table itself doesn't exist because you don't have any of this legacy data in your installation.

Other similar methods that pre-date the `UploaderQueue` have had their error reporting changed to debug only that would not then be visible in the event log and cause confusion. I will apply the same fix to this one as well.

**Comment by jamorham** [comment]
Should be resolved by: https://github.com/NightscoutFoundation/xDrip/commit/b2dcdf5f9466670dce61be78f256bf5251f908c4
