### ISSUE TITLE
Best way to move Xdrip plus master to new phone

### ISSUE THREAD

**Issue by Kustomwireless** [NightscoutFoundation/xDrip#259]
We have Xdrip plus setup with master and one follower my wife's phone is the master she now has a new phone and we need to move master setup over to her new phone what is the best way to do this.
We are using this setup with Libre and Blucon if that matters.

Thank you for this Life changing APP
Chuckk

**Comment by jamorham** [comment]
Install a fresh xdrip on the new phone and on the existing master use the 3 dot menu on the top right and select to share the settings via QR code and then select the all settings option. When the QR code shows use the new phone and in settings select Auto configure from barcode and scan the barcode. It should pick up all the settings (double check your alarms)

If that works then make sure to disable the original master being sync master or you will get in to all kinds of problems.

**Comment by Kustomwireless** [comment]
Thank you Ser went perfect.
And Thank You for ALL you DO
Will Basil entry and tracking ever be add to Xdrip +?

**Comment by mysticprog** [comment]
Hi,

How to switch to new phone if on old phone is broken screen glass ?
Thanks.

**Comment by Navid200** [comment]
@noctividus 
> I'm getting a new phone and I'm in the middle of a sensor. I understand how to move the database over, but I'm up on NightScout, so that's not as important as not losing 8 days on a sensor. Are there instructions somewhere about disabling the old phone as sync master and setting up the new phone as the new collector mid-sensor?

Please open a discussion:  https://github.com/NightscoutFoundation/xDrip/discussions
In it in addition to the question you are asking, include what CGM you are using.
If you are using xDrip as a collector from Dexcom, I will answer all questions.  If Libre, I will ask the individual who can walk you through the steps.

But, please let's use discussions, for discussions.
At the time this issue was opened, we had no discussions in this repository.  We do now.  Please help us encourage everyone not to use issues for discussions or questions.

**Comment by noctividus** [comment]
I opened this discussion and Navid200 provided clear instructions: https://github.com/NightscoutFoundation/xDrip/discussions/2479
