### ISSUE TITLE
Only one Bluetooth device for 'speak reading' ?

### ISSUE THREAD

**Issue by bjarkih1977** [NightscoutFoundation/xDrip#2641]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2548

<div type='discussions-op-text'>

<sup>Originally posted by **bjarkih1977** December 12, 2022</sup>
I'm having a bit of trouble with bluetooth devices and vehicle mode/speak readings.  I love having the function of xDrip reading the values to me when connected to bluetooth audio while e.g driving.  Problem is that I use another BT device at work and xDrip doesn't seem to store the info on both so at the start of work I have to pair xDrip to my work BT audio and vice versa after work when starting up the car.  Any suggestions?  Other apps on the phone are fine switching between BT devices.</div>

**Comment by doc77** [comment]
Hi, I just set up an xdrip profile in Tasker to connect to earbuds or my car. Works very well. You could probably do this in any automation app, but xdrip is  well integrated in Tasker.

**Comment by bjarkih1977** [comment]
Connecting the phone to the car audio isn't the problem.  The issue is that the xDrip app only seems to allow for one receiver overall.  Instead of e.g having a list of them to select from automatically.  I find this strange since all audio players on the phone just follow the bluetooth output automatically.  It's just this special car-mode that gets in the way.

**Comment by Kaapeli64** [comment]
Hi, technically this isn't about xDrip forming a Bluetooth connection with the car. It is about xDrip triggering functions in it based on the presence of Bluetooth connection. That is, when you are connected to car Bluetooth, xDrip can enable Text to Speech automatically, or some other functions.

Personally I am only interested in enabling Text to Speech when specified Bluetooth connections are detected. For example, I would like to enable Text to Speech any time I use either my own or my wife's car, but also when I put on headphones or earbuds or whatever.

That said, for me it would be enough if this "Detect car audio" had a list of Bluetooth MAC addresses instead of just one. I can understand it would become cumbersome to add different profiles to enable different set of features depending on which device you connect to. Having a list of devices would suffice my use case perfectly.

**Comment by Navid200** [comment]
I'm a little bit confused by this.
I don't believe it is xDrip that pairs to a Bluetooth device.  It is the phone that pairs with a device.  And your phone must have a list of Bluetooth devices.  

Is it possible that your phone deletes any Bluetooth device as soon as the link is not used?

**Comment by Kaapeli64** [comment]
Yes, the Bluetooth connection is completely handled by the phone. xDrip is only following from the phone which devices it has the Bluetooth connection enabled to.

That part works well, but you can only specify one Bluetooth device that triggers the vehicle mode. If you have two cars and you would like to enable vehicle mode when in either of them, you can only choose one of them. For this to work with multiple Bluetooth devices, there would need to be a list of MAC addresses in "learn current car audio" xDrip that enable vehicle mode. Not just one like there is now.

**Comment by Navid200** [comment]
@Kaapeli64 I'm sorry I did not tag.  But, my question was for the individual who opened this discussion.

I understand what you are talking about and we can talk about it.
But, I would like to address the concern this discussion was opened for first.

**Comment by doc77** [comment]
As I said previously on this thread, you can easily use Tasker to be able to trigger multiple Bluetooth connections that you have. It is very simple to create a single profile to trigger any Bluetooth connection made. For instance, I have 3 sets of earbuds and a car listed to start "speak readings" whenever any one of them is connected, and turn off "speak readings" when they are disconnected.

**Comment by Navid200** [comment]
@bjarkih1977 Can you try a different phone?
Do you experience the same issue?

**Comment by vanelsberg** [comment]
> Connecting the phone to the car audio isn't the problem. The issue is that the xDrip app only seems to allow for one receiver overall.

Not sure when this changed, but I am seeing the opposite now: On latest versions (current version = 20240419) xDrip+ started speaking readings to *any* BT device selected?

For long I have had xDrip+ only speak reading BG values when in the car by enabling Motion Detection -> vehicle mode and then select the car audio system using "learn current car audio. So it would only speak reading while in the car.

With this setting, since recent versions, xDrip+ started to read BG readings continuously on any BT device selected or even - when not connected to a BT audio device - over the phone. 

**Expected behavior**: only speak readings when in the car connected to the car audio device selected in settings?
