### ISSUE TITLE
FreeDNS for google cloud Nightscout down

### ISSUE THREAD

**Issue by mr-mjb** [NightscoutFoundation/xDrip#2787]
Seems today FreeDNS is down so I’m unable to access my Nightscout site.
While i appreciate this is not an issue of the xdrip team do you think there could be an option to import our privately owned domains?

To be honest the FreeDNS domains I find are regularly getting blocked so I would like to use a private domain but I’m not sure on the nginx setup manually.
Thanks

**Comment by Navid200** [comment]
FreeDNS is currently down.  If you look online, you will see that everyone is talking about it.
But, Nightscout set up through FreeDNS is working fine.
Let's see what happens.

Every domain server will have to be treated differently by us as far as associating the hostname with the ip.  
If you want to use a private domain you can.  But, you need to be able to take care of technical issues including setting it up yourself.

I see no way of setting up our platform such that you can bring in a hostname and being able to easily use it regardless of which server the hostname is from.

I am happy to develop such a thing if anyone has an idea.

**Comment by Navid200** [comment]
This issues platform used to be cluttered with questions.  It was impractical to maintain the repository and figure out which issue needed to be given priority.

That's why we opened discussions: https://github.com/NightscoutFoundation/xDrip/discussions

We have respectfully asked users to help us by using discussions to ask any question they may have even if they think there is a bug.
If it turns out to be an issue, we will convert the discussion into an issue.

**Comment by mr-mjb** [comment]
I just realised the mistake I made, should have been a discussion as I’ve done in the past.  Please accept my apologies!
