### ISSUE TITLE
Dexcom Bridge / Not receiving values from Dexcom Bridge

### ISSUE THREAD

**Issue by Erdella** [NightscoutFoundation/xDrip#2831]
Hello!

Hoping someone could point me in the right direction.  I installed NS but am using my own DNS. The site works, but I cannot figure out how to get the data to load from Dex. I re-created the Dexcom dependent account, have set up multiple followers and can verify data is flowing to Dexcom Clarity.
![image](https://github.com/NightscoutFoundation/xDrip/assets/53439889/72359d37-69f1-4a9a-b136-ae3ed66f4263)

Are there any logs I can look at to troubleshoot? Is the issue because of the way I'm doing the DNS....
Thanks!

**Comment by Navid200** [comment]
If you used a hostname from FreeDNS and it worked, you could then switch to your private DNS and look for a way to fix it.
But, you then would know for sure the cause is the private domain.

If you used a hostname from FreeDNS and it still did not work, you would know that something may be wrong with how you are setting up your uploader and can ask those who upload using Dexcom.

But, as it stands, there is no way to be sure what the cause of the problem is.
For all you know, it may be both.
The best way is to divide and conquer.

**Comment by Navid200** [comment]
Please don't open an issue.
Please follow our request that you must have seen while opening this and open a discussions instead:
https://github.com/NightscoutFoundation/xDrip/discussions

**Comment by Erdella** [comment]
Yep, I did see it. Sorry, thought I did open a discussion.
