### ISSUE TITLE
Feature request - Xdrip + stand-alone watch upload to follower & Nightscout

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#289]
I've set up my son with Libre, Bluecon, Xdrip+, and Nightscout, all linked to an Android Wear 2.0 smartwatch set as Forced Wear Collection. We follow him via Xdrip on our Android phones. It all works great - THANKS!
As the watch has Wifi and a data sim, it would be really good if the watch uploaded the numbers to followers & Nightscout without having to have a phone nearby.
Any chance you could incorporate this in a future update? Or, is it already possible and I've missed a setting somewhere?
Regards
Ali

**Comment by AdrianLxM** [comment]
It should be possible if you enable sync via the cloud in your Android-Wear companion app on the phone.

It still needs the phone to be running in order to sync to another phone. But it can stay at home with Wifi and on the charger. The way the data travels then would be:
Watch -> cloudsync -> paired phone at home -> follower phone.

**Comment by alexmoir1** [comment]
Great, thanks Adrian, I'll give it a try!

**Comment by Navid200** [comment]
@alexmoir1 Would you please close this issue if it was resolved?
Thanks
