### ISSUE TITLE
 Feature request - Add Basal input and tracking

### ISSUE THREAD

**Issue by Kustomwireless** [NightscoutFoundation/xDrip#302]
Is it possible to add a second type of insulin input so that Basal could be input tracked and graphed. 

Thanks for all the work you do and for a great APP

**Comment by jstevensog** [comment]
Add an MDI, I second this request.

**Comment by jamorham** [comment]
Is this for Lantus or something else?

**Comment by jstevensog** [comment]
Lantus for me. I'm sure there are other MDI basal insulins though. It could
be an option in settings. MDI yes turns off all loop/temp basal entry, and
just provides a basal entry instead.
Cheers

On 14 Feb. 2018 09:19, "JamOrHam" <notifications@github.com> wrote:

Is this for Lantus or something else?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/NightscoutFoundation/xDrip/issues/302#issuecomment-365424736>,
or mute the thread

**Comment by Kustomwireless** [comment]
My wife uses Levemir now but it would great if we were able to select any of the common insulin's and set onset delay time and duration. She is also MDI


Thank you for looking into this and all your hard work.


chuckk

**Comment by WanaGo** [comment]
Would be great to have the ability to enter different insulins each with customisable onset delay and duration, I agree. Some people use Regular (Actrapid) for protein bolusing, then Fast Acting like Novorapid/Apridra etc for food, then Lantus for long acting, and some even then do Inter Muscular shots for stubborn highs which the duration is about half what it is subcutaneous, but much faster acting. Would be awesome to be able to enter what you used and have xDrip plot its estimates based on those.

**Comment by lee-b** [comment]
There's no need to name the insulins.  "Simply" having a "basal" measurement that's shown on the graph like the boluses, but as a straight line until changed would be great for pump users.  Adding insulin profiles that change the (basal) IOB and delivery rate could be done later.

**Comment by Kustomwireless** [comment]
Really need to be able to enter Onset and Duration time because it is so different for each person.

**Comment by Kustomwireless** [comment]
What is required to get someone to work on this?

**Comment by andywilson** [comment]
I'd also find this very useful. I've used Lantus, Levemir and Toujeo, and each has its own insulin profile and duration. Happy to help test if needed.

**Comment by filipedanunes** [comment]
It would be great to have this feature.

**Comment by tremor** [comment]
That would be great, and maybe a drop-down list of 2-3 types of insulin that is often used in the treatment input field...

**Comment by Kywalh** [comment]
Hi all
Any news on this request ?
I also find this very useful to understand the mechanisms !!!

**Comment by DavitBS** [comment]
It would be great to have visual basal tracking as it can be shown in Nightscout.

**Comment by sodesignberlin** [comment]
1+ for basal insulin also from my side.

**Comment by hrasky** [comment]
I agree, basal recording and prediction would be great

**Comment by michelle197602** [comment]
Another vote from me, I'm a pump user so constant line of basal dripping in

**Comment by st0ber** [comment]
I would like to see basal and tbr.

**Comment by Kywalh** [comment]
what's tbr ?

**Comment by st0ber** [comment]
temporary basal rate

**Comment by YYurchuk** [comment]
Manually correct Onset and Duration time of insulins profiles will be very, very helpfull.

**Comment by psonnera** [comment]
Having the possibility to add insulin duration (3/9/20) or dual choice (fast/basal) in the bolus would be great.

**Comment by DunePlodder** [comment]
I would be happy to simply be able to record my MDI basal injections in xDrip (& Nightscout would be good). Then everything is recorded in one place - currently I keep a separate log just for my Levemir injections.

**Comment by n3bbf** [comment]
I would also really appreciate the ability to log and track my basal injections. Have always logged it in as a comment but graphing it on the display would allow me to better visualize what is happening (and when).

**Comment by candelanaj** [comment]
1+ for basal insulin also..

**Comment by yepee1** [comment]
Personnaly, I add a note using the **_Treatment Note_** icon. I type the Insulin name and the quantity. In my case I write: **_Tresiba 17 units_**. 

Then It's possible to track theses entries using the **_Note Search_** button.

Hope this will help someone :)

**Comment by stukov4** [comment]
Hi, +1 for basal insulin also.. 
Is this happening or is it just a thing a bunch of people wants but there are not real news?

**Comment by AnaHarr** [comment]
This would be very useful.  Using Lantus as Basal on MDI for our daughter.

**Comment by filipedanunes** [comment]
> Is this for Lantus or something else?

Lantus here. 
Can you tell us if there is any chance of this to be developed in a near future? :)
It would bring joy to a lot of people, theres any chance we can crowdfund this?

**Comment by filipedanunes** [comment]
> I'd also find this very useful. I've used Lantus, Levemir and Toujeo, and each has its own insulin profile and duration. Happy to help test if needed.

Can help testing too

**Comment by afcady** [comment]
I'm considering giving this a try.  I've never even built `xDrip+` so that's where I'll start.  Once I get to the point where I can build and install my own `.apk` I'll put an interface in to set the insulin type.  Then I can make the predictive algorithm just ignore Lantus &c completely.  Then maybe it can be modified to actually have a separate curve for each insulin type... if anybody can figure out what those curves should be.

**Comment by Kustomwireless** [comment]
@jamorham

**Comment by LTorrao** [comment]
:+1: Basal
:+1: Bolus

**Comment by afcady** [comment]
I did get xDrip to build (and successfully installed and ran it on a phone), but the build isn't incremental, so I have to figure that out before I can start making code changes.  Still planning to work on this though.

**Comment by stukov4** [comment]
> 
> 
> I did get xDrip to build (and successfully installed and ran it on a phone), but the build isn't incremental, so I have to figure that out before I can start making code changes. Still planning to work on this though.

Nice!!

**Comment by filipedanunes** [comment]
Having something with the appearance of diabetes m app for this feature would be an idea. Have a look.

**Comment by davidmtml** [comment]
Would love this feature as well!

**Comment by ImLateImLateForAVery** [comment]
Oh gosh, yes please!

**Comment by thevascgmdb** [comment]
This is crucial.
Spike app can do it.
We also need to be able to enter multiple bolas insulins and then be able to amend their peak time

**Comment by nadavv** [comment]
Thanks in advance for any one making it happen

**Comment by Son1k02** [comment]
Levemir for me, would be much appreciated having a graphical action curve for basal insulins, to allow sence to be made of rises and falls towards the end of the action profile. Effects and duration change per person, and for each person due to factors such as excercise, sickness, keto, insulin vial quality etc, so just a line that can be entered at a specific start time, and we can adjust in options our current duration and insulin type (action profiles are published by manufacturers). Having it also be uploadable to nightscout would eliminate my endo's biggest objection to xdrip reports.

Many thanks for making this happen!

**Comment by Dainem21** [comment]
Since I started to use only Tidepool, I realy like to see thhis feature, too.
Thanks in advance.

**Comment by nilsbusch** [comment]
This would be a very important feature for me too +1. (Basal: Levemir/Bolus: Humalog)

**Comment by MariVargas87** [comment]
+1 Here too! (Basal: Tresiba / Bolus: Fiasp)

**Comment by redman8** [comment]
Basal please :) Humalog

**Comment by wagnefrede** [comment]
Yes please Lantus as well :) would be great to see that feature

**Comment by Son1k02** [comment]
@K2s fantastic news! Any instructions for those of us unsure how to compile a version?

**Comment by wagnefrede** [comment]
> this ticket is obsolete ... there is active development in this pull request #973
> 
> it is working (I am using it) and Lantus is also included. you need to compile own version or wait until it is accepted in Nightly

@k2s  how can I compile that?

**Comment by k2s** [comment]
@Son1k02 @rudysroost @wagnefrede if you are interested in testing, please [read](https://github.com/NightscoutFoundation/xDrip/pull/973#issuecomment-540728359) and subscribe to that pull request comments

**Comment by mistermintsgh** [comment]
As well as the requests for the standard MDI basal to be implemented above, is it possible to include pump basal information in xDrip?

**Comment by lee-b** [comment]
Pump basal is already shown now, @mistermintsgh.  It's the blue rectangles at the top.  If you're not seeing those, check your settings, and that your particular pump is supported fully.

**Comment by mistermintsgh** [comment]
I don't have that @lee-b Presumably it's only available then for connected/loopable pumps? There's no way to display basal information for an offline pump?

**Comment by bennettnicholas** [comment]
I mean my pump puts in 1 unit every hour in, .1 increments. Is there a way to add "basal" support but you can just hard code it to track 1 unit every hour so the prediction curve is better?

**Comment by Nemz716** [comment]
Please can we have basal rates and the ability to add temporary basal rates be added to the app! Thank you 😄

**Comment by scgibbs** [comment]
Did anyone ever start on this?

**Comment by filipedanunes** [comment]
There's  an on going work: https://github.com/NightscoutFoundation/xDrip/pull/973?fbclid=IwAR1yU9FW8rSO6ReBKeyV9c1NZp17DyWgj2w_snnOX0JORZ9MKKoV5EK4q5w

**Comment by LakeSideCitizen** [comment]
> There's no need to name the insulins, or even have onset/duration initially. "Simply" having a "basal" measurement that's shown on the graph like the boluses, but as a straight line until changed would be great for pump users, at least, and probably great for everyone as a starting point. Adding insulin profiles that change the (basal) IOB and delivery rate could be done later. Main thing is, it would let you track basal changes, which can happen frequently with keto.

Well I use different basal, with different effect duration. To define just one  wouldn't work for me

**Comment by Kustomwireless** [comment]
Why can it not be set up just like the orginal insulin entry  where we can set onset and duration for the type of Insulin that we are using as Basal this has worked in GLIMP all along.

**Comment by dyjaks** [comment]
> Would be great to have the ability to enter different insulins each with customisable onset delay and duration, I agree. Some people use Regular (Actrapid) for protein bolusing, then Fast Acting like Novorapid/Apridra etc for food, then Lantus for long acting, and some even then do Inter Muscular shots for stubborn highs which the duration is about half what it is subcutaneous, but much faster acting. Would be awesome to be able to enter what you used and have xDrip plot its estimates based on those.

This is what I use R for and this feature is helping a bunch. All I'd want is a way to input protein or have a second carb entry that I can change absorption time for. As is the prediction gets thrown off because it assumes I ate 30g carbs that will be absorbed fast when really it's 30g "carbs" that will absorb quite slow.

**Comment by gapolv** [comment]
> Would be great to have the ability to enter different insulins each with customisable onset delay and duration, I agree. Some people use Regular (Actrapid) for protein bolusing, then Fast Acting like Novorapid/Apridra etc for food, then Lantus for long acting, and some even then do Inter Muscular shots for stubborn highs which the duration is about half what it is subcutaneous, but much faster acting. Would be awesome to be able to enter what you used and have xDrip plot its estimates based on those.

Hello did we have any update on these topics? I'm new to the app and seems like 

> > Would be great to have the ability to enter different insulins each with customisable onset delay and duration, I agree. Some people use Regular (Actrapid) for protein bolusing, then Fast Acting like Novorapid/Apridra etc for food, then Lantus for long acting, and some even then do Inter Muscular shots for stubborn highs which the duration is about half what it is subcutaneous, but much faster acting. Would be awesome to be able to enter what you used and have xDrip plot its estimates based on those.
> 
> This is what I use R for and this feature is helping a bunch. All I'd want is a way to input protein or have a second carb entry that I can change absorption time for. As is the prediction gets thrown off because it assumes I ate 30g carbs that will be absorbed fast when really it's 30g "carbs" that will absorb quite slow.

Exactly! Same case here, using Fiasp+Novolin R and struggling to input the protein+fat in the app..... Do you have any toughts on it? Know any other app being able to handle this? Thank you!

**Comment by gapolv** [comment]
> > Would be great to have the ability to enter different insulins each with customisable onset delay and duration, I agree. Some people use Regular (Actrapid) for protein bolusing, then Fast Acting like Novorapid/Apridra etc for food, then Lantus for long acting, and some even then do Inter Muscular shots for stubborn highs which the duration is about half what it is subcutaneous, but much faster acting. Would be awesome to be able to enter what you used and have xDrip plot its estimates based on those.
> 
> This is what I use R for and this feature is helping a bunch. All I'd want is a way to input protein or have a second carb entry that I can change absorption time for. As is the prediction gets thrown off because it assumes I ate 30g carbs that will be absorbed fast when really it's 30g "carbs" that will absorb quite slow.

Exactly! Same issue here, do you have any thoughts or suggestions? Do you know any other app that could handle this? Thank you!

**Comment by tolot27** [comment]
PR #1388 adds more insulin types including basal insulins. Visualization of basal insulin is not included to avoid touching the [business logic](https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-674791173).

**Comment by simonpickering** [comment]
I would also like to have basal insulin considered in the calculations, having read most of the thread in PR #1388 (much of which would probably be better in this PR re relevance) I have at least one concern/query, which is that the algorithm needs to know or be able to estimate a basal glucose generation rate in order to do anything useful. Does anyone have any thoughts/papers/etc. with which to look at this - I'm guessing one could start with a flat curve and then automatically populate it by looking at periods with no food and/or bolus insulin in the system. 

I definitely think it's worth a go (along with some automation of insulin sensitivity adjustment though the day/based on activity/previous activity), and I've started writing some MATLAB code to post-process my exported data to see whether any of this might work.

My reason for wanting this is that I'm on basal/bolus and my insulin sensitivity is very different overnight and during the day (and my basal insulin is a Lantus type ~24h action). My sensitivity also  changes significantly depending on how much exercise I do (as well as the usual illness, etc.), and I also get the feeling there's something else in the mix which is more short term - perhaps muscle glycogen restoration after high intensity/long duration exercise (e.g. riding bike a reasonable distance).

I guess some of this could be "fixed" by my using a basal insulin which lasts ~12h and injecting different quantities for day and night, but I am where I am for the time being and it would be useful to have this functionality to understand/predict things better.

I guess one way of avoiding the arguments would be to allow the end user to simply select the "business logic" they desire (from a list) and everyone can then be happy with whichever they want to use.

**Comment by tolot27** [comment]
> I have at least one concern/query, which is that the algorithm needs to know or be able to estimate a basal glucose generation rate in order to do anything useful.

A new algorithm would change business logic which is highly debatable. The adjustment of the basal rate is completely separate from bolus insulin and discussed independently in all CSII studies I know of. It is also highly dependent on the individual. Implementing algorithms to address this is a huge effort.

> Does anyone have any thoughts/papers/etc. with which to look at this - I'm guessing one could start with a flat curve and then automatically populate it by looking at periods with no food and/or bolus insulin in the system.

The basal rate is highly dependent on age and day time. Renner et al. developed some standard curves, see https://www.diabetologie-online.de/_storage/asset/1916029/storage/kirchheim:article-lightbox/file/334471441/16215326.jpg for instance. I've this data extracted, already.

I recommend to just implement an input option for the amount of injected basal insulin and displaying it as a single data point in the graph.

**Comment by simonpickering** [comment]
Thanks for the bar chart data :)

To your latter point, this is already available in XDrip, but it does nothing to the algorithm calculating predicted blood glucose (which is the interest I have). So perhaps this is the wrong place to discuss it if this issue/thread has already been resolved, and I should therefore open a new issue.

I agree that implementing algorithms is an effort, but one must start somewhere - I completely understand the desire to separate the basal and bolus calculations for the sake of simplicity of analysis, however as the graphs you provided show, unless you are on a pump you cannot account for the basal effects completely so they need to be taken into account when calculating boluses (which is presumably why the CSII studies don't need to do this as they assume an effective basal profile).

I can also well imagine that the basal requirement curves are quite different for different people, which indicates to me a good reason to look at whether at least some of this data can be automatically extracted from observed responses. Certainly from my point of view (not on a pump) that's my interest. Perhaps I am the only one who is not on a pump and is interested in this, who knows.

While I understand the reluctance to alter the "business logic" (for the sake on consistency and on the assumption that it works for most people), it would enhance the platform (IMO) if one were able to select different "business logic" implementations to handle what you wish, whether that's the addition of GI/GL, protein:fat:carb ratios or basal insulin, etc, even if these eventually turn out to not be as effective as the standard "business logic". The unfortunate alternative is that people will fork the application in order to implement their particular flavour of "business logic", which would be a shame for overall productivity.

**Comment by Navid200** [comment]
This issue, based on its title, was about adding the ability to enter basal insulin.
That capability already exists now.  Hence, I am closing this issue.

If you like something else, please find a related open issue and add your suggestion to it.

If you like to bounce ideas, please use the support channels.  Many developers frequent those as well.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
