### ISSUE TITLE
Freestyle libre 2 EU (French ) sensor recovered from pharmacy no longer works with third-party applications 

### ISSUE THREAD

**Issue by Domby91** [NightscoutFoundation/xDrip#3059]
hello, here is already the 9th sensor retrieved from the pharmacy which does not work with xdrip 
in fact when connecting it with Xdrip, it displays the error code “INVALID NFC data” 
for information I use the native freestyle libre application to start my sensors and then I start them on Xdrip as explained on many sites and forums 
I have always worked like this and before the year 2023, I had few problems on this side. 
Have the new sensors delivered in pharmacies received blocking codes only allowing their use via the native application associated with the sensors? 
the only ones that still work with XDrip are those received by abbot when I complain about a defective sensor.
I'm having a hard time since the sensors no longer seem to work with Xdrip, if anyone has a solution or simply an explanation, I would be eternally grateful 
Thanks

**Comment by Navid200** [comment]
You seem to have a question.  There is nothing wrong with that.  But, a question is not necessarily an issue.
That's why we have asked everyone not to open an issue and instead, open a discussion.  https://github.com/NightscoutFoundation/xDrip/discussions

If/when needed for tracking, we will ask you to change your discussion to an issue.
Thanks for your cooperation.
