### ISSUE TITLE
Remote Snooze not working

### ISSUE THREAD

**Issue by WanaGo** [NightscoutFoundation/xDrip#306]
Latest Nightly. 
xDrip on my phone, SW3 as collector. My wife uses xDrip as a follower, and I have a xDrip phone as a follower on my desk as a HUD.

When the alarm goes off on my phone, I can snooze it fine. When the alarm goes off on my wifes phone, Remote Snooze does absolutely nothing. I have done it as a preventative, and it still happens, and I have done it to try and snooze her phone as its going off, and nothing happens either.
The preventative is the main thing, if I have just had an alarm myself and dealt with it, and my wife is asleep, due to the Dexcom delay I don't want her alarm to go off and wake her  up unnecessarily. So I want to snooze her alarm for 30 minutes, so by the time my correction has sorted itself and Dex has caught up, her phone will be back into normal range and wont alarm. But it simply does not work.

I have her alarm limits set slightly lower the my low alarm, and slightly higher than my high alarm, so I get the first alerts. 

Is there a trick to making Snooze Remote work?

**Comment by tzachi-dar** [comment]
Do you have a master and follower(s) working correctly?

First thing you need to make sure that it is set correctly.
The phone sending the data should have "send snooze to all" checked.
The second phone should have "accept remote snooze".

How are the two phones connected? if by wifi is this the same network?
If not by the same wifi network make sure that "wifi name must match" is not set (this is not optimal since in this case, one might disable an alert at home, while he is at work).

If all of this is set correctly, then there is one thing to note: remote snoozing is limited to two minutes. Sometimes messages take more then 2 minutes to reach, and in that case remote snoozing will not work.

please verify that all settings are correct.

**Comment by WanaGo** [comment]
The phone sending the data should have "send snooze to all" checked. - Confirmed, was already set.
The second phone should have "accept remote snooze". - Was not set on 1 phone, will check the other when my wife returns. Thanks

Phones can be same WiFi sometimes, but sometimes on Cell network, or different WiFi, depending if home/work/out etc.

make sure that "wifi name must match" is not set - Confirmed, this has been disabled.

Thanks very much, will check on the wifes phone, it likely is just not set right, but I will come back to you. Many thanks for the help

**Comment by tzachi-dar** [comment]
Please note that if your wife is with your kid, and you are away, snoozing the alert is dangerous. She might not treat a hipo, make sure to silence it only when you know what you are doing.

**Comment by WanaGo** [comment]
I am the diabetic, not her or any of the kids.

**Comment by WanaGo** [comment]
Wifes phone was also unticked for the remote snoozing - Thanks for the tips about these settings.
I will test it tonight. So if I personally go high or low, I can snooze the follower phones so they are not disturbed when I have things under control myself.
