### ISSUE TITLE
Feature request - Falling and rising fast alarm

### ISSUE THREAD

**Issue by wannabeflatliner** [NightscoutFoundation/xDrip#311]
Hi,
I would like to request a feature for xDrip. It would be very helpful to add **glucose values to help with the falling and rising fast alarm** (value under which the fallling fast alarm will ring, and value over which the rising fast alarm will ring).

For example, let's say I'm at 15 and I'm falling fast, I don't want the alarm to ring cause it is expected. But now let's say that I'm at 5.5 and I'm falling fast, I might want to know it since I might prevent a hypo with that information.

Thank you for all the good work.

Wannabeflatliner

**Comment by jamorham** [comment]
Have you tried the predicted low alert for a similar behavior?

**Comment by ss1043** [comment]
Hello @jamorham and @Navid200, I'm quite unsure about the process here.
I would like to mention that I'm also very interested in this feature of #1604 and #311 and I want to ask if there is progress on it?
I like the idea from @ARkaine2 from https://github.com/NightscoutFoundation/xDrip/issues/1604#issuecomment-758599423.

**Comment by Navid200** [comment]
@ss1043 You can accomplish the same objective, for falling, if you use the existing Forecasted Low alarm.
Do you agree?  If not, please respond.

If yes, we can talk about rising.

**Comment by ss1043** [comment]
@Navid200 
I'm using the version from March 31st, 2021, and here is in further settings just the possibility to enable alerts for rising/falling blood sugar with a warning limit of 2 or 3 mgdl. Does it mean 2/3 mgdl per minute or per 5-minute cycle?

I would like to have something to get an alert when the blood sugar is rising/failing about x minutes with x mgdl. 
When I enable it like it is, I assume I will have a lot of expected alerts (e.g. after lunch, sports).

**Comment by Navid200** [comment]
@ss1043 So, is this a response to my question?  Or, did you not see my question?

**Comment by ss1043** [comment]
@Navid200 This was my response. Maybe I'm thinking about a different feature as you mean. 😅  My last comment was about the existing feature and what I'd like to have.

**Comment by Navid200** [comment]
@ss1043 We are not going to create a new feature that happens to be redundant.
In other words, if you can accomplish what you need with xDrip as is, we will not create a new feature for it since it's not needed.

Please read my post again, the one that you believe you have responded to.  Tell me what part of it is not clear.

**Comment by ss1043** [comment]
@Navid200 What I mean is, afaik we have this feature right now:
![tempFileForShare_20210420-075913](https://user-images.githubusercontent.com/28440976/115344963-640eb900-a1ae-11eb-83d3-5800d352c42b.jpg)

My suggestion is, to have the possibility to edit glucose level when this should be triggered and the time as long as the falling value continues. 

In case this already exists, please describe how I get this goal.

**Comment by Navid200** [comment]
Look at the second post in this thread, or my post of 4 days ago.

**Comment by ss1043** [comment]
> @ss1043 You can accomplish the same objective, for falling, if you use the existing Forecasted Low alarm.
> Do you agree? If not, please respond.
> 
> If yes, we can talk about rising.

@Navid200 No, I didn't try that, can you describe how, please? Where can I find this feature?

**Comment by Navid200** [comment]
@ss1043 Of course.
Go to the following page first.

Settings -> Alarms and Alerts -> Extra Alerts (xDrip+)

There, you can see "Forecast Lows".  If it is not ON already, turn it on.
Then, enable "Raise Alarm on Forecast Low".
You can adjust "Alarm at Forecast Low mins".

**Comment by ss1043** [comment]
@Navid200 thanks a lot

**Comment by Navid200** [comment]
The functionality you are asking for by adding a value to fast rising can effectively be accomplished by using the existing predicted low alarm as already explained.

The functionality of a fast rinsing alarm including a value can be accomplished if we had a predicted high alarm.  We have a pull request for it.  https://github.com/NightscoutFoundation/xDrip/pull/441
It has not been accepted and the reason is explained in the discussions of the pull request.  The reason will similarly affect the feature you are asking for.  Before we can develop a fast rising alarm including a value and merge it, we need to merge the pull request for the predicted high alarm.

Therefore, I see no reason to keep this feature request open.
We can always reopen it if needed.
