### ISSUE TITLE
How to get the Arrow back

### ISSUE THREAD

**Issue by Kustomwireless** [NightscoutFoundation/xDrip#321]
Now can someone tell me how to get rid of the N and get the Arrow back
![28377576_1809409226031236_5508081775518608268_n](https://user-images.githubusercontent.com/26770661/36710804-2c3e1ab4-1b4e-11e8-97bc-703f951ac69f.jpg)

**Comment by jamorham** [comment]
Is this a non-unicode font support issue? Did it ever work on this phone?

**Comment by endafarrell** [comment]
@Kustomwireless - in your phone's "Language & keyboard" settings, what Language is set on that phone? And, your answer to @jamorham's question will also help understand what's going on - the necessary first step to fixing it.

**Comment by Kustomwireless** [comment]
I asked this for a friend. This is the info I just received about your questions.
The Phone is a alcatel u5 Language is set  English (UK) She said the ARROW does show sometimes but then quickly  changes to the n like in the picture This is the Master phone Hope this answers the questions

**Comment by jwoglom** [comment]
This won't be conclusive -- because I don't know if your web browser will use the same system font as xDrip -- but do the different types of unicode arrows appear on a page like this? (look at the symbol in the top left of each box, not the image of what it should look like underneath)

https://en.wikipedia.org/wiki/Arrow_(symbol)#Arrows_in_Unicode

If it's switching back and forth between working and not working, maybe the "-->" arrow isn't supported properly by the font, while the 45-degree and straight up-down ones are, for instance.
