### ISSUE TITLE
Falling / Rising BG Threshold Alerts use mg/dl when mmol/l is set

### ISSUE THREAD

**Issue by lee-b** [NightscoutFoundation/xDrip#328]
As title, these Alert settings ignore your chosen units.

**Comment by tzachi-dar** [comment]
Did you actually see this happen?

XDrip internally does not care about the units. Before displaying the units to the user, they are replaced, but this is OK since data is stored on the correct units.

**Comment by lee-b** [comment]
I saw the problem directly IN the preferences as described.  It may be a
problem with hardcoded UI labels rather than db units and such.

**Comment by tzachi-dar** [comment]
In my version the text say "2 mgdl(0.1 mmol)".
Does it say something else for you?

What language are you using?

**Comment by lee-b** [comment]
Hmm. Mine is similar: "3 mgdl (0.16mmol)".  Not sure if I missed the part in brackets or if that's been added lately.  Either way, it's a bit strange to a) list both when I've selected mmol/l as the one I use; b) list the one I don't use first; c) list them with improper units (should be mg/dl, mmol/l, shouldn't it?).  I think it wouldn't hurt to revisit that.

**Comment by Navid200** [comment]
@lee-b 

a) It would require complicating the code to present a menu that varies depending on your other choices.  Instead, xDrip shows both units and you can choose to look at the one that is right for you.

b) See my answer to a) above.

c) These are slopes.  They represent how fast the blood glucose is changing.  So, the units that you have specified would be wrong too because they would be missing the time unit in the denominator.  
Nevertheless, I agree that the units are incorrect.  But, they do the job.  The user knows which option is for more rapid change.

I am happy if the units are corrected.  But, I will also be happy if the options are just marked with 1, and 2.

Unless there are any objections, I would like to close this issue.

**Comment by Navid200** [comment]
If you like to reopen, would you please state if you are willing to make the required edits yourself?
Also, would you please explain the level of hardship if this is not implemented?
Thanks
