### ISSUE TITLE
Support Wear 2.0 Complications

### ISSUE THREAD

**Issue by lee-b** [NightscoutFoundation/xDrip#330]
Not a high priority issue AT ALL, but similar to #244, it would be nice if Wear 2.0+ complications were supported, so you could customise the watchface by adding your own preferred additional information (be it the date, weather, fitness tracker, or whatever other complications are available from the system or third-party apps).

**Comment by jamorham** [comment]
They are supported already, please see: https://github.com/NightscoutFoundation/xDrip/issues/101

**Comment by lee-b** [comment]
xDrip supports providing complications for other watchfaces.  I'm talking about supporting embedding complications into the xDrip watchface, which would provide the functionality in #244, but also provide general extensibility too.

**Comment by Navid200** [comment]
@lee-b 
Considering there has been more than 3 years with only one person responding, I suggest you rewrite the request may be adding more detail or may be breaking it down into pieces.
Please help the reader understand exactly what you need.
Otherwise, I don't think this issue as it stands is going to serve you or anyone else.

**Comment by lee-b** [comment]
Already answered.  Feel free to close.  Thanks!
