### ISSUE TITLE
Feature request - Automatic upload to cloud/Google Docs

### ISSUE THREAD

**Issue by Biggerandreas** [NightscoutFoundation/xDrip#334]
Could be nice if the data would automatically upload onto a cloud so I can show it to my doctor.

**Comment by endafarrell** [comment]
@Biggerandreas - have you come across [Nightscout](http://www.nightscout.info/)? Many of us use xDrip+ to upload - in real-time (so that we can see it in phone apps, on watches, be a "follower" of our diabetic children so that we can remotely see their glucose readings) - to Nightscout. 

Here's a [video that gives an introduction](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=10&cad=rja&uact=8&ved=0ahUKEwjsktyV-dnZAhUI2KQKHaNVBVQQtwIItgEwCQ&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DmnkIYUN-R9U&usg=AOvVaw2tU9CF6kxzql1r_oNRSCv4). Getting started is something that takes some work - but almost everyone finds it to be very worth while.

For sharing information with doctors, your Nightscout has your data in many reports - Day to day / Daily Stats / Distribution / Hourly stats / Percentile Chart / Weekly success / Calibrations / Treatments / Profiles - and they all can be customised. Going this route means you can reuse the fantastic work of others.

**Comment by Biggerandreas** [comment]
@endafarrell Thanks, I'll look into it.

**Comment by Navid200** [comment]
@Biggerandreas Would you please close this issue as it seems your question has been answered?
For other questions, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Biggerandreas** [comment]
@Navid200 Of course
