### ISSUE TITLE
New upgrade broke high values

### ISSUE THREAD

**Issue by KevinDenys** [NightscoutFoundation/xDrip#343]
After updating values above 300 show up as a low 30. 319 on freestyle libre shows as 31 https://imgur.com/a/M65cQ

**Comment by KevinDenys** [comment]
Hmm after looking at the data its everything above 270 that shows up as 27(low)

**Comment by KevinDenys** [comment]
https://imgur.com/a/kAmMg

**Comment by keencave** [comment]
Can you Post a Screenshot from the BG Data Table in the Menü? To be enable in system - less Common settings.

**Comment by KevinDenys** [comment]
https://imgur.com/a/gS7io

**Comment by tzachi-dar** [comment]
What is the sensor type that you are using?

**Comment by KevinDenys** [comment]
I have a freestyle libre sensor and I am using an ambrosiasys blucon sender

**Comment by tzachi-dar** [comment]
What was the last version that worked? What are your calibration params?

**Comment by KevinDenys** [comment]
The version I had before the upgrade screen was: 20a4313-2017.11.13 here everything worked fine. Then I updated to the latest version and the bug started happening.

**Comment by tzachi-dar** [comment]
Here is what I think that has happened:

Your data based on the last bg table was 479.647. This is the last value measured before problems has happened (this is the raw value measured).

Since this value is being multiplied by 117.64705, the value before multiplying was .
(See the function blukon.getGlucose()) to understand the calculation.
So, the value read from the hw is: 4077 (I assume value was devided in 1000) some where.

4077 in hex  is: 0xfed which is almost the latest values that can be read using 12 binay bytes.
Due to very bad lack the 13 bit was removed from the calculation therefore the numbers got smaller again.

@KevinDenys What you can immediately do is 1) return to use the 13'th bit  2) use another algorithm for calculating bg.

To return the 13'th bit do: in xDrip settings->less common settings->calibration settings->use 13 bit ads mask.
To use another algorithm please follow instructions on: https://github.com/tzachi-dar/LibreOOPAlgorithm

I hope this will solve the problem.

**Comment by KevinDenys** [comment]
Hi, thanks for explaining. Currently I switched back to the 2017 version where everything worked fine. When I have some free time I'll try out the 13th bit mode.

**Comment by keencave** [comment]
You can use the current nightlys. Your BG data table screenshot showed clearly that you had values beyond the 12 bit coding which leads to a simply numerical overflow resulting in a fake low value. Please enable the 13th bit as @tzachi-dar described above and yoou are done. Hope that you dont have this high values in the future. I found this behaviour some weeks ago having also very high values after a party night and @jamorham added this 13th bit mask.

**Comment by KevinDenys** [comment]
Okay, I updated the app. But I cant check the 13th bit check box? Do I need to uncheck/check other settings to enable 13th mode?

**Comment by KevinDenys** [comment]
https://imgur.com/a/G7sdR

**Comment by keencave** [comment]
Have you enable engineering Mode?

**Comment by KevinDenys** [comment]
I was not, my bad. Okay its enabled now. Hope this solves the problem. Thanks for the help and your patience!

**Comment by jamorham** [comment]
13bit mask mode in enabled by default in the latest nightly.  Instructions for getting nightly version on automatic update is here:

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by jamorham** [comment]
This should be resolved.
