### ISSUE TITLE
Insulin Fiasp Prediction

### ISSUE THREAD

**Issue by m1st0** [NightscoutFoundation/xDrip#351]
It may be too early to tell, but Fiasp has a different curve it seems for prediction values. It starts quicker, unsure if it does not last as long as Novolog.  Its advantage of acting more closer to the onset of a person's own insulin may add a need to specify which rapid acting insulin is in use. Although we assume insulins like Novolog and Humalog are similar enough in onset and duration, we may have need to start to differentiate insulins. I believe a better place to start would be Fiasp because it is more different. Maybe if needed I can look into the technical prescription documentation to share more for the prediction algorithm.

**Comment by Son1k02** [comment]
Not just fiasp, but different insulins affect people differently. I'd love to have an option to adjust how long the insulin action graph lasts (don't know why adjusting insulin duration in predictive settings doesn't do this automatically), & when a viable action starts. 

At the moment it takes my Novorapid about 45m to start having an effect unless it's been injected into a vein, & it's duration is set to 3.75hrs however the graph shows around 3hrs. This makes the bolus wizard & prediction graphs much less useful to me, & I'm wishing to be able to rely on it's predictions more.

**Comment by miletine** [comment]
Where is the duration set?  I have to move to porcine for the next few months (testing insulin sensitivity) and it's duration is closer to 6 hours.  Reprogramming the pump would be much easier with this input on the graph.  I can try to manually hard code it in my fork.

**Comment by miletine** [comment]
Insulin Action Times from various sites:

https://www.diabetesnet.com/about-diabetes/insulin/insulin-action-time
http://static.diabetesselfmanagement.com/pdfs/dsm2511_4833.pdf
https://www.diabetes.co.uk/insulin/insulin-actions-and-durations.html
http://www.ema.europa.eu/docs/en_GB/document_library/EPAR_-_Product_Information/human/004046/WC500220890.pdf
http://www.novonordisk.com.au/content/dam/australia/affiliate/www-novonordisk-au/Health%20Care%20Professionals/Documents/NovoRapid_NovoMixd_s28102014_Marketing%20version.pdf

Animal short:  Onset Within 1 hour,  Peak 2 to 5 hours, Duration 6 to 8 hours
Aspart (NovoLog) Glulisine (Apidra) Lispro (Humalog): Onset 5–15 minutes, Peak 30–90 minutes, Duration less than 5 hours 
Hum/Nov/Apidra: Onset 10–20 m,  Peak 1.5–2.5 h,  Duration  4.5–6 h
Novorapid: Onset 10-20 m, Peak 1-3 hr, Duration 3-5 hr
Fiasp:  Onset 5-15m  (estimated from description),  Peak 1-3 h, duration 3-5 hr 
(Fiasp and Novorapid considered equivalent over the full length of application)

**Comment by RaabenFuchs** [comment]
hi, i'm using fiasp, too. i have set the duration to 3h (inxdrip+ prediction settings) and on the graph it shows exactly the 3hours on my phone

but maybe 3 hours is a bit short, whats your setting?

**Comment by miletine** [comment]
In Predictive Simulation Settings I only see "Carb Ratio" "Insulin Sensitivity" and "Carb Absorption Rate".  Where is duration set?  Doesn't the absorption rate setting have only one slope based on 35g?

**Comment by RaabenFuchs** [comment]
You're almost there.Goto last option 'extended prefs for algos' below eula on this page                                                                                                                                                                                                                                                                                                                                                   Von: notifications@github.comGesendet: 19. März 2018 12:23 vorm.An: xDrip@noreply.github.comAntworten: reply@reply.github.comCc: dhilipp@web.de; comment@noreply.github.comBetreff: Re: [NightscoutFoundation/xDrip] Insulin Fiasp Prediction (#351)  In Predictive Simulation Settings I only see "Carb Ratio" "Insulin Sensitivity" and "Carb Absorption Rate".  Where is duration set?  Doesn't the absorption rate setting have only one slope based on 35g?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by miletine** [comment]
Thanks,  I missed those settings at the bottom.

I agree, I wasn't looking for an update now I  just wanted to know what was there already before I started to dig into how I might need to change it.  The porcine is incredibly slow compared to the fiasp and very few people would need it.

**Comment by RaabenFuchs** [comment]
np. so theres still porcein insulin to buy? and you can get it for a pump?

if youre in mood to tell, what is a sensitivity test?

**Comment by miletine** [comment]
Sorry if this is off the original topic but the answer to your question is long.

There is a group in the UK that is promoting awareness that a percentage of diabetics still require animal insulin and provide information about its availability:  https://www.iddt.org/publications/30-years-of-synthetic-insulin

Wockhardt UK still produces porcine insulin.  Hypurin Regular is a medium/fast acting insulin that has the buffers required to use in a pump but I believe that few pump manufacturers have formally tested so they can’t approved it’s use without supervision.  Hypurin NPH is a very long (up to 24 hour) insulin without the required buffers so it cannot be used in a pump.  

If you read the papers issued with each insulin you will find a mandatory list of infrequent side effects encountered during testing.  Apparently, because it really is life saving, if it does not affect blood glucose response then it is fair game for regulatory approval.  As a result, once approved, there is little interest in pursuing a review of those side effects.

Infrequent Side Effects of many insulin formulations:  Typically  < 1% of diabetics affected
• Hypokalemia (low potassium) You might be more at risk if you are losing potassium (e.g. diarrhea)
• Hives and rash may occur  (two types: at the injection site and Chest or wide spread areas away from the injection site)
• Less sensitivity to onset of hypoglycemia
• Extreme Lethargy
• Mental Confusion
• Memory Loss
• Joint and Muscle Pains
• Depression
• General feeling of being unwell

Skin Complications (7 common types listed in http://www.diabetes.org/living-with-diabetes/complications/skin-complications.html)
• They list extreme cases but for some individuals their sensitivities will cause similar reactions, likely based on these basic mechanisms.

An “Allergy” must have a fairy rapid response to an irritant to be formally recognized and a “Sensitivity” is more like an undesirable reaction that occurs over time. Very little study appears to have been done for those affected by these kinds of side affects that appear slowly.  

A sensitivity test requires you to switch insulins for a period of time (we find 3 months seems to work well) and track to see if the symptoms change due to that one main change.  It appears that in most cases people who react it are not sensitive to the insulin itself but to an ingredient in the mixture.  There are sometimes two suppliers with the same insulin (e.g. NOVORAPID and FIASP both use ASPART) but the concentration and mix of other ingredients are different so it would make a difference for some people.  Of course there are those few who are truly allergic to insulin itself but since the insulins are created differently it makes sense to confirm if it is the specific type and not all insulins that is the problem.

Different Types of Insulin I have briefly reviewed:
• insulin lispro
• insulin aspart
• insulin glulisine 
• Insulin glargine 
• Porcine insulin (Available imported from England)
• Bovine insulin (I believe still available in Argentina but not an approved import to Canada)

Common Non-Medical Ingredients, some with reported infrequent similar side effects of their own:
• Glycerol
• Tromethamine
• meta-cresol
• Phenol
• zinc oxide

If you are sensitive to insulin or a common ingredient one approach is to find the mixture with the lowest concentration of the irritant and use micro doses (like in a pump) to slowly acclimatise the body.  Another approach is to go to intravenous because some of the reactions are due to antibodies formed when the insulin is injected in the skin tissues. 

Sent from Mail for Windows 10

**Comment by xkamor** [comment]
I am usin Fiasp and find out that the predictions are wrong with actual insulin model. I've put as duration 3.5 h. I see on the graph that there is a triangle with peak at half time. The main issue is that Fiasp is not a simmetrical curve, the peak is very erly compared to its duration. Reading the comments here i'll try to put the duration of fiasp to 1.67 h getting the peak at 50 min and check the predictions. The best will be to add a field for insulin saying the peak time (duration+peak time) equals to asymmetrical triangle.

**Comment by Navid200** [comment]
I am closing this issue because we have consolidated all insulin requests: https://github.com/NightscoutFoundation/xDrip/issues/1898
You can continue the conversation here in this issue about this particular request.

Please don't post in the consolidated table issue.  Please either use this issue or [Discussion](https://github.com/Navid200/xDrip/discussions) for any conversations.

**Comment by Navid200** [comment]
Fiasp was added I believe at the end of 2019.
