### ISSUE TITLE
Option to vocalize glucose readings at longer intervals.

### ISSUE THREAD

**Issue by dave1812** [NightscoutFoundation/xDrip#369]
I like having Spoken readings, but I'd also like to have the option to space them out, for example every 10, 15, 20 minutes, or even much longer, at my option.

**Comment by jamorham** [comment]
@jsroberts92 To answer your last point, have you tried using the `Speak Alerts` feature? It should announce things like predicted low

**Comment by jsroberts92** [comment]
Yes, I've given the speak alerts feature a try. My issue is that when I pressed to test the alert, the speak alert only seems to activate after the alarm notification has been acknowledged/dismissed on the phone (at which point I may as well just read the alert myself!)

I'd appreciate the option to have the speak alert in place of the alarm noise so that it would just straight up tell me"low test" instead of playing the alarm noise until I dismiss it. Or can this be achieved some other way?

**Comment by jamorham** [comment]
Please try the May 3rd nightly and see the new options in the `Speak Readings` section.

Please let me know if this works. Thanks

**Comment by jamorham** [comment]
Here you can set the minimum number of minutes between each reading or the minimum change. If either thing happens, eg glucose changes vs previous spoken reading by more than the amount set or more than the specified number of minutes pass then the reading will be spoken.

**Comment by dave1812** [comment]
It works!   I set it to roughly 17 minutes and also adjusted the md/dl but since my bg doesn't move too fast I don't know if that aspect of it works, but very cool!   Thank for adding this new feature!  Very worthwhile and I'm sure others will take advantage of the new options.

**Comment by jamorham** [comment]
Marking as resolved.

**Comment by dave1812** [comment]
The varied time for spoken values is AWESOME (thank you!!), but can you please change the rate of change minimum from 4 to 2, as 4 is too large of a rate of change.  Most CGM software is coded to allow for either 2 or 3 mg/dl/m.  I always choose 2 to get alerted more quickly.
