### ISSUE TITLE
Does anyone have experience with Huawei SmartWatch 2 as a collector?

### ISSUE THREAD

**Issue by avr248** [NightscoutFoundation/xDrip#374]
Does anyone have experience with Huawei SmartWatch 2 as a collector?
Is it necessary to make a patch for the BLT?

**Comment by lucychiu** [comment]
It would be great to have a timeline of when a patch can be created for the Huawei Watch 2. Happy to provide logs to assist with this.

**Comment by mileom85** [comment]
It is necessary to have have a patch for Huawei SmartWatch 2. Without it it can't work as a collector. We have it but can only send data to WatchFace from smartphone.

**Comment by avr248** [comment]
Please, if there is someone with knowledge who can prepare to explain how to make a patch... it will help very much !!

**Comment by mileom85** [comment]
@jamorham is going to try to create a patch. I have sent him backup of system partition from my Huawei Watch 2.

**Comment by avr248** [comment]
thanks

**Comment by lucychiu** [comment]
Great thanks. 
I have the Android 8.0 update (build# OWDE.180215.017), let me know if there's anything I can provide to assist Jon.

**Comment by mileom85** [comment]
@lucychiu I have submitted system partition from same build. When @jamorham creates patch you will also be able to use it 😄

**Comment by jamorham** [comment]
I will start work on this shortly

**Comment by jamorham** [comment]
Can you guys give me all the information about build numbers, kernel version etc from the Settings -> About page from the watch? Thanks.

**Comment by lucychiu** [comment]
Build: OWDE.180215.017
Google WearOS 1.1
Android 8.0.0
Kernel - cannot find.

**Comment by avr248** [comment]
Build: OWDE.180215.017
Google WearOS 1.1
Android 8.0.0
Kernel - cannot find.

**Comment by ralf-ms** [comment]
Buiild: OWDD.180215.018
Google WearOS 1.1
Android 8.0.0

**Comment by alexmoir1** [comment]
I have set this up for my son. We have a Freestyle libre. On top of that sits an Ambrosia Bluecon device. The Bluecon converts the Libre readings from NFC to Bluetooth & sends them to Xdrip+ running on the watch. The (Android Wear 2) watch sends the data to his (Android) phone, follower (Android) phones & Nightscout in the cloud. When we first set it up it seemed to work great, but the problems arise when the watch loses bluetooth connection to the Bluecon. It's then a major hassle to get it re-connected. So until a more robust solution comes out we've stopped using it.
I prepared the attached document to help.
[BlueconLibreXdripNightscout.docx](https://github.com/NightscoutFoundation/xDrip/files/1973624/BlueconLibreXdripNightscout.docx)

**Comment by mbickelhaupt** [comment]
Build: OWDD.180215.018
WearOS 1.1
Google Play Services: 12.5.29
Android 8.0.0

**Comment by mbickelhaupt** [comment]
I have the event logs of a failed attempt to use the Huawei 2 on the 05.04.18 build paired with a g5. Succeeded in "found,connecting" but no BGL data pickup.

**Comment by avr248** [comment]
Good Luck

**Comment by mileom85** [comment]
Build: OWDE.180215.017
Google WearOS 1.1
Android 8.0.0

**Comment by jamorham** [comment]
Okay, I have now been able to receive readings from the G5 but it isn't yet stable. I'm still working on it, getting closer though.

**Comment by jamorham** [comment]
Okay, I now have demigod mode working as well. Quite a few modifications are needed overall though.

Is everyone on this thread using the 4G version of the watch?

**Comment by ralf-ms** [comment]
No, just the wlan version...

**Comment by lucychiu** [comment]
Hi Jon,
That's great news. I am using the 4G version.

**Comment by alexmoir1** [comment]
Yes, 4G

Regards 

Ali 

On 2018-05-14 09:45, JamOrHam wrote:

> Okay, I now have demigod mode working as well. Quite a few modifications are needed overall though. 
> 
> Is everyone on this thread using the 4G version of the watch? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/NightscoutFoundation/xDrip/issues/374#issuecomment-388742028
[2]

**Comment by mileom85** [comment]
Yes, 4G version.

**Comment by jamorham** [comment]
I'm planning to release two versions. The first version coming very soon will fix the bluetooth and add demigod mode.

A second later version will attempt to optimize battery life and add any other niceties I can get working.

**Comment by ralf-ms** [comment]
Hi Jon,
splendid! Sounds great!
Will the versions you mentioned above be functional for both kind of the huawei watch 2 (4G and wlan only)?

**Comment by jamorham** [comment]
Okay guys, grab the care package here!!

https://drive.google.com/open?id=1vls9Vh1tRqAwSpqcHG71EvWhfuooDhn3

I have tested this with the 4G version. I don't know if it will work on the non-4g version. Please try that out too and when the patches are applying look very carefully at which ones say OK or ERROR so I know where changes may need to occur.

Please make sure to backup your watch before making any changes. In TWRP the system image backup and the boot image backup are the most important. Make sure you also pull these off your watch sdcard and keep them safe. You will need these to back out the changes if anything goes wrong and if I produce a version 2 of the patch I will likely want you to restore from the backup first. 

The tests I have done so far look good with this. It should work with G5 and other collectors like miaomiao.

There may still be a stability issue, if you find you're not getting any data then reboot the watch. In my tests it seems like if it doesn't work a reboot fixes it and then it remains solid.

How does it work a live environment? I don't know so please test this and let me know!!

**Comment by avr248** [comment]
Thanks a lot, I'll try it and update later

**Comment by avr248** [comment]
not working for OWDD.180215.018

**Comment by ralf-ms** [comment]
No, I did a clean install with the OWDD rom provided here:
https://developer.android.com/wear/releases/wear-preview-downloads
(non-preview-image sawfish-factory-OWDD.180215.018.tgz)
After removing the two services.patch* files, patching succeeded except for the demigod modes (see attached image),  and I'm now able to run the collector on the watch! 👍 
I will send you a link to the TWRP backup I made before patching.

![huawei-patching](https://user-images.githubusercontent.com/35162235/40057936-f1bb9c1a-584f-11e8-8e4b-cefbd9f60ed6.jpeg)

**Comment by lucychiu** [comment]
Currently reinstalling from image in XDA developers. (https://forum.xda-developers.com/watch-2/development/rom-t3705589)
Wasn't able to use adb to pull and push using Windows 10. There's a known issue with the creative update.
I'll try again in a few days using a Windows 7 system.

**Comment by jamorham** [comment]
I can probably produce the alternate patch version from the OWDD files available on the android.com link @ralf-ms posted. The main issue with running without demigod mode is that there may be problems with the watch sleeping and missing readings.

**Comment by avr248** [comment]
Are you going to create a patch soon?

**Comment by lucychiu** [comment]
Windows 10 Creative Update - ADP pull and push doesn't work, however I was able to use this workaround here to do the ADP pull and push: https://wiki.lineageos.org/adb_fastboot_guide.html.
Note: this didn't work for me while I had the TWRP app running.

I did a clean install of Android 8.0 using the image from XDA developers last night, and applied the security and demigod patches. All the patches failed... I  wonder if it's because there's a TWRP app install on the Android 8.0 image.

As my watch was purchased from China (Model LEO-DLXX), last year I did flash it with an International rom in order to use the watch properly. (https://forum.xda-developers.com/watch-2/how-to/guide-how-to-flash-english-firmaware-to-t3602140) So I will do a clean install with this rom with Android 7 and wait for the OTA updates back to Android 8.0.

I have used TWRP in the past to load Cyanogenmod onto a tablet, and I was able to copy files to the SD card from the windows explorer. I think the Huawei drivers are not installed properly on my laptop which is why the watch's internal storage didn't show up on windows explorer; and why I was using the ADP commands.

**Comment by jamorham** [comment]
@avr248 yes I will work on a proper patch for the non-4g version shortly.

**Comment by jamorham** [comment]
The care package is updated now with an alternate patch for the non-4g version of the watch:

https://drive.google.com/open?id=1vls9Vh1tRqAwSpqcHG71EvWhfuooDhn3

I haven't been able to test this as I only have a 4g one, so I would be very grateful to know if this works or not.  If it fails then you will likely need to restore the system image from backup or reinstall it from the factory image link posted by @ralf-ms above.

@ralf-ms if you apply this then it should enable demi-god mode but the already applied patches will report failed but that wont matter.

**Comment by izywizy** [comment]
I've been following this thread as I have the Watch 2 non-4g.

I've just applied the 'care package' and can confirm everything went very smoothly as I'm quite familiar with twrp as I use or have used it on quite a few devices so your instructions were very easy to follow.

I have tested 'force wear collection' and it works perfectly with libre/blucon combo, not tested wear collection when phone is out of range yet, i'll do that tomorrow.

I'd like to offer my gratitude for the work you've done on this and also to you and the other devs for the brilliant xdrip app.

best regards.

**Comment by mbickelhaupt** [comment]
Trying to get the watch into fastboot mode. Running on a linux system, I can recognize the device with "fastboot devices" but when I issue the command "fastboot oem unlock" (or any fastboot commands) I get the message waiting on device. On the watch end of things, it is just happily sitting in fastboot mode without receiving any commands.
 I have enabled adb debugging, is there something I am missing on the watch end that is hanging me up?
Sorry to take us back to kindergarten. I can just barely do these flashing and running terminal things, and when something goes awry, I get stuck pretty quick.

**Comment by lucychiu** [comment]
@izywizy just wondering, do you have the normal windows 10 or one with creative update?
Also, do you have the Huawei drivers installed?

**Comment by lucychiu** [comment]
@mbickelhaupt can you try 'adb devices' and see if it lists your watch?

**Comment by mbickelhaupt** [comment]
I'm working with Ubuntu. I have a windows computer that I would prefer, but it sounded like Linux would be easier. I can connect to the watch on adb, and have always accept this computer. I can even run adb commands and force it into the fastboot. Just nothing in fast boot other than the computer recognizing the watch.

**Comment by lucychiu** [comment]
Okay, I don't know much myself either. Just following the instructions and
using Google to work through the issues I'm having.

**Comment by jamorham** [comment]
@mbickelhaupt I had this problem on one linux box and had to switch to another. I think there may be some low-level usb compatibility issue with the watch itself. Having said that when I tried it another time it did work okay on the first box. I would try another USB port, hub or even another machine if that is an option.

**Comment by jamorham** [comment]
@izywizy thanks for confirming the non-4g version also works! phew

**Comment by avr248** [comment]
yesss!!! it work!!
thank you very much!!

**Comment by izywizy** [comment]
@lucychiu, If you're talking about the Win10 April update then no, I did install it but had to revert to the previous version as I encountered the Chrome freezing issue that many have but up to date other than that.

I don't have the Huawei drivers installed just the universal adb drivers which seem to work just fine with any device I'm fiddling with.

@all, I have tested the 'out of range wear collection' by turning off the phone, I waited a good 20 mins or so but no collection.  I checked the bluetooth settings on the phone and there was an unknown device showing, I removed that and then scanned and the watch picked up the blucon and registered it but always shows as unavailable.  I rebooted the watch and blucon and then after approx 12 mins the watch connected to the blucon and I got my first reading and it carried on collecting for around 30 mins until I turned on the phone again.

The good news is it carries on collecting even when the screen is off so that should help battery usage somewhat.

Not so good news when switching back to the phone, I waited 30 mins and no automatic switch back to phone collecting.

@jamorham  regarding the above issue, I notice that when using the watch as collector the data source is always listed as LimiTTer and works fine and when I turned on phone to switch back to phone collecting the data source is still showing as LimiTTer, the problem here is that the the phone will never start collecting unless the data source shows as Blucon, and that always requires a restart of the Blucon.

any suggestions ? thanks.

**Comment by ralf-ms** [comment]
the new patch worked for me as well (with the bt patches failing like Jon mentioned because they've been already installed).
switching back from phone to watch and vice versa seems a little bit messy, I've also found that there are problems sometimes (where you have to wait for 10-15 minutes), but also found it to be running at once and then in turn it is not a bit working (where you have to reset blucon, reboot watch, disable phone's bt and so on).
Unfortunately I am not able to tell an exact procedure which path to follow if it is not working at all.
When having difficulties I see on the Systemstatus page "Watch Service State: Attempting connection" as well as "Bridge Device: Connecting", without neither of it advancing to "connected".

![btcon1c](https://user-images.githubusercontent.com/35162235/40176217-ebcf2ad8-59da-11e8-893c-9d729b90901a.jpg)

**Comment by ralf-ms** [comment]
Hi Jon,
complete agreement!
This is a big step forward and I can finally use the watch as a collector which was not possible before.
I'm very grateful for all your effort, work and patience!!
Lets gain some experience over the next days and find out what has to be done in specific situations.
Thanx again for all your support!

**Comment by lostboy86** [comment]
Sorry i have a 4g, i have flashed boot security fix and demigod patch etc for 4g, but for me the two demigod not applied from twrp, how i can resolve?

i have this rom : https://forum.xda-developers.com/watch-2/development/rom-t3705589

Is also for me for the diabethes, for xdrip.

Can you help me Joan? Thanks a lot

**Comment by lucychiu** [comment]
@izywizy the April date hasn't pushed through yet to my laptop. I think it's because I did a fresh install removing all the bloatware which has caused me a few issues other than this. Good to know about Chrome freezing with this update.

@all I have managed to apply the patches successfully and enabled demigod mode on my 4G watch. But I can't test until I fix my transmitter.

My problems have been trying to copy files across
1.  When I plug the watch in, windows opens a blank folder so I can't copy the backup and patch files between devices. 
2. adb pull and push doesn't work for me while in twrp, but works while the watch is running normally.

Also after using twrp to do a backup, for some reason my watch doesn't boot, gets stuck with the Huawei logo. So this time booted back onto twrp and turned on adb sideload and installed the patches that way.
And I've setup the watch now and used ADB pull to grab the backup file. 😊

Will update again when i've got the transmitter working and can test with the watch.

**Comment by lostboy86** [comment]
Do you have a original rom oreo, or my rom into link above?
Because my bt patch work ok, but i had two error for demigod mode not apply, can you help me?

Thanks a lot

**Comment by lucychiu** [comment]
@lostboy86, I don't have the original rom for my watch (model LEO-DLXX), which is from China and I replaced it with International rom.
I did try the Oreo rom that you linked above and I received errors when patching it (can't remember which ones). So I went back to Android 7 waited for the OTA updates and have now applied the patches successfully.

**Comment by jamorham** [comment]
What sort of battery life are people seeing? Even before patching the watch I have for testing here it didn't seem to do a whole 24 hours. More like closer to 12 hours. 4G standby seems to consume 30% of power even when the watch is in wifi-range all day.

**Comment by lostboy86** [comment]
@jamorham my watch, if i put only bluetooth for miaomiao+libre connect, battery is ok for almost 2,5 days (ALL other function off : gps, 4g, wifi, gesture, etc).
I know i have a big request, but my watch is 2,5 days battery also because i have a rom above, can you provide your patch for this rom? Is the most rom used for this watch, can increas the battery very very good.

@lucychiu damn, you tell me the patch of @jamorham working only with the original oreo rom?

**Comment by lucychiu** [comment]
@lostboy86 I looked back at my comment 7 days ago. All the patches (A, B, BT, Demigod 1 and 2) failed for me using the Oreo rom. However you mentioned all the patches apart from demigod 1 and 2 worked for you, so there must be something different with that oreo rom.

**Comment by lostboy86** [comment]
Yes, for me with latest kernel, a,b,bt ok. Demigod 1 and 2 not apply. With Oreo roms xda modified for long battery etc.

**Comment by izywizy** [comment]
I have a problem since applying this mod, default apps on the watch will not update, the error message is 'not enough space to update apps'

Now this is not the case as the only apps on the watch are the default apps and xdrip !

Anyone else seeing this or can offer a solution ?

**Comment by izywizy** [comment]
@ralf-ms, thanks very much, never thought of that so it's likely the problem.
Wear on phone is showing 2.20GB used/2.42GB total.

and thanks for the detailed instructions which I will carry out when I've finished setting up my new PC.

I'll report back when I've done it :)

**Comment by lucychiu** [comment]
Today I used 'Use Only Wear' mode on. In the past 14 hours, battery started
at 90% and went down to 15%.
At the 10.5 hour mark it lost connection for 30 mins (battery under 40%
from memory), it aggressively restarting collector a few times before I
decided to restart the whole watch. It automatically connected again upon
reboot.

It did lose connection a few times during the day, but the major one was 30
mins and I wasn't patient enough to wait for it to reconnect.

**Comment by lostboy86** [comment]
@lucychiu Lose connection with MiaoMiao you mean? Only Wear mode means smartphone bluetooth off / without smartphone, and xdrip on watch 2 read directly from miaomiao+libre with bluetooth?

**Comment by lostboy86** [comment]
@lucychiu ah dexcom, not miaomiao.

**Comment by izywizy** [comment]
@ralf-ms, finally finished setting up my new PC so had some time to sort out the watch.

Thanks again for the instructions, worked for me and apps now updated :)

**Before**
`/dev/block/mmcblk0p35 2.2G  1.9G  242M  90% /data`

**After**
`/dev/block/mmcblk0p35 2.2G  557M  1.6G  25% /data`

**Comment by ralf-ms** [comment]
@izywizy, nice to hear!

@all: so far I'm very pleased and satisfied with jon's patch and bluetooth solution.
I'm using mainly the 'force wear collection ' settings but have also tried the 'connect to watch if phone is out of reach'.
Switching between phone and watch was without any issues, had to wait 10min at most.
Thanks again, Jon, for you quick and functional solution!

**Comment by lucychiu** [comment]
@All, battery seems to have improved slightly after a few days with the
watch in 'Only Use Wear' mode, getting an extra hour or two... Not sure why.
I have also tried out @izywizy advise to turn off the always on display
today. Started at 100% and after 6.5 hours, it is at 72% and no connection
issues at all. Thanks @izywizy.
This has been amazing not having to carry the phone around. Thanks so much @
JamOrHam.

--
Lucinda Chiu
Phone: 021 252 0891
Email: zhaojielan@gmail.com

**Comment by borijess** [comment]
I applied the patches on my Huawei watch sport 2. It worked over night at a high capture rate. 94 percent. Once I woke up I started to miss data. In the debug settings I added the scan constantly option. Is anyone else having these issues?

**Comment by mileom85** [comment]
I have finally applied patch everything went ok. I was planning to use watch when smartphone is not in range. Yesterday I have managed to connect to watch. Then I have switched to smartphone and haven't managed to connect to watch anymore. I don't get it. I force Wear collection and it can't connect. Did anybody else have this problems?

**Comment by lucychiu** [comment]
Have you tried rebooting the watch?
Also in the watch pref settings under xdrip G5, is force screen always on
checked?

**Comment by borijess** [comment]
I patched my watch and I still get a lot of missed readings. It works for a while an then it missings readings for 10 to 20 minutes. What are your readings besides authenticate before each reading?

**Comment by lucychiu** [comment]
I only have force screen always on and auth G5/read checked in the settings.

**Comment by borijess** [comment]
Does force screen on kill battery? And does it keep the screen on all the time? What is your capture rate?

**Comment by lucychiu** [comment]
Yes, it does kill the battery. The workaround is to Force Screen on Xdrip
Prefs settings and on the watch's main display settings, disable always on
display. That way you will get a full day of battery. Capture rate 90-95%.

**Comment by borijess** [comment]
How do u turn off screen? Does it shut off automatically?

**Comment by lucychiu** [comment]
Go to: ​Settings - Display - Always-on screen​.
The screen shuts off automatically in 5 seconds...

**Comment by borijess** [comment]
How long does your battery lasts on average?

**Comment by lucychiu** [comment]
With force screen always on, I had to charge twice a day.
With force screen off, I charge once a day, but my guess it will last 1-1.5
days depending on the watch usage.

**Comment by mileom85** [comment]
@lucychiu I have tried to reboot watch multiple times. It still can't connect. All patches have been installed without errors. I don't get it. I don't have force screen always on in xDrip+ prefs, but Always on screen is turned on in Settings.

**Comment by lucychiu** [comment]
"I don't have force screen always on in xDrip+ prefs, but Always on screen
is turned on in Settings.."

Do the opposite.. force screen on in xdrip prefs. Always on turned off in
settings.

**Comment by mileom85** [comment]
@lucychiu I don't have that option in xDrip+ prefs. I don't understand why.

**Comment by borijess** [comment]
Why if the patch was applied to the Huawei do we still need to select force screen on in settings on watch. On the polar M600 I did not have to chose that option after I applied the patch.

**Comment by lucychiu** [comment]
You've selected xdrip prefs - xdrip G5 settings - force screen?
Otherwise then I'm not sure. My xdrip build from my phone is 14 June too.

@borijess I don't know. It's just something I read on Facebook in the xdrip
group when someone else downloaded the patch and couldn't get it working.
This is what they had to do and it solved it for me when I took a few weeks
break and then I couldn't connect to the transmitter anymore.

>

**Comment by borijess** [comment]
Can you post link to the facebook conversation of this app?

**Comment by lucychiu** [comment]
I'll try and find the post...

Otherwise this section in the watch guide can shed light as to why you
didn't need it for the Polar.

There are the following two, known exceptions:

   -

   Force Screen On - Some watches, such as the Moto 360 2nd Gen, fall into
   deep sleep preventing the BT Collector from retrieving the transmitter
   data. Enabling this preference will trigger the watch to wakeup to read the
   transmitter data, then fall back to sleep. This preference is
   experimental but may be helpful for watches that do not support the
Always-on
   screen feature.


https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/WatchGuide.md#xdrip-bt-settings

**Comment by borijess** [comment]
I found the link on xdrip. Thanks for the info.

**Comment by borijess** [comment]
Are you able to input treatment from watch? I can not. Dont know if I am missing a setting.

**Comment by Isaksen** [comment]
Question: Buying a new watch within a day or two?
Is Huawei SmartWatch 2 4G working now? (looking for non phone solution for school/sports days)

New to all this. Daugther with MiaoMiao - Android phone. Working well
Coder background, so hope to contribute in the future

**Comment by tboyd91** [comment]
Hi everyone, I am struggling to successfully install the patches provided by jamorham and I hope that someone can help me fix my problem. So far I have installed the update patch and security patch; demi God mode was enabled but the BT patch was unsuccessful. I followed the instructions provided in the care package and I have no clue where I went wrong. What would cause the BT patch to fail?

**Comment by jserajlic** [comment]
Hi, I have huawei watch 2, build OWDE.180926.001.A1, is there any solution to set it as collector.
tnx

**Comment by jserajlic** [comment]
Solved,
flashed with android_kernel_huawei_sawshark-oreo-wear-dr
and 
OWDE.180215.017_LEO-DLXX_Stock
patched with this instructions
bluetooth patched

ERROR with demigod mode
ERROR with demigod-2 mode

for now working fine

**Comment by lmiekus** [comment]
@jserajlic If you are still looking for the original stock roms OWDE.180215.017 you can find here
 https://drive.google.com/file/d/1TwtOBmz-01a2EjLFdFnbGi8pqOGEeOCa/view . Use img files from sawshark.zip and fastboot to flash your watch:
fastboot flash boot boot.img
fastboot flash system system.img
fastboot flash recovery recovery.img
After that apply fix-boot-security.zip and huawei-watch-2-4g-demi-update-patch. I have used twrp provided by jamorham. Both operations are successful. 


> Solved,
> flashed with android_kernel_huawei_sawshark-oreo-wear-dr
> and
> OWDE.180215.017_LEO-DLXX_Stock
> patched with this instructions
> bluetooth patched
> 
> ERROR with demigod mode
> ERROR with demigod-2 mode
> 
> for now working fine

**Comment by jserajlic** [comment]
fantastic, tnx my man

**Comment by Garweho** [comment]
Hi everyone,
since a week I'm using a Huawai 2 watch as stand-allone collector. Just out of the box. Without patching the watch! I have follwowing Build: OWDE.180926.001.A1 / Modell: LEO-DLXX
My phone is an old Huawai Y625.
I tried it several times and finally found I had to turn off the automatic update in Playstore immy after setup and then also cut Wear OS from Internet in phone settings. I'm not sure if this is really necessary, but when I tried first, the collector stopped working soon after I turned on wifi on the phone. And didn't restart collecting, even after rebooting the watch or/and phone. But when I do factory reset on the watch, it works right after installing xdrip on the watch.

**Comment by lee-b** [comment]
Worked for me with Glimp, but not Xdrip.

**Comment by psvtg** [comment]
Guys, please help me! I have Dexcom G6, Xiaomi Redmi 6a and Huawei Watch 2 LTE with Demigod running xDrip+ v.20190518. When I make my HW2 as the collector it can't send data to my Redmi and so my Redmi can't send data to NightScout (my Heroku website) and Dexcom Share. HW2 only collects the data itself. Is there any way to fix this issue? It's needed for the kid to go school with only the HW2 and parents could get the data from HW2 from home following the Nightscout (website or xDrip follower)  on their phones.

**Comment by jserajlic** [comment]
Did you try over wifi connection. If wifi is ok then you need to check your apn setings.

**Comment by william-so** [comment]
I have the same issue as @psvtg. However my setup is W2 LTE, Sony X Performance phone. W2 does not work as collector in either mode for me. 'Only' mode or 'Not phone nearby' mode. Doesn't matter if it's on WiFi or 4g.

**Comment by psvtg** [comment]
> Did you try over wifi connection. If wifi is ok then you need to check your apn setings.

I tryed that with wifi and with LTE. No difference. On my System Status page in Redmi's xDrip is automatically set 'Phone Service State: Service Stopped' when I activate Force Wear Collection Service so I think the xDrip app blocks all smartphone acttivity including recieving data from smartwatch and the smartwatch doesn't know how to push the data straight to Nightscout or Dexcom Share.

I installed web browser on my HW2 and it runs normally by wifi and LTE.

Is it possible that this issue is because of the developers' code? Or anybody's got this scheme workable?

**Comment by lmiekus** [comment]
Make sure that both enable and force are checked under android wear integration. Additionaly be sure that treatments events are not recorded in xdrip - this is causing communication problems betwean smartwatch and phone. We are useing Huawei SW2 LTE with Samsung S9 for last 3 months without any problems. Good luck

**Comment by william-so** [comment]
@lmiekus can you elaborate 'be sure that treatments events are not...' with a screenshot?

**Comment by psvtg** [comment]
@lmiekus What version of xDrip are you using?

**Comment by lmiekus** [comment]
I don't have access to computer now but these are carbs or insulin entries that you can do in xdrip on your phone. For some reason they cause communication problems betwean Phone and smartwatch. If this dosen't solve your problem, try last avalible version of android wear insted of wear os.

**Comment by lmiekus** [comment]
We are useing xdrip from 13.04.2019

**Comment by psvtg** [comment]
@lmiekus It seems your vesion from 13.04.2019 works fine! And the new versions don't have access to Wear API. Thousands hugs!

**Comment by mbickelhaupt** [comment]
> @jserajlic If you are still looking for the original stock roms OWDE.180215.017 you can find here
> https://drive.google.com/file/d/1TwtOBmz-01a2EjLFdFnbGi8pqOGEeOCa/view . Use img files from sawshark.zip and fastboot to flash your watch:
> fastboot flash boot boot.img
> fastboot flash system system.img
> fastboot flash recovery recovery.img
> After that apply fix-boot-security.zip and huawei-watch-2-4g-demi-update-patch. I have used twrp provided by jamorham. Both operations are successful.
> 
> > Solved,
> > flashed with android_kernel_huawei_sawshark-oreo-wear-dr
> > and
> > OWDE.180215.017_LEO-DLXX_Stock
> > patched with this instructions
> > bluetooth patched
> > ERROR with demigod mode
> > ERROR with demigod-2 mode
> > for now working fi0ne

I have the OWDD.180926.001.A1 (Classic Watch 2 non-LTE) I am struggling to successfully patch it and get demigod mode up and running. 
I have tried flashing directly with the "update patch" and "fix boot security" with error messages
I have also tried flashing the sawfish ROM from your previous post, created by JanJan, so now my version is  OWDD.180926.001.A1-9 Feb-JanJan, and still no luck. Any advice on what to do with this non-LTE version of the classic?

Also, I have a huawei watch sport 2 (non-LTE) that I was able to flash successfully and theoretically works however the mounts for the strap are broken and not repairable. I tried to make and use a recovery from the watch to flash onto this new classic to no avail. I'm not very talented at this stuff so there may be a way to use this old watches recovery that I do not know of.

Thanks for the help

**Comment by greenninjas** [comment]
@jamorham any chance for you to rebase patches against 4G version Build number OWDE.180926.001.A1 ?

Thanks!

**Comment by wisefolks** [comment]
> Solved,
> flashed with android_kernel_huawei_sawshark-oreo-wear-dr
> and
> OWDE.180215.017_LEO-DLXX_Stock
> patched with this instructions
> bluetooth patched
> 
> ERROR with demigod mode
> ERROR with demigod-2 mode
> 
> for now working fine

I also have huawei watch 2, build OWDE.180926.001.A1 and I would appreciate it if you could tell me how to Fash it to collector.

https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5
I referred to the above address but it was not applicable for the build number of OWDE.180215.017.

If you know how to Fash as a Collector with build OWDE.180926.001.A1, I would appreciate your help.

My e-mail address is imshawnroh@gmail.com.

**Comment by mustang011** [comment]
I was flashing heawei watch 2 4G to old firmware (original stock roms OWDE.180215.017). I applied patches. MiaoMiao 2 Reader does not work with this watch (xdrip nightly 2019.10.27). In addition, battery life has been reduced by half. I'm going back to the latest firmware and waiting for the patch update for the new firmware (OWDE.180926.001.A1).

**Comment by jonathanmmm** [comment]
@jamorham 
Is it possible to Patch a Oppo Watch 41mm (in EU)?
I don't have it right now, but consider it as a collector (without phone, phone can be used in the beginning) with xdrip/Libre 2/oop with the help of MM1/MM2/Bubble (don't know which right now).
Is a patch actually necessary, as I read in the watch guide that they would then show data every 10 minutes, instead of 5 minutes.

If it is possible, I would help and send the details about the watch, when it arrives. Hope it is possible :)

**Comment by tolot27** [comment]
@jonathanmmm Please ask at the support forums. This issue is related to the Huawei Smartwatch. There are so many WearOS watches available that nobody knows if it works or not. If the WearOS is a recent one, it is likely that it works.

**Comment by old-square-eyes** [comment]
Hi all. I have an opportunity to buy a used Huawei Classic 2. Is this a viable collector solution still for Dexcom G6? I use a SWR50 and my life revolves around it's excellent collection.

I require...
- >=95% collection (forced Wear)
- Wear OS 2.0
- Happy to charge nightly if I can at leat get through the day.

**Comment by Navid200** [comment]
@avr248 
_yesss!!! it work!!
thank you very much!!_

Sounds like your request was addressed.
Can we close this issue then?
Thanks

**Comment by AliSaeed86** [comment]
Hi @Garweho, @Navid200, 
Kindly, can Huawei smartwatch GT 2-319  be used as a standalone collector?  
I tried too many times to set my Huawei SW GT 2 to collect Libre1 readings, but no use. There is no play store in the smartwatch to install xdripe+.

Please, help me. 
Note I am using MaioMaio1, Libre1, xdrip+ and Samsung mobile.

Thanks.

**Comment by Navid200** [comment]
@AliSaeed86 : https://github.com/NightscoutFoundation/xDrip/discussions/2286
