### ISSUE TITLE
Rest-Api - Nightscout data download not working

### ISSUE THREAD

**Issue by muehle28** [NightscoutFoundation/xDrip#403]
"Also try to download data from Nightscout" is activated, but no data from nightscout is beeing downloaded.

**Comment by Splitfox** [comment]
Is there already a solution, because I have the same Issue

**Comment by bobhavlin** [comment]
I too have this problem.  Treatments are downloaded from Nightscout and can be seen in Xdrip, but not BG data.  Thus, it does not appear to be a Nightscout configuration problem, but an Xdrip BG data processing/acceptance issue.  "Nightscout Sync (REST-API)" -> "Download data" is ON.  This is version d1d4887-2018.09.08.

**Comment by anfichtn** [comment]
I'll have a similar problem. Treatments get backfilled when I set the download to on, but cgm data keeps missing.

**Comment by ikniwn** [comment]
Did this get resolved?  I have the same issue - I can see treatments but no BG data.  I am using a Huawei p8 lite as a follower.  Base URL data is correct and Night Scout is receiving the uploads from the master.

**Comment by Navid200** [comment]
@psonnera

**Comment by psonnera** [comment]
I believe the menu item "Download data" should be renamed "Download treatments" or xDrip+ should accept incoming BG as it is and not bloodtest.

**Comment by Navid200** [comment]
xDrip cannot download BG readings from Nightscout.
You will need to transfer database from the old phone to the new phone.
I have opened a pull request to change the menu to avoid this confusion as suggested by Patrick.

I am closing this issue as the capability does not exist.

**Comment by jwoglom** [comment]
It strikes me as odd that xDrip, to my knowledge, doesn't support automatically downloading treatments (or CGM readings, although I don't have a direct need for that) on some periodic schedule from Nightscout. In my own workflow, I have pump treatments which upload directly to Nightscout via tconnectsync but unless I manually go into the xDrip settings and hit this download treatments button, they aren't ingested into xDrip. Ideally, whenever xDrip already uploads CGM data to Nightscout it could query to see whether there were new treatments to download and automatically ingest them to xDrip, if enabled by the user.

Automatically downloading treatments is a feature I was planning to build out for my own personal use, if it was implemented would others make use of it?

**Comment by tolot27** [comment]
I do not fully understand the use case. The Nightscout Follower data source is designed to fetch the data from NS, both BG readings and treatments as well as notes.
Now, you are requesting the same feature from Cloud Upload Agent "Nightscout Sync (REST-API)", aren't you?

What's then your primary data source?

**Comment by jwoglom** [comment]
@tolot27 Let me clarify. In my system, I have two parallel streams of data flow which are being funneled into Nightscout. xDrip on my phone grabs G6 sensor data and uploads it to Nightscout. Concurrently, I have a Tandem pump which has Tandem's own app running. This app automatically sends pump data (i.e. basal and bolus treatments) to Tandem's cloud system on a regular basis. I then have a tool, tconnectsync, which I wrote, that queries Tandem's cloud for new treatment data and puts that information into Nightscout, so that I can view bolus and basal data automatically in Nightscout. As a result, Nightscout now has combined CGM and pump data stored within it -- CGM data being uploaded via xDrip, pump data via tconnectsync. 

In my ideal world, xDrip downloads the treatment data which was placed into Nightscout by tconnectsync into its own local database, so that I can view bolus/basal data within the xDrip UI as well. xDrip would be smart enough to then know not to re-upload that data back to Nightscout, since it downloaded it from Nightscout, in the same way that it currently downloads treatment data which was created directly in Nightscout.

**Comment by tolot27** [comment]
> In my ideal world, xDrip downloads the treatment data which was placed into Nightscout by tconnectsync

Treatments should be downloaded, automatically. At least this works for my use case and treatment data entered via Nightscout. Please confirm that only treatments created directly in Nightscout are synced and not from other sources.

BTW: Did you see #1403? Maybe, we can work together on this PR.

**Comment by tolot27** [comment]
@Navid200 copied from #1770:

> That is interesting. If the follower can download past readings from Nightscout, the master should be able to do it too. But, it cannot. I'd like to know why. But, that is not related to this issue.

Because Nightscout Sync (REST-API) is just an uploader of BG values, despite its name, and Nightscout Follower just a downloader of BG values. Only treatments can be transferred bidirectionaly.

Maybe we should rewrite and merge both services into a unifying service with a true two-way sync of any kind of data and supporting v3 API (#1765).

**Comment by Navid200** [comment]
Does this mean if someone buys a new phone, they can first set it up as a follower of the Nightscout, and get all the history?
Or, does the follower download only one day or 12 hours or what?

**Comment by tolot27** [comment]
> Does this mean if someone buys a new phone, they can first set it up as a follower of the Nightscout, and get all the history?
> Or, does the follower download only one day or 12 hours or what?

That could be a workaround we can evaluate very easily using the Android Simulator. Currently, I don't know how many historical values can be fetched. I switched off my dev phone on some months ago and turned it on three days age, if I remember correctly. The data were fetched back till 7th, June. But NS follower was set up months ago and hence knows from previous data stored in the SQlite DB that there is a big gap. I'm unsure whether this works with a completely new phone without importing any backup.
