### ISSUE TITLE
Current xdrip watchfaces do not support sound

### ISSUE THREAD

**Issue by Cylon75** [NightscoutFoundation/xDrip#483]
A few AW2.0 watches have a speaker now and it would be nice that the speaker can be used for alerting like in the xdrip+ app. Most smartwatches have a weak vibration alert/notification which does not wake you up. Now a phone is still needed for sound alerts.

Could this be added?

**Comment by jamorham** [comment]
Please try the Aug 19th Nightly. You will need to make sure the latest wear app gets re-installed on your watch. Then you need to enable the on-watch notifications and the sound feature - both via xDrip preferences on the watch face. This may be fairly primitive at the moment and has not been properly tested, so please let me know if it works. Thanks.

**Comment by Cylon75** [comment]
I have tested for a short time and the high and low alert seems to work. A loud horn beep sounds when either threshold is passed. Xdrip does seem to be more slow/unresponsive now at times. I have the same problem regarding the slowness when updating to the latest nightlies. The wear app is not updating automatically but it tries to do it.  The error logs says Unknown channel: updated apk. It never really finishes and keeps trying. When I update the wear app manually it works faster again. But overall the Aug 19th nightly seems a little bit slower than previous versions but my phone is already very old. So it could be that. It needs replacing badly which will be soon.

It looks like only the low and high alert is working, but I am not sure if that are only the intended alerts to be working in this first version but I assume so. Other alerts like the prediction alert is not working. Also the alert sound does not repeat until snoozed. 

But this is already a great start :) 

Thanks,  very much appreciated that you are working on this.

**Comment by Navid200** [comment]
@Cylon75 Would you please update how xDrip behaves now in that respect?

**Comment by Cylon75** [comment]
I am no longer using my watch as a collector. The watch battery is depleted quickly now and will be replaced soon. I replaced my phone some time ago with a Xiaomi Mi mix 3 which works great and have a backup phone now. I don't think there were any improvements to what I described that the high and low alerts worked but nothing else.

Thanks for this. Should I close this issue?

**Comment by Navid200** [comment]
Thanks for your response.
I can close it too.  
I am just going over all the issues trying to figure out what the status is and allow the person who opened it to respond.  I don't just close an issue.
We would like to have an issue open if it is a request for a new feature, which then will be discussed and may still be closed if there is a reasonable work-around.  Or, if it is a bug meaning an issue with xDrip that needs to be fixed.  
There are some existing issues that re really just questions about how one can accomplish something using xDrip.  There are two support channels available for the users to access for that kind of question.
There are of course some overlaps between these categories.  

The hope is that we can clean up the list of open issues so that when developers look at it, they can see what needs their attention as opposed to finding lots of questions that can be answered by other users, or requests for something that only benefits one person, or objectives that can already be accomplished with the existing code using a work-around.  

I am not suggesting that your issue is in any of these categories.  I am just explaining what I am doing.

I close this.  If you disagree, we can open it.  
Thanks for getting back to me.
