### ISSUE TITLE
Variable spoken-values time is awesome, but...

### ISSUE THREAD

**Issue by dave1812** [NightscoutFoundation/xDrip#484]
The varied time for spoken values is AWESOME (thank you!!), but can you please change the rate of change minimum from 4 to 2, as 4 is too large of a rate of change. Most CGM software is coded to allow for either 2 or 3 mg/dl/m. I always choose 2 to get alerted more quickly.

(I posted this also under the original thread, but since it was marked "closed", I figure I should submit a New Issue here.)

**Comment by jamorham** [comment]
Can you describe in more detail the usage pattern of some example glucose values over time periods where you would see this being a problem?

**Comment by dave1812** [comment]
Sure, every CGM system has a rate of change warning built into it that uses
a choice of 2 or 3 mg per deciliter per minute to warn the patient of
impending highs or lows even if they don't indicate that one will hit a
high or low ceiling necessarily. It's a very useful utility and you
included it when you included the feature that I asked for for the spoken
glucose values being given at a variable time but the portion that you
added for the rate of change starts at 4. What I'm saying is it really
should start at 2

**Comment by dave1812** [comment]
Follow up to my previous email of a moment ago. It's in addition to the
arrows that show straight up straight down or angled up and go down. It's
designed to give an audible signal such as you have for the glucose
readings giving every 5 minutes originally and now that you modified the
app and given X number of minutes apart. An example would be someone is
very high such as 400 and they start dropping at 2 or 3 mg per minute that
would not indicate that they are going to necessarily crash to the low 40s
or 50s anytime soon but just the fact that they are dropping at that
particular rate kicks off the feature and CGM systems. I hope that helps

**Comment by jamorham** [comment]
Ok from what you have described I don't think you understand what the setting does. The speak readings glucose threshold is not based on rate of change, it is based on absolute value since the last spoken reading.

So if the value is set at 4 mg/dl and glucose is 120 at some point in the future if it reaches 116 or 124 then it will speak the new reading and then count from there, so either 120 or 128 would trigger the next spoken reading in this example. In mmol this is about 0.2mmol change.

Please test this if you would like to confirm the operation.

**Comment by dave1812** [comment]
Oh okay I understand what you are saying. I didn't understand it from the
description on the screen. I will check that it does just as you say which
I'm sure it will. Thanks for the quick instructions

**Comment by jamorham** [comment]
If you can think of improved wording which will fit in to the space feel free to suggest it.

**Comment by dave1812** [comment]
Given that I now  understand the function, I can't think of better/succinct verbiage.  (other than add a forward slash between "mg" and "dl")

One thing to note is that when I had it set to 4 mg/dl, my next reading had a delta of 3.7 and no voice (as expected).  However, the next delta was .7 and that triggered the voice.   Can you check on the coding to see if that is precisely what you intended to happen?

**Comment by doc77** [comment]
I've been watching this. How about an option to have speech fire every time a new glucose reading is recorded (every 5 mins.)?  Or better yet having the glucose being read every two minutes?  I use speech when in my car through the Sync head, and every two minutes would be perfect.

Along those same lines, could xDrip+ be made a compatible Ford Sync app so that it could be displayed on the Sync screen?

**Comment by jamorham** [comment]
@doc77 you can already have it speak every reading, just reduce the minimum minutes right to the lowest value which will result in every reading being spoken. 

Personally as far as use in a vehicle goes, I believe it is better to only speak when there is a significant change to the glucose value because I don't see the point in hearing very similar numbers and the mental burden of having to think about how much sugar has risen or fallen seems to be to be a potential for distraction while driving. If you are worried about not hearing the reading the first time you can enable it to speak twice and also adjust the speech speed to speak more slowly.

**Comment by sashasochka** [comment]
"or per number of minutes" is indeed confusing, I think I understand it correctly now but still not sure. If I have when changes by .7mmol and per number of minutes 10, does it mean that it will speak when in every 10-min window the change is >0.7mmol?
