### ISSUE TITLE
How to enable OOP calibration?

### ISSUE THREAD

**Issue by IgnisAsphodel** [NightscoutFoundation/xDrip#525]
Hi!

I have libre+bluecon+xDrip, many thanks to developers!
Unfortunatelly, I can't figure out how to enable OOP calibration - it's always grayed. 

![dexdrip](https://user-images.githubusercontent.com/36475784/43186422-4892d6c8-8ff7-11e8-9487-d1437568e207.jpg)

Is there any step-by-step instruction to enable this feature?

**Comment by dabear** [comment]
No. This is not supported. It's a pre-alpha feature that has some serious drawbacks if enabled.

**Comment by IgnisAsphodel** [comment]
Got it, thanks.

**Comment by akadismas** [comment]
Hi! I would ask one more time to enable the checkbox "OOP algorithm calibration". Using OOP algorithm is the only way, I succeeded to connect xDrip+, Miaomiao2 & Libre2 with. But BG values without calibration turned out systematically far from a glucose meter. As a workaround, I could toggle this checkbox by saving xDrip+ settings to XML, editing the value of option "calibrate_external_libre_algorithm" from "false" to "true" and loading the settings back. When I've done a calibration after this, BG values became perfectly close to glucose meter's ones. Why don't leave the decision to use OOP calibration to user with appropriate precautions, if necessary?

**Comment by Navid200** [comment]
@akadismas 
Would you please have a look at this?  https://github.com/NightscoutFoundation/xDrip/issues/1390#issuecomment-894267223
I don't think this is possible and I don't think it is going to change.
