### ISSUE TITLE
"Insufficient calibration" status for G5 native leads to no readings in xDrip

### ISSUE THREAD

**Issue by yeagerm** [NightscoutFoundation/xDrip#537]
During the night the alert for calibrating the sensor on the Dexcom receiver popped up, and the receiver continues to collect readings. The latest Aug 5 nightly for xDrip however stopped collecting readings. There was no alert on the Home screen that a calibration was needed. Only on the System status page "OB1 G5/G6 Collector and Transmitter Status" was there an alert for "insufficient calibration".

**Comment by jamorham** [comment]
Thanks this is useful information to be able to compare states with the receiver.

**Comment by jweismann** [comment]
I saw a similar thing - when there was a large difference between the BG measurement and the sensor value it refused to take the calibration and no values showed up despite the fact the it got readings (I saw the filtered/unfiltered numbers in the log but nothing was show). After 30 minutes or so I did another calibration and this time it was accepted and values started to appear in xdrip again.  If it is intentional not to show the numbers then maybe it would be a good idea to hint the user that another calibration is required before values will show again. Thanks for a great app.

**Comment by jamorham** [comment]
Can you enable the Advanced G5 setting for `Go on without calibrations` which I think will then allow this. If the receiver allows it then I guess I should make that default to being on.

**Comment by nan4kam** [comment]
Will do - thanks for the suggestion. I will report back if I see the issue again.

**Comment by jamorham** [comment]
Marking as resolved.
