### ISSUE TITLE
xDrip randomly opens

### ISSUE THREAD

**Issue by catslover32** [NightscoutFoundation/xDrip#54]
Often when in a different app, xDrip will open over the current app. I have yet to discover what is causing this and I'm wondering if it's a bug related to android 7.1.1. <-- I am using the Nexus 6P. Is anyone else having the same issues?

**Comment by jamorham** [comment]
Can you use the `System Status` menu item and let me know the version code you are using? (The top line of the `Version:` section)

Thanks

**Comment by hawsepipe** [comment]
Also happening on my Nexus 5X (7.1.1)

![screenshot_20170106-105029](https://cloud.githubusercontent.com/assets/23440432/21723412/4e9b5312-d3fe-11e6-8cf8-1df9b346e568.png)

**Comment by jamorham** [comment]
Ok, if you are experiencing this issue and you are NOT using any of the master/follower features, then as a work-around, go in to `xDrip+ Sync Settings` and enable the checkbox: `Disable all sync features`

Please let me know if that resolves it.

**Comment by catslover32** [comment]
Will disabling sync break nightscout?

**Comment by jamorham** [comment]
No, it refers to the phone to phone syncing.

**Comment by jamorham** [comment]
The latest nightly should resolve this issue I think, but as I can't reproduce it myself I don't have any way to easily test it. 

If you're on the Nightly update channel you can use Check for Update via the 3 dot menu or download it here:

https://github.com/NightscoutFoundation/xDrip/releases/download/2017.01.10/xDrip-plus-20170110-0077e30.apk

If you previously used the disable all sync features preference option, unchecking that and then let me know if this version ever misbehaves in the same way.

I've restructured how sync works in this version. Local testing shows that everything apparently still works but I would appreciate wider testing due to the variety of phones and issues that can bring. Thanks.

**Comment by catslover32** [comment]
Hmmm. I updated to the nightly yesterday and had no issues. However, it
just happened...

**Comment by jamorham** [comment]
Can you use the `System Status` navigation menu item and just confirm that you are running the version from 10th Janurary (or later) thanks

**Comment by catslover32** [comment]
It is from January 10th. I'll keep an eye on it as it has only happened
once on the new build
