### ISSUE TITLE
LibreOOPAlgorithm on pre-release multiple readings at same time in the graph

### ISSUE THREAD

**Issue by andreascarsetto** [NightscoutFoundation/xDrip#552]
On August 9th I builded the last available version.
When using the LibreOOPAlgorithm.apk in the graph it seems there are more readings for the same period of time and the app tell that readings are very noisy

![screenshot_20180817-153544](https://user-images.githubusercontent.com/16019002/44269986-661e5e00-a236-11e8-9c7c-2055bb54941b.png)

I tried both the "original" version of the algorithm where I see 5 readings on a single column and the "modified" version where I find three readings on a single column (which is the one used in the screenshot)

If I return to use the last releaase of May 30 (F20d8da9), with the same settings and LibreOOPAlgorithm.apk this does not happen.
If instead of the OOPAlgorithm the calibrations with the capillary are used, everything works correctly

**Comment by tzachi-dar** [comment]
Hi,

This is kind of by design.
xDrip has a fuzzer of 3 minutes, which means it has a resolution of 3 minutes.
Since libre has a new reading every minute there are 3 points at every minutes.

There are two things that you can do:
1) To turn this feature altogether: go to settings->xdrip display settings->show libre trend and disable it.
2) On the right menu you can choose, show libre trend and then you will have a per minute graph.

@jamorham should we change the fuzzer to one minute? Or, should I give one point of average for all points?

Tzachi
