### ISSUE TITLE
xDrip not prompting for calibration using Bluetooth meter

### ISSUE THREAD

**Issue by wormstein** [NightscoutFoundation/xDrip#603]
Hi,
I am using xDrip latest version on beta channel
 I also use a contour Next one meter linked via Bluetooth

I never get the prompt to use reading for calibration although I have this enabled in settings. I also can see in event log that xDrip is trying to protect but nothing appears.

Any adbive?

Thanks.

**Comment by viq** [comment]
I have contour next one, and I have `use meter for calibrations` *unchecked*, and `automatic calibration` *checked*. This way, most of the time, I can just measure and xdrip does "the right thing" (calibrates or not depending on circumstances).

I'm keeping the sound indicators on, because sometimes it fails to connect and start getting the data, in such a situation I go the "Glucose meters" settings and disable and re-enable the setting, and then it syncs just fine.

**Comment by jamorham** [comment]
I believe the reported issue is that when using native mode with G5/G6 synced blood tests are always sent to the transmitter regardless of your automatic calibration settings.

This is a bug if you believe that the native algorithm isn't perfect and shouldn't be advised of all and any accurate blood test data being provided by the meter. Regardless, it is an issue of user choice and so the plan will be to change this so that the native algorithm support better respects the settings for this and behaves more similarly to the non-native algorithm.

**Comment by Navid200** [comment]
@wormstein Would you please close this issue if it has already been addressed?
Thanks
