### ISSUE TITLE
The 9/29 version still doesn't work with Android Notifications to a Tizen watch

### ISSUE THREAD

**Issue by dave1812** [NightscoutFoundation/xDrip#607]
Wow, this problem has been going on with every version I've tried (at least 4 versions) since sometime after the 7/15 version.  Can someone please get the Android Notifications working again so that my Gear 2 watch will display CGM readings every 5 minutes (no app needed for this to work).   Pretty please??

Without this getting fixed, I'll never be able to update from the 7/15 version.

**Comment by dave1812** [comment]
I must have bad breath or something.  It seems as this issue isn't deemed sufficiently bad to warrant a fix.  What a shame I can't update the app, or I'll end up with one of  the most useful features rendered inoperative.

**Comment by MasterPlexus** [comment]
@dave1812 , it makes no sense to open other issues due to the same problem (this here is not a Forum). It is important to keep the information's together to the issue for one Entry by person. Please close this current entry (607), and go ahead on the older one, where I write some things, thanks.

This issue related to #547

**Comment by dave1812** [comment]
understood.
