### ISSUE TITLE
Use correct audio channel for alarms and let the user choose the specific volume for it

### ISSUE THREAD

**Issue by quizzmaster** [NightscoutFoundation/xDrip#620]
Currently, xDrip uses the media channel for its alarms causing all other audio sources like Spotify, Youtube, etc. to get extremely loud if an alarm gets off. Using the alarm channel would prevent this.

Also I really would like to set an individual volume for the alarm, because I normally prefer to use one between medium and high.

**Comment by GlennCoco** [comment]
I agree with this one, I was in the gym with my headphones on last week and the alarm went off mid lift and scared me half to death because the music went full noise.

**Comment by quizzmaster** [comment]
@jamorham Any thoughts about this?

**Comment by gregorybel** [comment]
do you want to do a PR?

**Comment by sjennison** [comment]
This is still an issue. I was using my device with headphones and the xdrip notification turned the volume up enough to cause my ears to ring. It was a very painful experience. I don't want to have to turn notifications off entirely but I also don't want hearing loss from a poorly-timed notification....

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/813

**Comment by Navid200** [comment]
Would you please try the ascending volume profile?

Settings -> Alarms and Alerts -> Glucose Alerts Settings ->Alert Volume Profile

**Comment by Navid200** [comment]
I am closing this for no response.
If you like to reopen, please explain exactly which alerts you are needing this for.
Also, please explain if you have tried the ascending volume profile.

**Comment by sjennison** [comment]
Does enabling ascending volume fix the underlying issue (abusing media channels for notification audio)?
Because if it does not, I don't see why using it would be relevant in any way - you wouldn't have the issue of "blowing out eardrums", but you're still changing people's volume for no good reason. If the purpose of using the media channel is to bypass silent mode, that's achievable through Android's settings without abusing media volumes.
