### ISSUE TITLE
G6 Battery Reporting

### ISSUE THREAD

**Issue by akacase** [NightscoutFoundation/xDrip#629]
Hi,

Been using `xDrip` for a long time, just transitioned to the G6 without any problems, except for during the warm-up phase I received a `Critical Low Battery` error and now am seeing this voltage/resistance reading:

![dex](https://user-images.githubusercontent.com/5959454/47027843-37d5d580-d136-11e8-8c08-b9d533daeaae.png)

I am receiving a replacement sensor, just wondering if there were any reports of this happening upon activating a new G6 sensor. I hadn't used the official G6 app to activate.

I'm on a Pixel 2 with the latest Android 9 security patch.

**Comment by gitanO0** [comment]
My experience with the new g6 batteries is in line with what you see in terms of the voltage and resistance numbers.  Others have seen similar values as well.  

Regarding the error... if you go into your settings at modify the "low battery" number from whatever the default is to something lower... I set mine to 260 some time ago for the g5 and it may have to come down to a new number as I learn more about how these g6 batteries behave.  The setting is in the g5/g6 debug settings area at the bottom, "Adjust battery warning level".

**Comment by akacase** [comment]
Thanks for the response @gitanO0! I've modified those values -- have your transmitters lasted as long? I assume we just need to edit some of the battery alerting features to account for the different battery characteristics of the G6? Unless the G6 I received is just faulty.

**Comment by jamorham** [comment]
The battery metrics for G6 are different. xDrip does normally automatically adjust for what we know about G6 so far. What would be helpful would be to build up some information about what a fresh battery level looks like and what it is at 90-100 days and what it is when the transmitter stops functioning correctly. Feel free to add such information to this issue..

**Comment by DunePlodder** [comment]
G6 transmitter day 107 (after resetting on day 96)
Voltage A:   300
Voltage B:   279
Resistance: 1287
Still working well.

**Comment by markuscgm** [comment]
G6 transmitter Day 1
Set Adjust battery warning level to  250
Voltage A: 297
Voltage B: 281
Resistanca: 956

**Comment by DigitalDan1** [comment]
Just wanted to share another G6 data point. Hope it’s useful:

Transmitter Days: 89
Voltage A: 302
Voltage B: 281
Resistance: 1294

Still working well.

**Comment by akacase** [comment]
Transmitter Days: 63
Voltage A: 299
Voltage B: 280
Resistance: 1154

**Comment by gitanO0** [comment]
Transmitter Days: 80
Voltage A: 299
Voltage B: 279
Resistance: 1243

**Comment by Gonzmdv** [comment]
Transmitter Days: 89
Voltage A: 299
Voltage B: 275
Resistance: 1456

Failing

**Comment by DigitalDan1** [comment]
Update on sensor details I posted here a couple of months ago...

Sensor Status: Sensor Failed 4
Transmitter Days: 151
Voltage A: 297
Voltage B: 260
Resistance: 2391

The sensor was 14 days old and missed readings for 20 mins or so here and there over a couple of days (as often happens with a sensor of that age). Then 12 hours of no readings at all and the last 6 hours showing “Sensor Failed 4” which I haven’t seen before. Also never seen Resistance above 2000 so decided to change sensor and transmitter.

Brand new transmitter (factory date 2018-11-08, SB date 2019-07-10):
Transmitter Days: 0
Voltage A: 296
Voltage B: 275
Resistance: 1246

**Comment by MUtley1966** [comment]
Transmitter Age:  89 days
Voltage A: 296
Voltage B:  269
Resistance:  1727

Voltage B and Resistance are both red highlighted.  System is a bit wonky.  I restarted a sensor about a week ago, and it has been working at about 90%.  But last night and today, the sensor failed.  So, I put in a new sensor, and I thought it failed too, but now am getting consistent readings (four so far).  I'll update tonight to see if it was just the warmup period for the sensor.

Just another data point....   ;)

**Comment by sirforce** [comment]
Transmitter Age: 128 days
Voltage A: 281
Voltage B: 251
Resistance: 2081  

seems to still be reliable overall - have to keep xdrip+ device close or it will miss readings but seems to pick back up without issue, wonder how long this will go...

**Comment by DunePlodder** [comment]
G6 transmitter day 171
Voltage A: 300
Voltage B: 274
Resistance: 1639
No problems

**Comment by Pentagit** [comment]
G6 transmitter day 60
Voltage A: 296
Voltage B: 276
Resistance: 1209
No problems as well

**Comment by analogmonster** [comment]
G6 transmitter day 69
Voltage A: 300
Voltage B: 279
Resistance: 1302
Today I have had a few missed readings.  Log shows Aggressively restarting collector service due to lack of reception

Phone is less than 1 meter from transmitter.  No faults before today.  After the reset it is now working fine with no missed readings.  From previous experience this will probably happen again in a few days and I will probably swap transmitters in about a week

**Comment by sirforce** [comment]
G6 Transmitter Day 144 / 144.5
Voltage A: 273
Voltage B: 236
Resistance: 2698

still working pretty well... knock on wood!  Have since transitioned to using Spike/Loop

**Comment by Gonzmdv** [comment]
Yesterday afternoon I received a  “Sensor Failed 4” message and "Try hard reset?" and I didn't receive a single glucose value for next 3 hours. As I had seen in this thread higher resistance values than mine at that point (1424), I decided to try a new sensor. I received a "Start session error", was asked for initial calibration after warm-up period, and received 3 glucose values. No more reading for next 18 hours. So  today I have started a new transmitter.

Battery values (Yesterday):                   Previous transmitter (Feb 26)
Days: 102                                              Days: 89
Voltage A: 299                                      Voltage A: 299
Voltage B: 276                                      Voltage B: 275
Resistance: 1424                                  Resistance: 1456

I would like to know why are there transmitters with much higher resistance values working...
By the way, I haven't changed the mobile or the watch in the meantime.

If someone is changing the transmitter I would like to remind them (because I forgot) that you should unpair the old tansmiter in the watch and the mobile, place a new sensor and insert the new transmitter, pair it, and then start the new sensor session.
The Bluetooth name of the transmitter will be Dexcom+ the last two characters of the transmitter ID.

**Comment by kiddostyle** [comment]
I used my G6 Transmitter since Dec 2018. Total of 7.5 months
Last few weeks I've got periods of minutes without signal although phone was very close to me (2-3m)
Picked up back values easily
Most recent 3 sensors lasted on average 20 days

G6 Transmitter total Days used 210 (2 resets)
Before change:
Voltage A: 287
Voltage B: 241
Resistance: 3190
Temp 34 C

**Comment by Ubik1969** [comment]
Hi i just started using my G6 system (First time dexcom user) bought directly from Dexcom UK as part of their introductory offer with 1 transmitter 3 sensors I'm using the latest nightly build of xdrip on my S10+. from reading this thread my resistance seems astronomical at:8705 with voltage A 309 voltage B 291.......... Anyone got any tips or advice please?

**Comment by SLYDoggie** [comment]
Is "Voltage A" the original starting voltage of the transmitter and "Voltage B" the current voltage? I can't find anything that describes this. Also, I'm assuming from reading this post that the resistance goes up over time. Is it usually the resistance or the voltage that eventually causes the death if the transmitter?

**Comment by 1981mama** [comment]
Day 169
Voltage A 293
Voltage B 260
Resistance 2157 (varies between 2147-2183 today)

Functions fine.
Serial number starts with 80

**Comment by savek-cc** [comment]
Transmitter Days ~190 (not sure, when I restarted the first time)
Voltage A: 291
Voltage B: 260
Resistance: 1969

Just started giving errors one hour ago - but sensor also needs replacement; Sensor Status is now "Stopped", Transmitter Serial starts with 80; BT connection doesn't seem to be a problem - it's connecting every 5 minutes; no signal dropouts seen before this.
Did another hard reset (as xdrip was suggesting) - sensor status is still "stopped" (but that's probably due to the failing sensor).

**Comment by wagnefrede** [comment]
Transmitter fresh paired 2 hours ago S/N: 8Gxxx


Firmware Version:     2.18.2.88
Transmitterdays:       0/3
Voltage A:                 307
Voltage B:                 289
Resistance:                7168

The Transmitter works for the moment. BUT I´m not sure how long. Does anybody have an [idea](url
![Screenshot_20191004-211032_xDrip+](https://user-images.githubusercontent.com/45721291/66234943-39096500-e6ef-11e9-9f87-7d207efe6f27.jpg)
)
why the voltage and resistance are so big? it scares me a little bit.

**Comment by Gonzmdv** [comment]
I also recently started an 8Gxxx transmitter.
Even a higher resistance fresh value:
Voltage A: 307
Voltage B: 288
Resistance: 7680

Looks like it's the new standard for 8Gxxx transmitters.

**Comment by 1981mama** [comment]
![Screenshot_20191030-195435_xDrip+](https://user-images.githubusercontent.com/55202285/67900301-78976580-fb64-11e9-999f-d402f57ac37e.jpg)

My voltage A dropped below 282. It died after 218 days, of which mostly using the dexcom app...

**Comment by IntoxRRR** [comment]
no 1, **8G**xxx, firmware: 2.18.2.88

day 0:
A: 308, B: 289, Resistance: 7699

day 25:
A: 279, B: 256, R: 8473
_10 minutes after receiving these values, the transmitter died – after 3.5 weeks!_


no 2, **8H**xxx, firmware: 2.18.2.88

day 0:
A: 308, B: 286, R: 8704

**Comment by jamorham** [comment]
@IntoxRRR does your G6 status display the shelf life parameter? If not you may need to enable engineering mode. I'm curious what the shelf life values are for the transmitter as this indicates how long its battery has been running before you started to use it.

**Comment by IntoxRRR** [comment]
Now I'm curious too.
Since I hadn’t activated the mode for the dead one (8G) before, I can’t tell it anymore. Or is there a chance to still get it off the logs anywhere?
The new transmitter’s (8H) shelf life says 89/365.

**Comment by annbob** [comment]
Just wanted to add my stats for G6 Transmitter to the list...
day 12
Voltage A: 305
Voltage B:2 74
Resistance: 6155
Shelf Life: 40/365

**Comment by ailuirazal** [comment]
G6 Transmitter Day 125 / 125.8
Voltage A: 295
Voltage B: 249
Resistance: 3076
Transmitter ID: 81A***

Today it started to fail, xDrip app didn't get any readings for about 2 hours, then got 5 readings, disconnected again, another hour with no readings and now I've just got 4 readings. I suppose the transmitter battery are about to die.

**Comment by ailuirazal** [comment]
G6 Transmitter Days **125** / 125.8
Voltage A: 295
Voltage B: 249
Resistance: 3076
Transmitter ID: 81A***

Today it started to fail, xDrip app didn't get any readings for about 2 hours, then got 5 readings, disconnected again, another hour with no readings and now I've just got 4 readings. I suppose the transmitter battery are about to die.

**Comment by kameamea** [comment]
No. 1:
G6 81xxxx sensor Days 176 
Voltage A: 281
Voltage B: 239
Resistance: 3001
failed then

No. 2:
G6 81xxxx sensor Days 146
Voltage A: 291
Voltage B: 250
Resistance: 2738
failed then

No.3:
G6 8Gxxxx sensor Day 0
Voltage A: 295
Voltage B: 272
Resistance: 6912
Day 1:
Voltage A: 270
Voltage B: 246
Resistance: 7681
Shelf life: 233/365

**Comment by Ugitsisgv** [comment]
My Note 9 running on Android 10 gives me a 7+ scanning error and will not
connect to my G6. The transmitter is an 8Gxxx. Not certain how to proceed.
I normally use my SW3 as the collector. Thanks in advance for the help.
Much appreciated.

**Comment by Ugitsisgv** [comment]
Just went to the t:slim X2. My Note 9 is getting the BG reading until I
enable Force watch (Sony SmartWatch 3) then I get a reading on the pump
only. Could you give me some guidance? Thanks so much.

**Comment by tolot27** [comment]
Related to #1085.

**Comment by Navid200** [comment]
The resistance value reported for G6 transmitters whose serial number did not start with 80 or 81 was never correct.  Neither was the temperature.  The format Dexcom used to communicate was changed.  There is a pull request to correct xDrip to read the new format correctly.  In the meantime, both resistance and temperature have been removed from the recent releases of xDrip.  Hopefully, the pull request will be approved soon.

Voltage B is the best parameter to look at to judge how long your transmitter is going to last.  However, what is important is the trend rather than the absolute value.
If the voltage is on a downward trend, you will know that the battery will die soon and you may need to take action.

Please look at the following two figures.  They show Voltage B for two different transmitters (neither 80XXXX or 81XXXX).  Neither reached a downward trend before day 110.  
But, please note the difference in the absolute values.  
The voltage is measured by the chip itself.  So, the reference for the measurement varies from part to part.  Therefore, the accuracy is not perfect and you shouldn't compare the absolute values.

![Screenshot 2021-03-01 175428](https://user-images.githubusercontent.com/51497406/109570343-e1278700-7ab7-11eb-9ac3-0e88611a5415.png)
![Screenshot 2021-03-01 175449](https://user-images.githubusercontent.com/51497406/109570357-e5ec3b00-7ab7-11eb-8b57-d2c6f91790ef.png)

As this issue is neither related to an xDrip bug nor a feature request, I am going to close the issue.  Please use the support channels to consult with the user community including the developers.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

You can continue to add comments.  If you feel this should not be closed, please post and let us talk about it.  We can always reopen if needed.  However, issues should only be used for reporting an xDrip bug for requesting a new feature, which has no existing work-around.

**Comment by andrewsawesome** [comment]
This was a faulty transmitter, or at least my G6 reciever detected it as one: 

 Days: 31
Voltage A: 286
Voltage B: 264
Resistance: 9759

Xdrip correctly detected the critically low battery.
