### ISSUE TITLE
LG watch not working with xdrip since wear OS update

### ISSUE THREAD

**Issue by bferens** [NightscoutFoundation/xDrip#630]
The latest Wear OS update has broken the X Drip watch face. On the watch, the xdrip readings often lag, show missed readings when in fact the reading is not missed and at times the watch face appears disconnected from app. I am running the latest nightly on my Pixel 2 which has been consistently performing at 100 % capture rate. 
Please note that prior to the wear OS update all was working just fine.
The update is : Wear OS 2.1 ( Sep 28, 2018)

**Comment by dave1812** [comment]
Good luck.  I've asked for over a month for them to fix the program to work with Tizen watch's Android Notifications, since sometime after their 7/15 version, which works fine.  So now, I can't update xDrip to any of the newer versions, INCLUDING the so-called "stable" version.   When xDrip doesn't work with my Gear 2, it's so much less useful.  I dunno why they can't take a look at the code that broke that function.

**Comment by jamorham** [comment]
Which LG watch are you using and which xDrip+ version?

**Comment by bferens** [comment]
xDrip+ version =  Oct 15th nightly
LG watch = LG Watch Sport Unlocked GSM
--

**Comment by bferens** [comment]
oops, closed by accident

**Comment by bferens** [comment]
see issue 631
