### ISSUE TITLE
25 hour Main Screen

### ISSUE THREAD

**Issue by DunePlodder** [NightscoutFoundation/xDrip#650]
The main xDrip screen currently covers 24 hours, but I often want to look back at what I did at this time (or a little before) yesterday, to see what I did & how effective it was, or what I did wrong so I don't repeat it. Currently I use the history screen but a 25 hour screen might be a little more convenient?

**Comment by jamorham** [comment]
It is an interesting idea.

**Comment by Navid200** [comment]
I have been there.  Interesting idea.

**Comment by emp-00** [comment]
+1 --- enhancement highly appreciated --- 
I also posted this in #1273 (was closed due to duplicate with this issue)

**Comment by Navid200** [comment]
I'm going to close this for now.  We can always reopen a closed issue.  This is my thinking.

In order to decide what to do, a better approach may be to look at the percentile chart that shows an overlap of possibly the last 90 days.
I understand you may have changed a practice so dramatically recently that the past 90 days are not a valid representation.
You are not limited in using the percentile chart to 90 days.  You can also set it to the last 30 days or the past 7 days.

Please note that implementing this, which I almost di will have a negative consequence.
We currently have an issue with a very high reading causing the y axis to extend making the slopes to look wrong.  This lasts 24 hours.  Meaning you will have to put up with the wrong (visual) slopes for 24 hours before the y axis goes back to normal.
If we implement this feature, we will then have to wait 25 hours instead of 24 hours.
