### ISSUE TITLE
G6 sensor errors

### ISSUE THREAD

**Issue by QuadAlpha** [NightscoutFoundation/xDrip#674]
Getting G6 "sensor errors" and no BG results.  Reboot, restart sensor not working.

**Comment by jamorham** [comment]
Which xDrip version are you using?

**Comment by gitanO0** [comment]
I get this all the time.. thank god for the xdrip algo fallback option. Nothing u can do about that g6 cutting the feed and sending that sensor errors message. That seems to be a "feature" of the g6.

**Comment by gitanO0** [comment]
Oh you are referring to the reverting to native mode thing? Yeah that's odd. Happens to m too.

**Comment by Jaykeydj** [comment]
Note.. After toggling Bluetooth off and back in, restarting collector and restarting my phone a few times (to not success) I checked the 'fallback to xdrip' option and after a few minutes it kicked back in..

Went back into settings and it had unchecked (I imagine this is to do with being in native mode)

**Comment by IceRights** [comment]
I'm using version 1809080944 currently with a new sensor; I was using the
nightly build (11-02 I believe) when I had the issues.

Everything was fine for the first few days, then would start getting sensor
errors.  Fallback worked for a day, then total sensor failure after 7 days.

**Comment by Jaykeydj** [comment]
We're you using native mode at the time?

**Comment by Jaykeydj** [comment]
Might I add that after a night of no readings.. I entered enigerring mode and checked fallback to xdrip..


I have had readings all day since this step.. But I am still running in native mode.. 

Error message 'sesnosr failed in the collector status bar at the bottom. Of. My screen...

Don't want to switch sensor as I would like to try fault find this issue and I am down to my last sensor with my only transmitter being at around 75 days (hard reset via spike ios app a few days back)

**Comment by Navid200** [comment]
@QuadAlpha If the problem has been resolved, would you please close the issue?
Thanks

**Comment by Navid200** [comment]
Please consult with other users as well for questions about how to use xDrip.
Currently, the following options exist.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
