### ISSUE TITLE
Silence alarms with volume or power button press

### ISSUE THREAD

**Issue by gregtcm** [NightscoutFoundation/xDrip#73]
It would be great to silence/snooze the alarms with the press of either the volume buttons or the power button.  It would be the same as when silencing an incoming phone call.

Case:  I was caught in church this morning with my xDrip+ alarm going off and in a panic trying to turn it off.  Luckily, I remembered the snooze button on my Pebble, but the ability to silence/snooze from the volume or power buttons would be great!

**Comment by jamorham** [comment]
This is a very good idea in theory. But I don't know whether volume change events are easily available to us, especially as xDrip itself can be adjusting the system volume depending on the alarm profile.

I did some quick googling about using `setMediaButtonReceiver` and it isn't clear to me whether this will work when xDrip is in the background. Some more research would be needed to understand if this is viable. If we did implement it I'm not sure if it should be enabled by default in case someone has their phone in their bag or something as we don't want to accidentally cancel an alarm.

I myself also use the pebble snooze control button app!

**Comment by jamorham** [comment]
I have been unable to reliably intercept the volume buttons on the lock screen / screen off which is where I think you need them. 

I can intercept the undocumented volume change action, but this doesn't work because within xDrip we set the volume to the desired alarm level and so it trips itself and I'm not sure it would be possible to make this reliable on all handsets and it would require somewhat of kludge to even work at all.

I couldn't get the android media button receiver stuff to work but its not clear to me whether that even includes the volume buttons.

What I have been able to make work is silencing the alarm by pressing the volume buttons from the app home graph screen.. This isn't ideal but it does make it that bit easier to manage at 3am etc.

I will let you know when I've tested this enough to include it in a nightly release.

**Comment by jamorham** [comment]
You can now do this on the app home screen in the latest nightly release. 

As mentioned before I haven't found a reliable way to do this when the phone is locked or outside of the app.

**Comment by gregtcm** [comment]
Sorry, I haven't replied sooner!  I'm finally getting time today to catch
up on my email!

Thank you so much for looking into this!  I wish I knew more about the
Android platform to to help out with this.  I keep thinking in my spare
time I'll get to it! :)

If I come across anything helpful, I'll forward it on.  And for the time
being, I'll test this out and I'll also try to NOT leave my Pebble at home
and also not panic if it ever starts going off like that again and instead
calmly press the Pebble snooze button! :)

And, not related to this issue, but I just started looping with OpenAPS and
have just figured out how to keep Nightscout and xDrip in sync with
NSClient.  You all are doing amazing work!  Thanks for all of that.  I hope
to be able to contribute more and more to the effort as best I can.

Thanks again!

Greg

Thanks,

Greg Uhlenkott
The Computer Man
208-507-0845

**Comment by Navid200** [comment]
One option, to avoid disturbing everyone around you in case of an alert, is to use the ascending volume profile:
https://github.com/Navid200/xDrip/wiki/Ascending-Volume-Profile
