### ISSUE TITLE
Not possible to turn off persistent notification

### ISSUE THREAD

**Issue by tobiasknudsen** [NightscoutFoundation/xDrip#750]
I just updated xDrip+ a few days ago on my phone and it is not possible to turn off/remove the persistent notification. If I uncheck the "Run Collector in foreground" it disappears for a little while, but it comes back again. The data in the notification does not update correctly and shows old data, I don't know if it is related.

Phone: Honor 10
OS: EMUI 9/android 9
Version 14fecb8-2019.01.10

**Comment by davidofwatkins** [comment]
I'm also having this issue. I can reproduce the faulty notification consistently by doing the following:

1. In Settings > Less Common Settings > Other misc options, check and uncheck "Run Collector in foreground." This should remove the notification if present.
1. Force-quit the app.
1. Reopen the app. The notification will appear again.

I'm not sure what release caused this bug, but I'm only seeing it after upgrading from `d1d4887-2018.09.08`.

Phone: Pixel 3
OS: Android 9
Version: `14fecb8-2019.01.10`

**Comment by jamorham** [comment]
Without a persistent notification on Android 8 and above xDrip will be killed by Android.

To minimize this notification either just select to minimize it or not show it by long pressing on the notification or if it isn't that simple on your phone, go in to `Settings -> Glucose Alert Settings` and enable the notification channels checkboxes and then wait a few minutes and then you should be able to adjust just the notification channel for the ongoing notification.

This isn't enabled by default due to the inconsistent way manufacturers have implemented this which we're still working on trying to get a standardized best set of default settings.

**Comment by tobiasknudsen** [comment]
Great, that worked for me! Thanks for the response.

**Comment by javierfeliullagostera** [comment]
I have a problem again with persist notifications.
