### ISSUE TITLE
Contour Next One (any Bluetooth) - When reading is done, there is a lot of error messages, trying to duplicate already added data (from history) to NS

### ISSUE THREAD

**Issue by andyrozman** [NightscoutFoundation/xDrip#762]
When I make measurment with my Contour Next One whole history is read, and then xDrip tries to add each entry again into Nightscout (UploaderQueue). All entries, except last fail, because they are already in NS.

I propose following solution:
1. When history is read, and all entries are added to NS, xDrip should remember which entry was added last and to which device and store it in Shared Properties. 
2. Next time when reading is done, this saved value is retrieved, and if we are uploading with device that already has last entry set, them we ignore all entries before that (looking at the date).

**Comment by jjaone** [comment]
Hi, I know this is a bit unrelated to your question, but I just wanted to know are you connecting Xdrip to other BT devices than the Countour Meter?

We are having problems with a setup where Libre Sensor is connected to MM which is read via BT by Xdrip+ installed in Android 8 phone OnePlus 5T and everything works. But, when we try to connect Countour Next One via BT to Xdrip so that the bg readings would be send automatically to Xdrip it makes the MM disconnect from Xdrip? Why is that?

It seems that Xdrip can only be connected to one BT device at a time, or is this a limitation in the OnePlus 5T phone?

**Comment by andyrozman** [comment]
Definetly not the phone. My phone is maintaining connection to 3 devices: G6, Pebble and Combo pump and I have OT 5T, and then I also connect to Contour Next One when needed...

**Comment by jjaone** [comment]
Ok thanks, it might be the Xdrip app then.. 

Each time we connect another BT device to it, the other disconnects.. gotta investigate more.. 😉

**Comment by andyrozman** [comment]
I think you can have only two devices connected.. One CGMS and one Meter... But configuration points are different, meter is configured on other configuration page...

**Comment by Navid200** [comment]
@andyrozman Would you please close this issue if it has been resolved?
If not, you can use the support channels to see if there are any existing solutions or work-arounds.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
If you like to reopen, please update what the possible work-around are and why they are unacceptable.
