### ISSUE TITLE
confused calibration

### ISSUE THREAD

**Issue by ObstKur** [NightscoutFoundation/xDrip#770]
I somehow managed it to get the status message "confused calibration 2" and "signal missed" at the same time. Maybe because i entered calibrations and reset them immediately. 
In the log it says "encountered backfill data we dont recognize 9 5 127"
How can i get the system to work again?

**Comment by ObstKur** [comment]
I managed to resolve the issue. The Dexcom receiver wanted me to enter a calibration after a certain time. I then restarted the phone and now xdrip seems to receive data again and the error message disappeared.

**Comment by rlweiner** [comment]
I started getting this error on a new sensor after 1 day. It continued after I did sensor shutdown/clear calibrations. The calibration option then disappeared from the xdrip menu! The Dexcom receiver kept asking for calibrations, but after 4 of them it seemed normal. I restarted my phone and after about 15 minutes xdrip started working again.

**Comment by oakeley** [comment]
This problem is not solved however. If you get a confused calibration and then do not enter a new calibration before the "no signal" error then the "initial calibration" menu disappears. Once the menu has gone there is no way to reset the calibration apart from a full restart on the sensor. Please can we have a way to force a calibration signal to be sent even if xDrip "doesn't think" it should activate the menu. The disappearance of the calibration menu removes the easy way to fix calibration problems
