### ISSUE TITLE
Android 9.0 Pie (ZTE Axon 9 Pro) blocking wakeups from Doze

### ISSUE THREAD

**Issue by miiihi** [NightscoutFoundation/xDrip#780]
My ZTE Axon 9 Pro updated to Pie a few days ago, causing XDrip to start failing - specifically whenever phone is on battery and screen is off (that is dozed), XDrip doesn't receive any data, with screen on or on connected power, it works perfectly.

Being a developer (with very limited Java experience though) I tried to debug the situation:
- Disabled "Adaptive Battery" feature, verified that Xdrip is not optimized automatically and is "allowed to run in background, even if it drains battery fast". No change, XDrip is still not being waken up
- found that there is already a workaround in place for buggy Samsung phones, using `setAlarmClock` call instead of `setExactAndAllowWhileIdle`, so I hard enabled it, deployed, but still no changes, no waking up... (although there is now a clock icon visible in notification line...)

So my question is, is there anything more that I can do/try to debug?
Any other Android setting that I've missed and could be relevant?
Any other possible workaround?

Thanks, Blaž

**Comment by gregorybel** [comment]
you could look here: 
https://github.com/NightscoutFoundation/xDrip/issues/780

**Comment by MasterPlexus** [comment]
I'm pretty sure, you want to use a other issue, as 780 is this issue itself ;)

**Comment by gregorybel** [comment]
might be :smile: thank you
I try again:
https://github.com/NightscoutFoundation/xDrip/issues/663

**Comment by miiihi** [comment]
Thanks @gregorybel  for the reference. It certainly looks like the same (or very similar) issue as with Samsung Pie update, although none of the fixes/workarounds work for me... Not even using old G5 collector - simply no way at the moment to get values when the phone is dozed... Moving back to old phone at the moment and will continue to debug the issue on new phone...

**Comment by dave1812** [comment]
Sounds like I won't be able to use xDrip on the S10, eh?    Dang, isn't there a way for xdrip developers to sell this thing to a large company so it can be developed to the point where it WORKS??   This is getting beyond ridiculous how many problems there are.  Only older versions of xDrip and older Android versions appear to work pretty well.  I can't even go past the 7/15/18 version of xDrip if I want it to work with my Gear 2 watch. (I'm using an S7 phone with that).

**Comment by MasterPlexus** [comment]
@dave1812 , just some comments:
- nothing could be sell to a big company, as no company will produce a software like this. It is too complex, to many Sensor-Typen under one hood, and a company will be reliable in a medical device manner... 
- if you want to use company apps, just do it. They are available (Librelink, Dexcom apps, Eversense and so on). But then you have to live with what a company will provide. Very much less functionalities, and no loop possible and so on... Just do it.
- as you say there are many problems: the most of them are not in xdrip based, but in several smartphone providers made their non standard and closed firmware thing.
- all here is opensource, and all devs do it for free. 
- if a Dev have not the problematic device, it will be not easy (or maybe impossible) to identify the problem.
- time is not an endless source, and devs have several topics where are be working on. And unfortunately for you, other topics are more important at the moment.
- as it is opensource, and the source is available, and you own the problematic device: just join the Community, and check the source where it is wrong.
- last but not least: if you think a Dev will be happy to support you because you pollute several issue entrys, you are wrong. Every topic will be handled by the possibilitys.

**Comment by dave1812** [comment]
"    * Every topic will be handled by the possibilitys."   what does that even mean?
if you are developing for a non-standard/closed firmware thing, are you saying the devs can't handle this?  that's VERY DISAPPOINTING TO PEOPLE who are buying phones with certain OS's on them, and watches, TO RUN CGM software on them.   
Of COURSE I can use Dexcom s/w but that doesn't work on my Gear 2.

YOU GUYS HAVE FAILED to keep YOUR CODE working with Android Notifications  since right after the 7/15/18 version.    Who's fault is that?  Mine?   PARDON ME FOR COMPLAINING!!!   I'm and end-user yet you bitch at me for complaining when YOU GUYS BROKE THE CODE in July of last year.  It wasn't because Samsung did something to you.   It was YOUR CODE that became broken.  You can't blame that issue on Samsung.

**Comment by dave1812** [comment]
" * nothing could be sell to a big company, as no company will produce a software like this. It is too complex, to many Sensor-Typen under one hood, and a company will be reliable in a medical device manner..."

ah, "too complex" for a large company, but it's just fine and dandy for unpaid volunteers to struggle to keep up with Android issues?   That's not really too logical, is it??  You claim that your band of unpaid volunteers are more capable than a large company would be.   

"Pollute"?    Well, thanks for the kind words because I've been trying without success for the devs to fix something that was BROKEN way back in July of last year.   Having CGM data on my watch is a HUGE benefit to me, as it would be to any Type1.  I think you have NO IDEA of the issues we Type 1's face.   **Thanks for being so understanding--NOT!!**

**Comment by MasterPlexus** [comment]
@dave1812 , I've tried to explain it to you, but it looks like you are not willng to understand. You throw arguments mixed, and did not read what I write.
As I have tried it several times, and I'm now upset, you will hear clearly nothing additional from my side. There are explained ways, which are not ok for you. Thats it. I wish you the best.

@miiihi , sorry for that whithin your Issue-Entry.

**Comment by RaabenFuchs** [comment]
Hi,
great that you have such an amasing discussion! @dave1812 you seem to have a point, but, im just curious: did they break it completely? i thoguht it never worked at all.
anyway thanks a lot, i recently thouhgt abaout buying an android 9 phone, but if it isnt working at all of course i wont.
@dave1812 where did you try to fix it? cant see any pulls/commits on your fork...

i was alway interested because, MasterPlexus is right, big firms arent willing to maintain such a nasty project. because companies couldnt benefit in any way.

im happy to have a solution, where i dont have to rely on any companys software ore worse, cloud connection.

in germany you have the right to remain unconnected with your healthdata. which i prefere.
and im also happy to say: then stay away from samsung if they cant commit to bluetooth standard (i think their wifi direct, didnt really work, too) cause thats customer retention in my oppinion. is it the same on googlephones now?

**Comment by miiihi** [comment]
first update of Android Pie on my ZTE Axon 9 Pro (to build number ZTE_A2019G_ProV2.1.0B03) fixed dozing issue... XDrip is now working!!! (with all battery optimizations disabled, of course).
