### ISSUE TITLE
Different arrows on watch and phone

### ISSUE THREAD

**Issue by MrField123** [NightscoutFoundation/xDrip#800]
Watch and phone showing different arrows but same numbers. The wear arrow is the same as the one at the original dexcom receiver. 

**Setup:**
G6, Nativ Mode, Patched Huawei Watch, Galaxy S7 edge, latest xDrip+ build.

**Comment by parapenT1sta** [comment]
Can you try to change the Arrow trend to the new version? Some Android OS change the default arrow and it's not good... 
Long press on xDrip+ (graph) upper left corner, and then activate the last option.

**Comment by jag111** [comment]
I see this too with G6, Nativ Mode, Sony SW 3, Moto E (2nd gen), Beta xDrip+ build.  Don't understand "Long press on xDrip+ (graph) upper left corner, and then activate the last option" since long press does not bring up options. What is the name of the option that should be changed?

**Comment by MrField123** [comment]
The new arrow trend looks fine in the app thanks! But in notifications and on the watch the arrows are random.

Long press in the xDrip Logo (blood drop)

**Comment by jag111** [comment]
> Long press on the xDrip Logo (blood drop) will Open the settings
Thanks, that worked. No effect on watch arrow though.

For me watch arrows are not random, but often less steep than phone arrows. Not a major issue for me, just something I noticed.

**Comment by teflonjoe** [comment]
I have this issue too. Using OnePlus 6T and Ticwatch C2. Arrow on watch face does not correspond to app.

**Comment by rca221** [comment]
Same issue here too with Xdrip and G5 on Android TicWatch E.

**Comment by hmbannister** [comment]
I have the same issue with xdrip/g6/fossil watch.

**Comment by wakefulpanda-web** [comment]
I have the same issue on xdrip+, G6 and Fossile G5. Watch arrow just remains straight while Xdrip app on phone will have the correct corresponding arrow for a rise/fall rate.

**Comment by Cagier** [comment]
I have this error too with my pebble but I think the problem is that although the xDrip is working out what the arrow should be, it is in fact sending the arrow that the G6 has derived instead.  I've deduced this from the fact that we have a separate G6 receiver and the arrow direction on the watch (and NightScout site) always match the Dexcom receiver and these are often different to the xDrip app.

This seems to related to the G6 but may relate to G5 in Native Mode also?

I suggest that the xDrip app should transmit it's own arrow to remote systems rather than blindly sending on the arrow direction that Dexcom has worked out.  It would be more consistent and less confusing (and more accurate!)

**Comment by sweetafro** [comment]
Same issue here. Watch trend arrow and phone trend arrow don't match. 
Running latest nightly xdrip+, G6 8H series transmitter, Zenwatch2, Moto G7.

**Comment by Navid200** [comment]
There doesn't seem to be any active developer addressing WearOS concerns.
We can always reopen if such a developer joins.
