### ISSUE TITLE
Volume is way to high in build 0223-80e1023

### ISSUE THREAD

**Issue by zshh** [NightscoutFoundation/xDrip#813]
Volume of the device (phone) is completely ignored by xdrip in the version from 23rd of Feb 2019. 
Also changing the volume profile in xdrip it self between High and Medium doesn't make any difference. It's really really loud. 
I went back to January build which works as expected.

**Comment by tzachi-dar** [comment]
Can you try the latest nightly?

**Comment by zshh** [comment]
Just tested 20190304-c1a661b, issue remains.
Just to be clear there is a difference between Medium and High volume profile. But medium feels like at least 50% higher than medium in older versions.
When it goes off in middle of the night its heart attack inducing.
So I am back at 20190106-c45ef19 version again

**Comment by zshh** [comment]
Just briefly browsing back through different commits and searching for volume these 2 pop-up.
No idea if they are relevant or not

https://github.com/NightscoutFoundation/xDrip/commit/8d5a08bbc17842706a8aebcc515c670291da6320

https://github.com/NightscoutFoundation/xDrip/commit/03f5cc719034cef710957990cbaeea0249499091

**Comment by jamorham** [comment]
More likely I think is that volume is now being properly adjusted. So you just need to go in to your Alert settings and change the volume profile to, for example, medium instead of high.

**Comment by zshh** [comment]
I always had it on medium (even in old-er builds), but medium now is really really loud compared to before. Can we have "low" profile? or custom like 0-10 scale?

**Comment by jamorham** [comment]
Have you tried the ascending profile? That is what I use.

**Comment by zshh** [comment]
Ascending profile is not reliable. Both me and my wife tried running in that mode and it without doubt sometimes misses audible alerts all together. I am at the latest build.

Can you **please** reconsider adding back either:
1) that volume can be controlled via built-in Android volume control/levels as it was before
or
2) Add the some kind of volume slider inside xdrip application to control the level
or
3) Add "Low" to the volume settings.

As it is now, if we want audible alarm right away its waking up half the house in middle of the night and giving heart attack to everyone.

**Comment by jo1st** [comment]
Please I second that from Zshh, as him the ascending option nor medium works well, either too loud or ......

PLEASE

that volume can be controlled via built-in Android volume control/levels as it was before
or
Add the some kind of volume slider inside xdrip application to control the level
or
Add "Low" to the volume settings.

**Comment by Navid200** [comment]
@zshh It is dangerous to lower the volume too much.  What if doesn't wake you up?

Can we focus on the ascending volume issue?
Can you explain what the issue is?  I have noticed that it could skip the entire alarm clip depending on what the clip is.  But, I have never spent time on it to try to figure out why.
But, I have chosen files that it plays and I have no problem with it.

Do you mind giving us more detail about your problem with it?

**Comment by Navid200** [comment]
If anyone finds this issue and has the same request, please post and please explain what you don't like about the ascending volume profile.

**Comment by Navid200** [comment]
I am worried that some may feel that they should have the option and freedom and don't need to be forced what to do.  I would like to just explain my thinking and we can talk about it.  I'd like to use an example.

Let's say we add a Low volume profile to xDrip.
Let's say a construction worker, who has to deal with a very noisy work environment, changes the volume profile to Low before going to bed because he doesn't want to bother his partner.  
Let's say in the morning he forgets to change the volume setting back to High,
He then goes to work; he gets a low glucose alert; but, never hears it because it is very quiet with respect to the noise around him.

We can say that's his responsibility and why should we penalize everyone because one person may forget to use proper settings.
I would say there is a solution and that is the ascending volume profile.  It starts really quiet.  But, eventually it could become very loud.  So, you never have to remember to change any settings.  I hope you give it a try and like it.

**Comment by zouden** [comment]
The ascending volume profile is not a good solution, because it keeps alerting every 1 minute until you dismiss it. It is so annoying that I had to turn it off. I'm surprised you like it. What happens if you've left your phone in another room? Or you're relaxing watching a movie on the couch and your phone is on the table and it keeps playing this sound every minute. I don't want to have to get up to dismiss the alert. I just want to hear a quiet sound to let me know if my blood sugar is high or low.

A "low" volume option is a simple bit of code that would make life more pleasant for a lot of users. Please, someone add it 🙏

**Comment by Navid200** [comment]
@zouden Every change we make to xDrip has more than just one consequence.
We have to consider them all.   Would you please consider the following scenario?

A construction worker is home from work and changes the volume profile from high to low in order not to bother his partner.
Tomorrow morning, he forgets to change the volume profile from low back to high before going to work.
While at work, he has a low.  But, he never hears it because his work environment is very loud.
The possibility of this scenario occurring is the reason I personally would never favor what you are requesting.

Can you think of a way to avoid the scenario I have described from happening other than expecting the user not to forget to change back the volume profile?

The scenario you have described can easily be addressed by snoozing the alert.  I'm not 100% clear why that is an issue.  If you have an alert that has triggered, why would you want to ignore it by not hearing it?

**Comment by zouden** [comment]
Well, the desire to have quiet notifications at home and loud notifications at work isn't specific to xDrip users. This problem was solved years ago when phones got silent mode, do-not-disturb, and scheduling. 

Suggestion: a separate volume level for when do-not-disturb mode is activated? That way we can have it quiet at night, and loud when we go out,, and we can simply use our phone's schedule/routine features to activate the different modes, as normal.

>I'm not 100% clear why that is an issue. If you have an alert that has triggered, why would you want to ignore it by not hearing it?

Perhaps I didn't explain clearly. I want to hear the alert right away... I don't want to have to find my phone and swipe the notification away to prevent it playing the sound every minute. Once a minute is far too frequent for a high-blood-sugar alert. So I don't want to use the "ascending" mode. But then I have to use the "medium" mode, which is too loud. I simply want a "low" option.

**Comment by Navid200** [comment]
No, silent mode does not address the scenario.  Most xDrip users want to get the alert even when their phone is in silent mode.  But, they also don't want to wake up their partner.  That's where the ascending volume becomes very useful.

You don't have to use it if you don't like it.

Very unlikely we will create a low volume profile.

**Comment by jo1st** [comment]
I really don't get why we have to read replies like the last, what's the
big deal to just create a low volume option? You don't want to use it? then
don't but give the option to other users to use it if they want.  I could
care less because I solved the problem by installing the Sound Assistant
app by Samsung on my phone so that I can set a lower alarm sound for xdrip.

**Comment by zouden** [comment]
I also don't understand the opposition to the Low volume profile. The hypothetical construction worker can continue to use the Ascending profile. I'm not proposing doing away with the Ascending profile, I simply ask for a lower volume option. Please! 🙏

@jo1st, I've also tried the samsung Sound Assistant and it doesn't seem to work. Even if I set the xDrip volume to zero, the "test alert" feature in xDrip is extremely loud. Is it really working for you?

**Comment by jo1st** [comment]
are you using it correctly? it works for me just fine. I set xdrip in the
individual apps option and control the volume there.

**Comment by jo1st** [comment]
don't test in xdrip, that's a test. just set it up and see if it works

**Comment by zouden** [comment]
Okay I've discovered that it works if I disable the setting called "force speaker". With that off, the volume can be adjusted with the samsung Sound Assistant app. Fantastic!

What does the "force speaker" option do? It's not obvious.

**Comment by jo1st** [comment]
sorry, I forgot about it, it was a while ago. I don't know what that does
but I'm glad you are OK now.

**Comment by zouden** [comment]
The "force speaker" option is a setting in xDrip for the alerts. Actually I googled for it, and it forces the alert to come out of the phone speaker instead of a bluetooth speaker (this is useful to me, because I use bluetooth speakers a lot and I don't want alerts coming over the music). However it makes the volume **extremely** loud. Even the Ascending profile is incredibly loud.

Now that I've turned force speaker off, and used Sound Assistant to reduce the alert sound by 50%, the xDrip alerts are now tolerable. Thank you.
