### ISSUE TITLE
Have to reset "Number Icon in Notification Area" upon phone reboot

### ISSUE THREAD

**Issue by davidmtml** [NightscoutFoundation/xDrip#864]
I am able to have my BG show up in the top notification panel successfully.  However, anytime I have to restart my phone, I have to go back into the settings, turn OFF that option, leave the settings screen, then go back into the settings screen and turn it back on.  If I don't do this, it just shows the "blood drop" icon, instead of the numerical BG.  

I am using an LG G6 android phone.

**Comment by opasha** [comment]
Yep, this is a known issue even on Nov. 2 version (the one I'm on). I do exactly what you do. What I do is, turn it off and on twice, then force stop xdrip app, then re-open and it works. I'm on Android 9.0 pie (Xiaomi Mi Max 3 running AOSiP rom).

**Comment by TheMunshi** [comment]
Doing it twice is what works for for me too

**Comment by jamorham** [comment]
The number icon in notification area has a safety check on it that it wont start the feature until something like 15 minutes after a phone reboot. The reason for this is that on some buggy phones the number icon can completely crash android (which is why there is a test process before enabling it) - If your phone somehow was still one of these buggy ones then the 15 minutes grace time gives you time after power cycling your phone to recover by switching the feature off. I'm pretty sure that is what you guys are experiencing here.

**Comment by Navid200** [comment]
@davidmtml Would you please close this issue if you are satisfied with the answer?
Thanks

**Comment by davidmtml** [comment]
I no longer have this phone, but I don't have the problem with my new phone.  So, since this no longer an issue for me, and no one else has commented having the issue for 18 months, I will go ahead and close it.

**Comment by TheConen** [comment]
I'm having issues with the number icon, too - I somehow got it to work, but after a reboot it was gone and I couldn't manage to get it to show up again. Could you point me to the code where the safety check is?

**Comment by TheConen** [comment]
Update: number icon works as intended, however, it is coupled to the persistent notification of the foreground collector which I had disabled (see #1793).
