### ISSUE TITLE
Is there documentation on how to import and build xDrip

### ISSUE THREAD

**Issue by bert1973** [NightscoutFoundation/xDrip#878]
I pulled the project from Github, opened it with the latest version from IntelliJ community (IntelliJ IDEA 2018.2.8).
After build, I chose: Build Artifacts, but this keeps resulting in:
Error:java: invalid target release: x (where x is a version, e.g. 11)
Questions about import:
Is there any documentation?
Should I use the standard Gradle wrapper or custom?

**Comment by tzachi-dar** [comment]
I think that most people use android studio to build xdrip.
You can also write gradlew assembledebug from command line to build it.

**Comment by bert1973** [comment]
I decided to go with Android Studio, but even this one fails:
error: cannot find symbol class Models
error: package UtilityModels does not exist
error: package Models.ProcessInitialDataQuality does not exist
error: package UtilityModels does not exist
etc.

Do I have to do clone more then master from https://github.com/NightscoutFoundation/xDrip.git?

**Comment by k2s** [comment]
the problem you have is related to comment `// use specific version of data binding until google resolves the bugs with mixed case package names` in `app/build.gradle`

when you open xDrip (after clean clone) in Android Studio it will ask you `Plugin Update Recommended: Android Gradle Plugin is ready to update.`. Ignore that otherwise you will get into troubles.

@jamorham do you know what is the problem ? by quick try there is no reason to wait until `google resolves the bugs with mixed case package names`. Is it needed to rename something manually in xDrip code to get it fixed and to upgrade to latest Gradle plugin ?

**Comment by k2s** [comment]
related ticket #1012

**Comment by tolot27** [comment]
As mentioned already, use Android Studio. I'm on 4.1.1 and it works pretty well.
