### ISSUE TITLE
Make xDrip+ available on FDroid

### ISSUE THREAD

**Issue by nbraud** [NightscoutFoundation/xDrip#902]
[FDroid] is a popular, free software repository for Android.
Please consider making xDrip+ available there.

I took the liberty of opening a request on FDroid's tracker: https://gitlab.com/fdroid/rfp/issues/1001
However, part of FDroid's process involves checking that you (the software's author) support the inclusion; please state (on this issue or on FDroid's tracker) whether this is the case.

[FDroid]: https://f-droid.org

**Comment by Navid200** [comment]
@nbraud Would you please close this issue if you don't require it any longer?
Otherwise, would you please explain what benefit the community would gain by this compared to the current situation where anyone can already access and use xDrip?
Thanks

**Comment by tolot27** [comment]
If you follow the discussion at https://gitlab.com/fdroid/rfp/issues/1001 you'll see that it is currently impossible to fulfill the FDroid requirements. None of the xDrip developers has time to remove the "evil" dependencies.

**Comment by chemputer** [comment]
@tolot27 @Navid200  I'll let you two decide to reopen this or not, but after a couple hours of looking into it, it would seem that all of the "evil" dependencies would no longer be dealbreakers anymore for the main FDroid repo, just considered [antifeatures](https://f-droid.org/docs/Anti-Features/) which would be fine, they're essentially just "hey, make sure you're okay with this", which is cool. I'm completely unsure if this is the case, but the source code for firebase seems to be at least open source? Doubt it's FOSS, but, it's something. But that does still, even if proprietary, seem to me, anyway, that it would count as an antifeature, not a disqualification, but I am not 100% on that. https://firebaseopensource.com

Personally, I would be fine with it being on Fdroid (though asking you to create a custom repository is a bit much) OR like some sort of self-updating mechanism within xdrip itself, as I imagine for a lot of people (especially when you install it for an older relative's device but want to keep it up to date between visits.) it would make keeping the app up to date a lot easier than having to go to github to check... Heck, even an optional push notification for when there's a new apk available on either the release or pre-release branch would be fantastic. If I'm missing a feature, my apologies, there are a lot!

Keep in mind, and this is mostly directed at @Navid200, most of us (myself included) are power users, _at least_ and so going to github and getting the release and sideloading it is no big deal. But for a lot of people who would probably like the extra data, especially out of Stelo, but aren't... super great with Android, then that's a task. Having it from a "Play Store" of sorts that reminds you to update when there is a new release or even just the app itself updating itself, would be quite useful to a lot of people. 

I have a few family members that I can't always visit, and I don't mind if I miss a few versions, but I do try to keep it _relatively_ up to date, because it's sending their data to my server which... yeah. 

It's an extremely useful app, I can't ask you all to do more than the very basics here, but IF it'd be possible to see if Fdroid would take it with their seemingly revised criteria since the initial attempt, or build in a simple updater (select which branch, get push with direct link when new release in that branch is available, store link, notify for update, allow download and update. I'm aware it's more complex than that but, still), I know I would appreciate it, I'm sure others would as well. It's a bit clunky as it is now.

**Comment by Navid200** [comment]
@chemputer ,
xDrip can give you a daily reminder that there is a new release in your chosen update channel.
https://navid200.github.io/xDrip/docs/Updates.html

**Comment by Navid200** [comment]
@chemputer With respect to the request here, I see no reason to place xDrip on any platform.
I am a user and I also spend time helping with maintenance.  The last thing we need is to add additional restrictions.
I really am not going to remove xDrip components in order to meet fdroid requirements.  We already have a lot of challenges and I would like to focus on tackling those.  You can see our open issues.  We need to address those.  I don't need artificial restrictions to keep a third party happy.  And for what?  What do we get in return for placing xDrip on a platform?

There is a legitimate request for putting xDrip in the Google play store.  There are individuals who cannot use xDrip because their work requires them to only have apps installed from the app store.
I would really like to do something so that we can allow those individuals to be able to use xDrip.  But, Google imposes lots of restrictions as explained here: https://navid200.github.io/xDrip/docs/App-store.html  
We would have to give up our emergency text messaging.  We cannot do that.  As much as I would like to allow everyone to use xDrip, the price is too high.  So, we are not putting xDrip on Google Play store.  I don't see why we would put it anywhere else.

**Comment by chemputer** [comment]
First, sincerely, thank you for pointing out the update reminder, I completely missed that somehow!
> I really am not going to remove xDrip components in order to meet fdroid requirements. We already have a lot of challenges and I would like to focus on tackling those 

No components would need to be removed to meet their requirements. That was my point. their requirements have changed. I agree, open issues take priority.

To be clear, I'm saying that Fdroid's CURRENT rules and all that would allow Xdrip+ in. It would get several anti-feature labels, but that's about it. They've moved a LOT of things from hard nos to getting an antifeature label on the download page. 
I completely agree with you that it's not worth modifying it just to get onto a platform, and losing emergency text messaging to get on Google Play Store would be terrible, so I get it. Just a note, that link works, but if you click to look at the thread, it simply takes you to the forums, I could not find the specific thread, but I will take your word for it. But I do think it's worth submitting it again, given the many changes and relaxed rules that Fdroid now has compared to when it was initially denied.


> I don't need artificial restrictions to keep a third party happy. And for what? What do we get in return for placing xDrip on a platform? 

I can't really answer what you get in return, that's more abstract, but there wouldn't be artificial restrictions, again, that's my point. You just put it on there, automate it, and you're good. You can't get it on Play Store, but Fdroid would be nice. At least it's managed by an app store. 


Even if, for some esoteric reason, Fdroid denies it, there's always the ability to host your own repo, or see if another Fdroid repo will take it, and in that case, the answer is this one: https://android.izzysoft.de/repo/info 900 applications already, they say they're willing to work with people, and the aps they have on their repo are not super restricted, just lots of anti-feature warnings. These repos can be added extremely easily in the Fdroid app, and they simply add access to additional applications. Alternatively, there's even a tool to help set it up using GitHub Pages, so you don't even have to worry about hosting cost: https://github.com/eyedeekay/fdroid-git this I'd actually be able and willing to help with if you wanted to go that way. Technically, I _could_ do it at any point (it's that simple, seriously), but I respect the work not to. izzzysoft repo is added by default in several Fdroid compatible app stores. 

Is a self updater out of the question? I'll be honest, it seems like it would take a little work, but there are essentially plug and play modules, like this one: https://github.com/burgyl/SelfUpdatingApp which is for that exact purpose. 

Apologies for the length, best wishes, I hope some of this can be helpful.
