### ISSUE TITLE
xDrip stuck on "still warming up"

### ISSUE THREAD

**Issue by joelerch-zz** [NightscoutFoundation/xDrip#916]
I recently put in a new sensor and a new transmitter. I receive (seemingly) accurate data from the transmitter: the graph, the notification, and my wearOS watch all display the last reading, the trend, and the graph, but the home screen in the xDrip app continually says "Sensor is still Warming Up, please wait" and doesn't show the result or trend, only the graph. 

I've tried restarting my phone, calibrating the sensor, stopping and starting the sensor, and even hard resetting the transmitter, none of which have worked. It is unclear to me if this is an issue with xDrip, or with the new transmitter.

**Comment by MattDxdrip** [comment]
Hi -- I was having the same problem. For me the issue turned out to be having a wearOS watch that wasn't set up properly, but having the phone's Settings->Smart Watch Features-> Android Wear Integration->Enable Wear Collection Service turned on.
When I turned the Enable Wear Collection Service off,  the "still warming up" message went away at the next sync.

(I have a Huawei Watch 2 with a newer build number than supported in the patch, so I wasn't able to apply the patches and the watch couldn't run the collection service.)

**Comment by Navid200** [comment]
@joelerch Would you please close this issue if the problem has been resolved?
Otherwise, could you please post in the xDrip facebook group for advice?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by joelerch** [comment]
> 
> 
> @joelerch Would you please close this issue if the problem has been resolved?
> Otherwise, could you please post in the xDrip facebook group for advice?
> https://www.facebook.com/groups/xDripG5
> Thanks

Hey, sorry, I actually lost access to that old github account, so I can't close this. Is it possible for you to do so? Sorry for the inconvenience.
