### ISSUE TITLE
G6 sensor restart problems with xDrip

### ISSUE THREAD

**Issue by jgordon5** [NightscoutFoundation/xDrip#963]
I have restarted my sensor after 10 days and initially I got a warm up period showing on the start screen but now I have sensor failed start message.  I have a notification Auto Start Senor Requesting Restart but when I click on that nothing happens.
I have restarted collector a couple of times, unpaired the transmitter and paired it again but to no avail.  The only option now seems to be to insert a new sensor which I wanted to avoid.
Any suggestions would be appreciated.
Thanks.

**Comment by svirito4ka** [comment]
Look at [xDrip+ settings](https://androidaps.readthedocs.io/en/latest/EN/Configuration/xdrip.html#xdrip-settings) and [Dexcom G6](https://androidaps.readthedocs.io/en/latest/EN/Configuration/Dexcom.html#dexcom-g6).

**Comment by Zxquad** [comment]
Hi jgordon5, 
do fix your problem, cause I ve the same here ....

**Comment by opasha** [comment]
Try my settings :

<a href='https://postimg.cc/LnXV5wfR' target='_blank'><img src='https://i.postimg.cc/LnXV5wfR/Screenshot-x-Drip-20190810-154837.png' border='0' alt='Screenshot-x-Drip-20190810-154837'/></a>

**Comment by SabineDo** [comment]
You can try this:
1) Stopp sensor
2) Start sensor with code 0000
3) Wait 15 Minutes
4) Stopp Sensor and start with code again

**Comment by apeterson22** [comment]
@SabineDo  Have you been successful with doing that? is the second code the actual code or 0000 again?

**Comment by mrazek** [comment]
HI, doeas anyone have any solution? We have G6 since end of August and we were never able to restart it:(. Before August we had G5, and we had never any problem with sensor restart. I tried stop - strat with 0000 - stop - start with real code, but I was never lucky.

**Comment by opasha** [comment]
> 
> 
> HI, does anyone have any solution? We have G6 since end of August and we were never able to restart it:(. Before August we had G5, and we had never any problem with sensor restart. I tried stop - strat with 0000 - stop - start with real code, but I was never lucky.

This is the proven way to make it work:

1) Stop Sensor
2) Remove the transmitter with thin plastic (guitar pick or glucometer test strip) - set a time for 15 minutes - no less
3) Wipe down the sensor's two gold dot area - this gets sweat/oil/soap/water on it, so it needs to be completely cleaned to be functional - anything in the way will cause errors - MAKE SURE TO KEEP THE TRANSMITTER NEAR YOUR PHONE DURING THIS TIME.
4) Carefully clean the black rubber tips on your sensor on your arm - this is the point of contact those gold circle sensors make from your transmitter. Yes, they both need to be clean before contact with each other - I have tested this many times - the cleaner the contact, the longer your sensor can last - I have done 3 re-start sessions and got up to 25 days once.
5) After the 15 minutes are up and sensor and transmitter are cleaned, reconnect them and make sure your phone is still connected to your transmitter
6) Start Sensor as if brand new - enter the present time and date when asked and enter the same code for your transmitter - do not do the 0000 method - it does nothing
7) Wait 2 hours and a few minutes (for the final warm up) and it will automatically resume

When the above starts failing, it's time to change your sensor because at that point the connection to your arm is no longer good. 

Be aware that sometimes, your readings will be initially higher, so do not re-calibrate at all - this will mess up your readings and can cause issues. It's better to let the sensor level out and it will do so on its own. Verify the accuracy with a glucometer initially and later when you feel like to see how far off the range is.

**Comment by mrazek** [comment]
Many thanks, Omar, next time, I will try this way. We just started new sensor, so we will try it in 10 days...

> 
> 
> > HI, does anyone have any solution? We have G6 since end of August and we were never able to restart it:(. Before August we had G5, and we had never any problem with sensor restart. I tried stop - strat with 0000 - stop - start with real code, but I was never lucky.
> 
> This is the proven way to make it work:
> 
>     1. Stop Sensor
> 
>     2. Remove the transmitter with thin plastic (guitar pick or glucometer test strip) - set a time for 15 minutes - no less
> 
>     3. Wipe down the sensor's two gold dot area - this gets sweat/oil/soap/water on it, so it needs to be completely cleaned to be functional - anything in the way will cause errors - MAKE SURE TO KEEP THE TRANSMITTER NEAR YOUR PHONE DURING THIS TIME.
> 
>     4. Carefully clean the black rubber tips on your sensor on your arm - this is the point of contact those gold circle sensors make from your transmitter. Yes, they both need to be clean before contact with each other - I have tested this many times - the cleaner the contact, the longer your sensor can last - I have done 2 re-start sessions and got up to 27 days once.
> 
>     5. After the 15 minutes are up and sensor and transmitter are cleaned, reconnect them and make sure your phone is still connected to your transmitter
> 
>     6. Start Sensor as if brand new - enter the present time and date when asked and enter the same code for your transmitter - do not do the 0000 method - it does nothing
> 
>     7. Wait 2 hours and a few minutes (for the final warm up) and it will automatically resume
> 
> 
> When the above starts failing, it's time to change your sensor because at that point the connection to your arm is no longer good.
> 
> Be aware that sometimes, your readings will be initially higher, so do not re-calibrate at all - this will mess up your readings and can cause issues. It's better to let the sensor level out and it will do so on its own. Verify the accuracy with a glucometer initially and later when you feel like to see how far off the range is.

**Comment by mrazek** [comment]
it works!!! I restarted g6 already twice. Thank you very much!

**Comment by Navid200** [comment]
We are restarting G6 sensors on current G6 transmitter (8Q).  Instructions are available in the facebook group.
https://www.facebook.com/groups/xDripG5/permalink/4521043737969086
You can also ask in the Gitter room:  https://gitter.im/jamorham/xDrip-plus
I would like to close this issue.
Please respond if you have any questions or concerns with that.

**Comment by Navid200** [comment]
If you need help restarting a G6, please access the instructions in the facebook group, or post in the Gitter room.
