### ISSUE TITLE
Insufficient Calibration dead-end on G6

### ISSUE THREAD

**Issue by meatychunks99** [NightscoutFoundation/xDrip#976]
I seem to be stuck with my daughter's G6. I've fitted a new sensor this evening and entered the calibration code. The readings were off by a mile - 6 hours after fitting it was reading 16.4mmol/l when her blood stick was showing 9.2. So I entered it as a calibration.
After which, no more readings. The phone showed 'insufficient calibration' on the screen and under the system status for the sensor. But the calibration button was reading 'cannot calibrate right now'.
I left it 45 mins and nothing changed, so I tried 'Stop Sensor' -> 'Don't stop sensor, just reset calibrations'.
Now everything is still showing 'insufficient calibration' but the calibrate option under the menu has gone for good - not even 'cannot calibrate right now'.
Seems I can't calibrate unless it's taking readings, but it won't take readings cause I need to calibrate!
Please help.

**Comment by opasha** [comment]
Search my name and go to my post regarding G6 sensors. Xdrip doesn't work correctly for certain phones including xiaomi phones (I have the mi max 3 with aosip pie rom - as stock android as you can get) for the dexcom G6. You need to do the following: you need to disable in G5/G6 settings, "Use the OB1 Collector" - see my screenshot. Wait 5 min and it will pick up your g6 sensor guaranteed. The G5 algorithm of whatever this does works flawlessly. He is limited to his phones, so I assume certain Bluetooth devices don't work the way the app is designed for - not his fault. At least there is a workaround. 

This solution is for everyone that has the classic "stopped sensor" error as well. Trust me. I'm a long time android sdk guy. I came over from the miaomiao/libre setup. My g6 sensors run flawlessly till they fall off after 20+ days due to my sports activities. You can also technically just stop your sensor once done and start your new sensor from the new date and it will automatically work and resume without any issues after the 2 hour warmup. 

[url=https://postimg.cc/LnXV5wfR][img]https://i.postimg.cc/LnXV5wfR/Screenshot-x-Drip-20190810-154837.png[/img][/url]

**Comment by definitivequestion** [comment]
I am having similar issues. I was using a brand new sensor with the G6 transmitter and was getting a reading of 52 mg/dL when a fingerstick was 97 mg/dL. I know I shouldn't have been nearly that low since I had just eaten and values that low would make me feel quite bad. This was on a Samsung Galaxy S7 phone on Android 8.0.0 (even the official Dexcom app complains about my phone being incompatible even though it is supposed to be supported). I had tried to enable the Xdrip fallback mode, but that option reset. After calibrating it seems to have resumed. Also this is my first time using a plastic protector over the patch.

**Comment by Navid200** [comment]
@meatychunks99 Would you please close this issue if it has been resolved?
If not, you can use the support channels to get access to guides, documentation and advice.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
If you experience the issues described in the first comment in this issue, please update xDrip at least to the November 27, 2020 release.  
And, please consult with the community to find out how everyone else is using xDrip.
