### ISSUE TITLE
Restart sensor and preemptive restarts option no longer works with new transmitter SN 81xxxx

### ISSUE THREAD

**Issue by cyrusbyte** [NightscoutFoundation/xDrip#980]
I received a new transmitter and now with the preemptive session restart set I keep getting errors. "Native Sensor is now Stopped: Sensor Failed Start" then " Native sensor is now marked FAILED: Sensor Failed Start" then "Session Start Failed: Invalid". It has been working on the last two transmitters that started with SN 80xxxx, but on the new one stating with SN 81xxxx is when i started getting these errors. Seems the only way to restart the sensor was to start it using the dexcom receiver and then i get the "Warming up" message on both xdrip and dexcom and have to wait the two hour warm up.

**Comment by definitivequestion** [comment]
I am using a G6 transmitter with serial number: 815UKC and firmware 1.6.5.25 and preemptive restarts are working with a nightly build (can't find the exact version).

**Comment by cyrusbyte** [comment]
Mine Says firmware version 1.6.5.27 and is 81CYXX im on alpha version 2019.08.20.. you can see the version under the classic status page

**Comment by definitivequestion** [comment]
I am using 33fe112-2019.08.19 xDrip. It says my code is: 1908191229 which is downgradable to 1603091400. I did encounter a similar problem back in July. Since I don't care about my security settings here is my XDrip QR code with settings that work for me: xdpref:eJwtjEEOwiAQAP+yZw/dLgjxhkC/QVjZGmLjwdIYa/y7JHqdycwbnnXPj5K2rRY4gZmLMUUzXkjUKIaZM4rYPLMQDgQHyMuSVmmt3q9r+tU9bN38Vzd5dXB0KmL0ypNz1tkhhvM4kdeBFAbnNXy+15kmCA== .

**Comment by bpedman** [comment]
My sensor is 81F6XX firmware 1.6.5.27 and restarts are not working anymore either. I'm currently on build ff2c822-2019.09.24

I uploaded logs as well.

**Comment by joshhiram** [comment]
We got transmitter 81A*** to show "please wait for warm up" message, but a
few seconds later, it popped up and said G6 sensor failed.  It still
counted down the warm up, and then began prompting for calibrations!  It
wouldn't get passed that.  So, we had to go to the official Dexcom app to
start it, which it did just fine.  Xdrip nightly 9-30 and alpha release
didn't have an effect.

**Comment by Ugitsisgv** [comment]
Using G6 with Nightly transmitter 815LPP. Preemptive restart says "not capable."  Transmitter is on day 17. Not sure how to restart sensor in 2 days.

**Comment by definitivequestion** [comment]
If you are getting not capable, you may have to manually restart and go through another warm up period. You may try disabling the advanced time travel features. If you have the official Dexcom receiver, you can probably trick it into restarting with the Faraday cage trick. What is on the first page of the status screen (the one with version information)?

**Comment by Ugitsisgv** [comment]
Thanks for the reply. Two questions.

What is the Faraday cage trick?

What do I do about the sensor code if I start manually?

Thanks for the assist.

**Comment by Ugitsisgv** [comment]
How do I disable advanced time travel feature?

**Comment by Ugitsisgv** [comment]
Here is what is on the first page.

**Comment by definitivequestion** [comment]
I am not seeing what you posted about firmware versions. You should Google restarting Dexcom sensors to make sure you do the protocol correctly. In essence you can use the combination of the official Dexcom app (though XDrip might also work, but I don't have a receiver and haven't had much luck getting two XDrip instances to pick up the transmitter properly) and the Dexcom receiver prior to the expiration of your sensor. As long as nobody will turn on the microwave for two hours you can just store the receiver in the microwave and trick the Dexcom app into thinking the sensor is new. As far as restarting XDrip manually, you can re-enter the calibration code and just tell the XDrip algorithm the approximate time you really inserted the sensor. Given my experience, I would advise you enter a fingerstick upon restarting and at least once a day afterwards because the sensor will get out of calibration and start reading over 50 points low. Finally, there should be a search box in the settings menu so you should be able to type in "preemptive restarts" and uncheck the appropriate box. The problem without the time travel is the restart reads 20 points high.

**Comment by Ugitsisgv** [comment]
Interesting thing happened today. I put in a new G6 transmitter on September 20th. It quit getting a signal twice and they sent me a new one. However, after both events, within an hour after the customer support calls, I began getting a signal again and called and cancelled the replacement transmitter. The transmitter lost signal again yesterday. Contacted Dexcom customer support again and they scheduled a replacement transmitter. An hour or so after contacting customer service the signal returned. I contacted customer support this morning to cancel the replacement transmitter and the rep was very apologetic and said they were sorry I had lost the signal and they'd put my account on monitoring to make certain it didn't happen again. I got the impression it was something on there end that had cut the signal. (Even the Dexcom receiver would not pick up the signal.) Anyone else have similar experiences?  Another problem I have noticed is xdrip stops working and I've have to uninstall and reinstall the app and set it to  work with my SW3. Two things happened both times and I am not certain which is causing the problem. The one was the problem mentioned above. The second was a system update on my Note 9. Don't know if the combination of the two are related.

**Comment by joshhiram** [comment]
We had a similar experience when we changed our son's transmitter that was
also 81xxxx.  We didn't contact Dexcom tho. We had to use the Dexcom app to
start the transmitter and we haven't gone back to xdrip yet. We thought it
was an xdrip update, but going back to older versions didn't fix the issue.
It could have been a phone issue since we were using an old Samsung G On5.
Maybe Samsung changed something? Idk but not good for us.

**Comment by Ugitsisgv** [comment]
So it sounds like a Dexcom issue. Maybe an effort to keep people from extending transmitter life but my transmitter, the first time, was only 74 days old and with the latest transmitter it happened at 20 days and again at at 29 days but I am convinced they restarted the sensor. Interesting thing is my SW3 kept receiving the signal until I finally restarted it in an attempt to solve the problem.

**Comment by jamorham** [comment]
If your firmware is ` 1.6.5.27` then I believe they have also put measures in that firmware to try to frustrate restarts. The transmitter serial number prefix is less important than the firmware version number which it is running.

**Comment by joshhiram** [comment]
I have 1.6.5.25.  By the way, thanks for all you do, Jam!

**Comment by Ugitsisgv** [comment]
I'm sorry but could you tell me how to check the version and how I might update it if that is the problem? I 'm using a Note 9 with a SW3 as the receiver. This is the Wear OS version - 2.29.0272887579.

**Comment by definitivequestion** [comment]
I am using a Galaxy S7 on Android 8.0 and the official Dexcom app has issues and I have the occasional issue getting other Bluetooth devices to work right. Just a few things to try testing when you are experiencing connectivity issues: 1) delete all other Bluetooth apps (I know it is a pain, but a rogue Fitbit or a media app may hold the link badly), 2) power off and unplug as much as possible to minimize RF interference. I personally find my transmitter drops when I am in the shower. Signal loss is usually pretty brief lasting perhaps 20 minutes, but since I don't use a pump I can accept that. As far as being able to get the transmitter version: open the XDrip menu (upper left) and select System Status. From there swipe left and right just to record all the information there. The transmitter version should be on the top of the leftmost pane.

**Comment by gobeti** [comment]
Brand new 8GXXXXX transmitters do not restart either @jamorham 

I just attempted a preemtive restart yesterday without success. I use as well Dexcom receiver and it just stopped the sensor completely.

Status in Xdrip shows: "Not capable" in the preemtive restart.

Thanks

**Comment by Ugitsisgv** [comment]
Question. I am getting ready to replace my G6 sensor. This will be the second time. Can I start it only using xdrip+ or do I have to use the Dexcom G6 receiver? I can't seem to find the directions for replacing the sensor, just restarting one. Thanks so much for the assist.

**Comment by definitivequestion** [comment]
You should be able to start the sensor using just XDrip. Hit the menu button on the left pane, hit "Stop Sensor", wait at least 5 minutes to ensure the system status says stopped, then you should have an option to start a sensor. Depending on which Dexcom you are using and how you set up XDrip, it should ask for a code for G6 and you can get readings after the 2 hour warm up. Otherwise, XDrip should demand calibrations.

**Comment by Ugitsisgv** [comment]
You guys are the best. Much appreciated.  

One other question. Does the G6 send data to Dexcom if I am not using the Dexcom receiver?

**Comment by definitivequestion** [comment]
Unless you are using the Dexcom app or you enable the settings in XDrip to synchronize with the Dexcom servers, you should not be sending any information to Dexcom. As far as I know, the receiver has to synchronize with your phone to get data onto Dexcom's servers.

**Comment by mk886714** [comment]
If u use the dexcom App des, Receiver only if u connect PC

**Comment by gobeti** [comment]
> h

I use the DEXCOM G6 receiver (as well). Question: Once you stop and restart sensor with Xdrip, what do you need to do in the DEXCOM receiver in order to keep getting the data every 5 minutes? Or should I just forget about using the receiver? Note that it is for my daughter so the receiver is necessary for us to cover her at night for instance and to get data to Clarity for her Endo.

**Comment by gobeti** [comment]
> Unless you are using the Dexcom app or you enable the settings in XDrip to synchronize with the Dexcom servers, you should not be sending any information to Dexcom. As far as I know, the receiver has to synchronize with your phone to get data onto Dexcom's servers.

I use the DEXCOM G6 receiver (as well). Question: Once you stop and restart the sensor with Xdrip, what do you need to do in the DEXCOM receiver in order to keep getting the data every 5 minutes? Or should I just forget about using the receiver? Note that it is for my daughter so the receiver is necessary for us to cover her at night for instance and to get data to Clarity via the PC for her Endo.

**Comment by Ugitsisgv** [comment]
It worked. So easy. Thanks.

Could you share (1) the steps to reset a G6 transmitter and (2) the steps
when the transmitter has to be changed.

I'm so excited about this. What a kind thing for you guys to do.

**Comment by Ugitsisgv** [comment]
Was easily able to start new sensor with your directions. The only conflict
I see is that it did not change the days of the sensor. It still has the
number of days from the old G6 sensor. Did I do something wrong? That way I
can avoid it the next time I put in a new sensor. Thanks so much

**Comment by definitivequestion** [comment]
Yes you have done something wrong and you are now in a DANGEROUS position. I ended up in the ER with hypoglycemia and horrible calibration when this happened to me and I am not on any diabetic meds. As far as I can tell, you most likely didn't wait long enough for the sensor to fully stop. I've read elsewhere you should wait 20 minutes from the time you stop the old sensor to the time you start a new one. I have also heard that you are supposed to go into the settings menu and disable all settings regarding restarting. Not quite sure what exactly needs to happen. As far as your current sensor, I would be sure to calibrate it once a day even though you shouldn't need to under normal circumstances.

**Comment by Ugitsisgv** [comment]
I went through the entire process again waiting 30 minutes to start the new
sensor with the same results. Sensor status says the sensor is 5.6 days
old. It ask for the dual calibration. It is connecting with my SmartWatch 3
without any problem.

**Comment by definitivequestion** [comment]
Preemptive restarts will advance the clock even on new sensors. My previous response was if it was saying sensor start was a your old date.

**Comment by todddexter** [comment]
Am I understanding the discussion correctly that: the new G6 transmitters, (81XXXX) can be preemptively 
restarted by using xdrip on my android? Previously I used the microwave signal blocking method and it no longer works.

**Comment by definitivequestion** [comment]
Not quite Todd. This thread is saying the 81 series transmitters have some issues with preemptive restarts. I had 815UKC work correctly and it was manufactured around May 2019. I bought a refurbished 80 series transmitter and it works as well. In the settings menu just type restart in the search box at the top  to find the correct settings.

**Comment by todddexter** [comment]
Ok, I'll give it a shot next time I want to restart. Thanks.

**Comment by Ugitsisgv** [comment]
Changed G6 sensor (81xxx) and transmitter (firmware 2.28.xxx) yesterday using xdrip. Got continual, multiple error messages in the event log and stopped and restarted multiple times - no success.

Today I uninstalled xdrip, started the sensor with the G6 receiver and gave it six hours before reinstalling xdrip on my Note 9, paired it with my SW3 and the SW3 pairing seemed tow stopp readings and I did it several times with the same results. I finally did it once more repeatimg every step above but this time did not pair the Note 9 with the SW3 for a couple hours. Now I am getting slop errors and xdrip is continually asking for initial calibration but xdrip seems to be applying the calibration because my BG reading are accurate when I check. 

I am using Nightly, ob1 checked and native check with SW3 working as the receiver.

The thing I noticed is an error saying the transmitter does have a valid timestamp. Been five hours since I started getting readings and reading are still coming. 

Just thought I would pass it on in case somrone would like to give it a try.

**Comment by Ugitsisgv** [comment]
Oh my goodness. Sorry for the typos above.

**Comment by bpedman** [comment]
My experiences are somewhat similar to @Ugitsisgv. Basically, automated restarts seem to not work anymore on newer firmwares (the actual transmitter id doesn't matter, it's the firmware version). What I have had to do the last couple times is stop the sensor in xdrip, gently remove the transmitter from the sensor, wait about 15 minutes, then reinsert the transmitter, and start the sensor again from xdrip.

**Comment by Ugitsisgv** [comment]
That's good to know but how do you remove the transmitter without removing the sensor?

**Comment by definitivequestion** [comment]
There are videos on YouTube, but essentially you anchor the sensor with copious amounts of tape and use a metal pry tool such as those for electronics repairs.

**Comment by jamorham** [comment]
Just use a 0.46mm guitar pick

**Comment by Ugitsisgv** [comment]
Do I wait for the 10 day stop or remove the transmitter before that point.?

**Comment by todddexter** [comment]
Haven't tried yet, but this video looks promising: https://youtu.be/TNFibgcMU5M
Basically: 1) stop sensor (or wait until it expires)
2) remove transmitter from sensor using test strips on the area located in the video
3) wait 30 minutes
4) put the transmitter back in
5) restart the "new" sensor

**Comment by Ugitsisgv** [comment]
Excellent video. Thanks for that and I assume we can follow the same process with xdrip or do we need to use the Dexcom receiver and connect xdrip after the warmiup?

**Comment by Ugitsisgv** [comment]
Just tried the G6 restart using xdrip on Note 9 with SW3. seems to have worked beautifully but after callibration I got invalid slop. I am running in native using Nightly.

**Comment by Ugitsisgv** [comment]
I used the video directions bt toddexter above.

**Comment by todddexter** [comment]
I just did a successful restart too. Calibration seems wonky after a
restart, but after two or three a little better?

**Comment by Ugitsisgv** [comment]
Same. One hour later and 5 callibration on SW3 and accuracy seems to be returning. Xdip still asks for initial collaboration.

**Comment by todddexter** [comment]
I think less calibrations is better. I was told once that you should
calibrate if the meter shows an error grater than 20% if above 80. If
Actually below 80, then calibrate if the error is more than 20 points off,
so if a blood check shows you are at 70 but the dexcom says you're at 100,
that is more than 20 points when you are below 80, and should calibrate.

**Comment by Ugitsisgv** [comment]
Thanks. I'll follow your advice.

**Comment by Ugitsisgv** [comment]
Notice it did not reset sensor status. Still says 10 days.

**Comment by Ugitsisgv** [comment]
Gave it 24 hours but readings were all over the place. Stopped and restarted again today - same issue. Think I will just have to use new sensor.

**Comment by Dainem21** [comment]
Hello,

if I see it correctly I already got the new transmitter. But I have no issues.

My procedure to start the sensor:
1) Stop the old one and wait until it is stopped. 
               Queue must be empty under status.

<This is special, no need if only xdrip is used>
_I have an iPhone 8 with the Dexcom app, which I use as backup. Bluetooth is forbidden for Dexcom. Therefor I stop the sensor in the Dexcom app, too. I switch on Bluetooth for the Dexcom App and start the sensor.  Without waiting for the App to connect I switch of Bluetooth and block it again for the Dexcom app._ 
<xDrip+>
2) I start a new sensor in xDrip and enter Code. 
3) Wait for the warmup to finish. During this yDrip will connect to the sensor and you see the countdown.
4)Working
<This is special, no need if only xdrip is used>
  _The iPhone must stay disconnected to the sensor during its warm up. If the warm up is done, I can switch between xDrip on Android and Dexcom on the iPhone. Of course only one at the same time_

Please find my xDrip settings here:
![Screenshot_20191112-191821](https://user-images.githubusercontent.com/41136910/68700028-85648200-0584-11ea-8260-58cb61cc8e7e.png)
![Screenshot_20191112-192037](https://user-images.githubusercontent.com/41136910/68700037-8ac1cc80-0584-11ea-937f-58075d968cf8.png)
![Screenshot_20191112-192046](https://user-images.githubusercontent.com/41136910/68700050-8f868080-0584-11ea-870a-4a7a8add88af.png)
![Screenshot_20191112-192103](https://user-images.githubusercontent.com/41136910/68700077-9c0ad900-0584-11ea-9662-5661e8b8198b.png)
![Screenshot_20191112-192111](https://user-images.githubusercontent.com/41136910/68700082-9e6d3300-0584-11ea-8fa8-33285a633778.png)
![Screenshot_20191112-192119](https://user-images.githubusercontent.com/41136910/68700091-a200ba00-0584-11ea-9c9f-6edb2c41a07b.png)
![Screenshot_20191112-192132](https://user-images.githubusercontent.com/41136910/68700101-a4fbaa80-0584-11ea-8029-fa019e7bf3fe.png)
![Screenshot_20191112-192152](https://user-images.githubusercontent.com/41136910/68700112-ac22b880-0584-11ea-82b5-c3664acc45b3.png)
![Screenshot_20191112-192203](https://user-images.githubusercontent.com/41136910/68700126-b2189980-0584-11ea-8df4-886ce3515af2.png)
![Screenshot_20191112-192212](https://user-images.githubusercontent.com/41136910/68700135-b3e25d00-0584-11ea-9d3b-66920ebaf3e1.png)
![Screenshot_20191112-192223](https://user-images.githubusercontent.com/41136910/68700139-b644b700-0584-11ea-893a-e5a1ec07c9ac.png)
![Screenshot_20191112-192234](https://user-images.githubusercontent.com/41136910/68700143-b775e400-0584-11ea-8088-f089b655be10.png)
![Screenshot_20191112-192240](https://user-images.githubusercontent.com/41136910/68700150-b9d83e00-0584-11ea-864a-f75f384b708a.png)

**Comment by Ugitsisgv** [comment]
Thanks. See what I can do. Hope I can get it working so I don't have to change to less expensive sensor. I have used Medtronic and Dexcom and the G6 is, by far, is the more accurate and I haven't heard the best about Libre.

**Comment by Ugitsisgv** [comment]
When u say queue must be empty are you speaking of sensor queue?

**Comment by Ugitsisgv** [comment]
I want to thank both of you for helping me. Electronics are not easy for the elderly because we didn't grow up with them. Beyond that I'm xlassified as a type 2 diabetic but I'm actually MODY 1. If I understand it correctly, if you live long enough, you eventually move from a type 2 diabetic to a type one because the pancreas will eventually just quit producing eyelets. It's very kind of you to help me out and it's very much appreciated. You're gone above and beyond!

**Comment by Ugitsisgv** [comment]
Tried everything and nothing worked. Got multiple errors. Finally uninstalled xdrip. Put in a new G6 sensor. Started the sensor using the Dexcom G6 receiver. Waited for the  two hours lus an additional hour before reinstalleing xdrip. Once I installed xdrip it pretty much did the rest and I was able to turn off the receiver and follow my readings on my sw3. Don't know what will happen when I try to restart the next time because I'm again working with a 81xxx transmitter. At least I can use my Sony SmartWatch this way if only for the 10 days.

**Comment by Ugitsisgv** [comment]
Tried everything once again to restart G6 with xdrip and SW3 and nothing works. I can restart, however, with G6 receiver and am on day 2. It works fine thusfar but I have to carry the rceiver everywhere. I literally cannot  be more than 10 ft. away.  I followed the  before mentioned video. 
-stopped sensor
-deleted xdrip
-popped out transmitter
-waited 40 minutes
-cleaned transmitter and returned to the sensor
-started with G6 receiver

Reading have been accurate thusfar.

**Comment by Ugitsisgv** [comment]
If I have a G6 receiver running a 81XXX sensor and I want to start xdrip, is there a particular procedure? For example, can I leave the G6 receiver running and xdrip pick up on the existing session once it's installed?

**Comment by todddexter** [comment]
I'd be interested in this answer as well. I know bluetooth devices can be
finicky about what they are connected to/how many connections, etc. This is
the main reason I avoid using xdrip or even the dexcom app on a phone. I
don't want different devices sending conflicting signals to the transmitter.

**Comment by wouterla** [comment]
I seem to be having the same issue as described here.
Event log is telling me:
Got unknown packet rx: D0002715
And then a BleGattCharacteristicException, status 133, description 'CHARACTERISTIC_WRITE'.

**Comment by Ugitsisgv** [comment]
Well, restart would not work with the G6 receiver this time. Trying with xdrip nightly but it hasn't worked in the last couple months.

**Comment by Ugitsisgv** [comment]
On xdrip restart, the status says the SW3 is getting readings but no reading displayed.

**Comment by Ugitsisgv** [comment]
Here's the latest thing I have noticed with the 81xxx transmitter. I absolutely cannot do a restart and I can no longer run the G6 receiver, Note 9 xdrip and SW3 simultaneously. I start the sensor with the receiver. If I start with xdrip I get  a couple errors.  A packet error was a new one to me. Once the receiver is working I start xdrip on my Note 9 but if I have wear activated, the phone will not receive readings. Once the phone is receiving reading, I have to shutdown the receiver to get the SW3 to connect. If I try to connect the smartwatch with the receiver and phone rumming, the Note 9 looses readings. Not sure what it means but it may be a clue for programmers. My best guess would be Dexcom has built in a connection limit.

**Comment by Ugitsisgv** [comment]
Have to add to the above the 81xxx transmitter is using firmware 2.18.2.88.

**Comment by cyrusbyte** [comment]
Since we know that newer transmitters are not able to be restarted can we add a option to set an alert x hours before sensor will stop?   This would be great!

**Comment by MussumD** [comment]
I just restarted a new transmitter successfully. I was having the same issues everyone else has had but I don't use a Dexcom receiver and use a Tandem X2 with the CGM function. I stopped the sensor in xdrip, restarted it in xdrip using code 0000, let it warm up for about 20 minutes, then stopped it again and restarted it again with the right code. I did receive a sensor failed error and invalid error once during the warmup but dismissed these errors and the warmup continued and successfully completed. I started the sensor process on the Tandem shortly after starting it on xdrip and skipped entering the code as advised since I had already started it on my mobile device. Attached are before and after restarting screenshots.
![Screenshot_20191213-162048_xDrip+](https://user-images.githubusercontent.com/51686459/70840726-1a97a800-1dc9-11ea-9e62-186d10c37a30.jpg)

![Screenshot_20191212-203752_xDrip+](https://user-images.githubusercontent.com/51686459/70840690-d3111c00-1dc8-11ea-8b5b-42d49c3e94a6.jpg)

**Comment by Ugitsisgv** [comment]
When you said you dismissed the  error do you mean you simply ignored it?

**Comment by MussumD** [comment]
Yes, I simply swiped the errors from my notification list

**Comment by Ugitsisgv** [comment]
Thanks so much. I will give it a try.

**Comment by Ugitsisgv** [comment]
Did you let the sensor end before restarting?

**Comment by MussumD** [comment]
Yes the sensor had ended and I was no longer receiving readings when I first attempted to restart.

**Comment by Ugitsisgv** [comment]
Giving up for the time being. Thusfar every 81xxx transmitter goes 30 to 48 days, drops off the Bluetooth list and will only run on dexcom receiver. No plans by Sony or Apple to create a watch that works as a receiver according to company reps though dexcom rep said they had expected an Apple product by the end of 2019 and admitted most smartwatchs have the capability of connecting. My next transmitter will be a 8G and I have not found anyone thusfar who runs it successfully with anything but the Dexcom receiver.

**Comment by jrmantei** [comment]
Do we know if there is any work being done by the Xdrip team to correct these issues and make 81xxxx and 8Gxxxx transmitters work correctly with the Android app?

Thanks.

**Comment by Ugitsisgv** [comment]
I started a new 81xxx transmitter with the Dexcom receiver, waited 1 day then installed xdrip and connected. Still cannot do any restarts. Two interesting things. I can connect either my Note 9 or SW3 but not both even if the Dexcom receiver is powered off. If I connect both neither receives a signal. Also noticed with the two prior 81xxx transmitters, once I attempted a restart, both dropped off my Bluetooth list. I suspect blocks have been built into the programming by Dexcom.

**Comment by Navid200** [comment]
Instructions for restarting a G6 sensor are available in the facebook group.
https://www.facebook.com/groups/xDripG5/permalink/4521043737969086
It goes over the different behaviors of the different versions of G6.
You can also ask in the Gitter room,   https://gitter.im/jamorham/xDrip-plus


I would like to close this issue.
Please respond if you have any questions or concerns about this.

**Comment by Navid200** [comment]
We currently can only hard reset, and perform preemptive restarts on, G6 if the firmware version is 1.6.5.25.  This includes all 80XXXX and some 81XXXX transmitters.  

Only G6 transmitters with serial numbers starting with 80 and 81 transmit raw values.  Therefore, we can only use the non-native mode on those.

Restarting any G6 transmitter whose serial number does not start with 80 or 81 requires the temporary removal of the transmitter. 

This is neither a bug, any longer, nor a feasible feature request.  Therefore, I am closing it.  
We can always reopen it if needed.  
If we find a way to change any of these limitations, we will update the documentation.
